
<h2> Workflow Automation POC
Overview </h2>

This notebook demonstrates an end-to-end workflow automation platform built using:

Synthetic workflow data generation
SQLite-based persistence layer
Retrieval and search capabilities
MCP-compatible tools
Google ADK agents
Multi-agent workflow orchestration
REST API integration

The objective is to validate the workflow architecture and agent interactions before refactoring into a production-grade modular codebase.
---
Environment Setup
Purpose

Install and configure dependencies required for:

Agent execution
MCP integration
Vector search
Database access
API serving

This section is intentionally notebook-based to simplify experimentation.


## Workflow Architecture


Data Layer
├── Synthetic Workflow Data
└── SQLite Database

Tool Layer
├── Search Tools
├── Workflow Tools
└── Business Functions

Agent Layer
├── Planner Agent
├── Reviewer Agent
└── Executor Agent

Orchestration Layer
└── Workflow Automation Engine

Integration Layer
├── MCP Server
└── REST API Endpoints
```
```

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load
import numpy as np
import pandas as pd
from datetime import datetime
import json
import sqlite3
from typing import Any, Dict, List, Optional
# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
#Under progress

!pip install google-adk

Requirement already satisfied: google-adk in /usr/local/lib/python3.12/dist-packages (1.29.0)
Requirement already satisfied: PyYAML<7.0.0,>=6.0.2 in /usr/local/lib/python3.12/dist-packages (from google-adk) (6.0.3)
Requirement already satisfied: aiosqlite>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (0.22.1)
Requirement already satisfied: anyio<5.0.0,>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (4.13.0)
Requirement already satisfied: authlib<2.0.0,>=1.6.6 in /usr/local/lib/python3.12/dist-packages (from google-adk) (1.7.2)
Requirement already satisfied: click<9.0.0,>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from google-adk) (8.4.1)
Requirement already satisfied: fastapi<1.0.0,>=0.124.1 in /usr/local/lib/python3.12/dist-packages (from google-adk) (0.136.3)
Requirement already satisfied: google-api-python-client<3.0.0,>=2.157.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (2.197.0)
Requirement already satisfied: google-auth>=2.47.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[pyopenssl]>=2.47.0->google-adk) (2.47.0)
Requirement already satisfied: google-cloud-aiplatform<2.0.0,>=1.132.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (1.157.0)
Requirement already satisfied: google-cloud-bigquery-storage>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (2.39.0)
Requirement already satisfied: google-cloud-bigquery>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (3.41.0)
Requirement already satisfied: google-cloud-bigtable>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (2.38.0)
Requirement already satisfied: google-cloud-dataplex<3.0.0,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (2.20.0)
Requirement already satisfied: google-cloud-discoveryengine<0.14.0,>=0.13.12 in /usr/local/lib/python3.12/dist-packages (from google-adk) (0.13.12)
Requirement already satisfied: google-cloud-pubsub<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (2.39.0)
Requirement already satisfied: google-cloud-secret-manager<3.0.0,>=2.22.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (2.29.0)
Requirement already satisfied: google-cloud-spanner<4.0.0,>=3.56.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (3.67.0)
Requirement already satisfied: google-cloud-speech<3.0.0,>=2.30.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (2.40.0)
Requirement already satisfied: google-cloud-storage<4.0.0,>=2.18.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (3.11.0)
Requirement already satisfied: google-genai<2.0.0,>=1.64.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (1.68.0)
Requirement already satisfied: graphviz<1.0.0,>=0.20.2 in /usr/local/lib/python3.12/dist-packages (from google-adk) (0.21)
Requirement already satisfied: httpx<1.0.0,>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (0.28.1)
Requirement already satisfied: jsonschema<5.0.0,>=4.23.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (4.26.0)
Requirement already satisfied: mcp<2.0.0,>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (1.27.2)
Requirement already satisfied: opentelemetry-api<1.39.0,>=1.36.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (1.38.0)
Requirement already satisfied: opentelemetry-exporter-gcp-logging<2.0.0,>=1.9.0a0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (1.11.0a0)
Requirement already satisfied: opentelemetry-exporter-gcp-monitoring<2.0.0,>=1.9.0a0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (1.12.0a0)
Requirement already satisfied: opentelemetry-exporter-gcp-trace<2.0.0,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (1.12.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-http>=1.36.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (1.38.0)
Requirement already satisfied: opentelemetry-resourcedetector-gcp<2.0.0,>=1.9.0a0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (1.12.0a0)
Requirement already satisfied: opentelemetry-sdk<1.39.0,>=1.36.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (1.38.0)
Requirement already satisfied: pyarrow>=14.0.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (18.1.0)
Requirement already satisfied: pydantic<3.0.0,>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (2.12.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.9.0.post0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (2.9.0.post0)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (1.2.2)
Requirement already satisfied: requests<3.0.0,>=2.32.4 in /usr/local/lib/python3.12/dist-packages (from google-adk) (2.32.4)
Requirement already satisfied: sqlalchemy-spanner>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (1.19.0)
Requirement already satisfied: sqlalchemy<3.0.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (2.0.50)
Requirement already satisfied: starlette<1.0.0,>=0.49.1 in /usr/local/lib/python3.12/dist-packages (from google-adk) (0.52.1)
Requirement already satisfied: tenacity<10.0.0,>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (9.1.4)
Requirement already satisfied: typing-extensions<5,>=4.5 in /usr/local/lib/python3.12/dist-packages (from google-adk) (4.15.0)
Requirement already satisfied: tzlocal<6.0,>=5.3 in /usr/local/lib/python3.12/dist-packages (from google-adk) (5.3.1)
Requirement already satisfied: uvicorn<1.0.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (0.49.0)
Requirement already satisfied: watchdog<7.0.0,>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from google-adk) (6.0.0)
Requirement already satisfied: websockets<16.0.0,>=15.0.1 in /usr/local/lib/python3.12/dist-packages (from google-adk) (15.0.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.9.0->google-adk) (3.18)
Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (from authlib<2.0.0,>=1.6.6->google-adk) (48.0.1)
Requirement already satisfied: joserfc>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from authlib<2.0.0,>=1.6.6->google-adk) (1.7.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0.0,>=0.124.1->google-adk) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0.0,>=0.124.1->google-adk) (0.0.4)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client<3.0.0,>=2.157.0->google-adk) (0.31.2)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client<3.0.0,>=2.157.0->google-adk) (0.4.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client<3.0.0,>=2.157.0->google-adk) (2.30.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client<3.0.0,>=2.157.0->google-adk) (4.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.47.0->google-auth[pyopenssl]>=2.47.0->google-adk) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.47.0->google-auth[pyopenssl]>=2.47.0->google-adk) (4.9.1)
Requirement already satisfied: pyopenssl>=20.0.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[pyopenssl]>=2.47.0->google-adk) (26.2.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform<2.0.0,>=1.132.0->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (2026.5.20)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform<2.0.0,>=1.132.0->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (1.28.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform<2.0.0,>=1.132.0->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (5.29.6)
Requirement already satisfied: packaging>=14.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform<2.0.0,>=1.132.0->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (26.2)
Requirement already satisfied: google-cloud-resource-manager<3.0.0,>=1.3.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform<2.0.0,>=1.132.0->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (1.17.0)
Requirement already satisfied: docstring_parser<1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform<2.0.0,>=1.132.0->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (0.18.0)
Requirement already satisfied: cloudpickle<4.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (3.1.2)
Requirement already satisfied: google-cloud-trace<2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (1.19.0)
Requirement already satisfied: google-cloud-logging<4 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (3.16.0)
Requirement already satisfied: google-cloud-iam in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (2.23.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (3.14.1)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery>=2.2.0->google-adk) (2.6.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery>=2.2.0->google-adk) (2.10.0)
Requirement already satisfied: grpcio<2.0.0,>=1.59.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery-storage>=2.0.0->google-adk) (1.81.0)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.12.4 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigtable>=2.32.0->google-adk) (0.14.4)
Requirement already satisfied: google-crc32c<2.0.0dev,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigtable>=2.32.0->google-adk) (1.8.0)
Requirement already satisfied: grpcio-status>=1.51.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-pubsub<3.0.0,>=2.0.0->google-adk) (1.71.2)
Requirement already satisfied: grpc-interceptor>=0.15.4 in /usr/local/lib/python3.12/dist-packages (from google-cloud-spanner<4.0.0,>=3.56.0->google-adk) (0.15.4)
Requirement already satisfied: sqlparse>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from google-cloud-spanner<4.0.0,>=3.56.0->google-adk) (0.5.5)
Requirement already satisfied: opentelemetry-semantic-conventions>=0.43b0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-spanner<4.0.0,>=3.56.0->google-adk) (0.59b0)
Requirement already satisfied: google-cloud-monitoring>=2.16.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-spanner<4.0.0,>=3.56.0->google-adk) (2.31.0)
Requirement already satisfied: mmh3>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-spanner<4.0.0,>=3.56.0->google-adk) (5.2.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.64.0->google-adk) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.64.0->google-adk) (1.3.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.27.0->google-adk) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.27.0->google-adk) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0.0,>=4.23.0->google-adk) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0.0,>=4.23.0->google-adk) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0.0,>=4.23.0->google-adk) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0.0,>=4.23.0->google-adk) (2026.5.1)
Requirement already satisfied: httpx-sse>=0.4 in /usr/local/lib/python3.12/dist-packages (from mcp<2.0.0,>=1.23.0->google-adk) (0.4.3)
Requirement already satisfied: pydantic-settings>=2.5.2 in /usr/local/lib/python3.12/dist-packages (from mcp<2.0.0,>=1.23.0->google-adk) (2.14.1)
Requirement already satisfied: pyjwt>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.10.1->mcp<2.0.0,>=1.23.0->google-adk) (2.13.0)
Requirement already satisfied: python-multipart>=0.0.9 in /usr/local/lib/python3.12/dist-packages (from mcp<2.0.0,>=1.23.0->google-adk) (0.0.32)
Requirement already satisfied: sse-starlette>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from mcp<2.0.0,>=1.23.0->google-adk) (3.4.4)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api<1.39.0,>=1.36.0->google-adk) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.52 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-http>=1.36.0->google-adk) (1.75.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.38.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-http>=1.36.0->google-adk) (1.38.0)
Requirement already satisfied: opentelemetry-proto==1.38.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-http>=1.36.0->google-adk) (1.38.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.12.0->google-adk) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.12.0->google-adk) (2.41.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.9.0.post0->google-adk) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.4->google-adk) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.4->google-adk) (2.5.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=2.0->google-adk) (3.5.1)
Requirement already satisfied: alembic in /usr/local/lib/python3.12/dist-packages (from sqlalchemy-spanner>=1.14.0->google-adk) (1.18.4)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography->authlib<2.0.0,>=1.6.6->google-adk) (2.0.0)
Requirement already satisfied: google-cloud-appengine-logging<2.0.0,>=0.1.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-logging<4->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (1.10.0)
Requirement already satisfied: google-cloud-audit-log<1.0.0,>=0.3.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-logging<4->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (0.6.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client<3.0.0,>=2.157.0->google-adk) (3.3.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api<1.39.0,>=1.36.0->google-adk) (4.1.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.47.0->google-auth[pyopenssl]>=2.47.0->google-adk) (0.6.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->google-cloud-aiplatform[agent-engines]<2.0.0,>=1.132.0->google-adk) (1.24.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic->sqlalchemy-spanner>=1.14.0->google-adk) (1.3.12)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography->authlib<2.0.0,>=1.6.6->google-adk) (3.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic->sqlalchemy-spanner>=1.14.0->google-adk) (3.0.3)

In [3]:
pip install faker

Collecting faker
  Downloading faker-40.23.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.23.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 40.4 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.23.0

In [4]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.5.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.10.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.18.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers) (1.5.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

In [5]:
!pip install --upgrade chromadb

Collecting chromadb
  Downloading chromadb-1.5.9-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.5.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.14.1)
Collecting pybase64>=1.4.1 (from chromadb)
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.49.0)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.0.2)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.15.0)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.27.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.38.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.42.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.38.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading pypika-0.51.1-py2.py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.67.3)
Collecting overrides>=7.3.1 (from chromadb)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.81.0)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.25.1)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-36.0.2-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.9)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.2)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2026.5.1)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.4)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Requirement already satisfied: aiohttp<4.0.0,>=3.13.5 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (3.14.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.75.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.42.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.42.1-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.42.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.42.1-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.42.1-py3-none-any.whl.metadata (1.7 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.42.1-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-semantic-conventions==0.63b1 (from opentelemetry-sdk>=1.2.0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.20.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb) (1.18.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.4.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.8.0)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.2.0)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.24.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.5.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.7)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (4.1.0)
Downloading chromadb-1.5.9-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 41.0 MB/s eta 0:00:00
Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 13.8 MB/s eta 0:00:00
Downloading build-1.5.0-py3-none-any.whl (26 kB)
Downloading kubernetes-36.0.2-py2.py3-none-any.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 76.5 MB/s eta 0:00:00
Downloading onnxruntime-1.27.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 56.3 MB/s eta 0:00:00
Downloading opentelemetry_exporter_otlp_proto_grpc-1.42.1-py3-none-any.whl (19 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.42.1-py3-none-any.whl (17 kB)
Downloading opentelemetry_proto-1.42.1-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 3.6 MB/s eta 0:00:00
Downloading opentelemetry_sdk-1.42.1-py3-none-any.whl (170 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 6.7 MB/s eta 0:00:00
Downloading opentelemetry_api-1.42.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 2.8 MB/s eta 0:00:00
Downloading opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl (203 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 20.0 MB/s eta 0:00:00
Downloading overrides-7.7.0-py3-none-any.whl (17 kB)
Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 3.8 MB/s eta 0:00:00
Downloading pypika-0.51.1-py2.py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 3.6 MB/s eta 0:00:00
Downloading durationpy-0.10-py3-none-any.whl (3.9 kB)
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Installing collected packages: pypika, durationpy, pyproject_hooks, pybase64, overrides, opentelemetry-proto, opentelemetry-api, onnxruntime, bcrypt, opentelemetry-semantic-conventions, opentelemetry-exporter-otlp-proto-common, build, opentelemetry-sdk, kubernetes, opentelemetry-exporter-otlp-proto-grpc, chromadb
  Attempting uninstall: opentelemetry-proto
    Found existing installation: opentelemetry-proto 1.38.0
    Uninstalling opentelemetry-proto-1.38.0:
      Successfully uninstalled opentelemetry-proto-1.38.0
  Attempting uninstall: opentelemetry-api
    Found existing installation: opentelemetry-api 1.38.0
    Uninstalling opentelemetry-api-1.38.0:
      Successfully uninstalled opentelemetry-api-1.38.0
  Attempting uninstall: opentelemetry-semantic-conventions
    Found existing installation: opentelemetry-semantic-conventions 0.59b0
    Uninstalling opentelemetry-semantic-conventions-0.59b0:
      Successfully uninstalled opentelemetry-semantic-conventions-0.59b0
  Attempting uninstall: opentelemetry-exporter-otlp-proto-common
    Found existing installation: opentelemetry-exporter-otlp-proto-common 1.38.0
    Uninstalling opentelemetry-exporter-otlp-proto-common-1.38.0:
      Successfully uninstalled opentelemetry-exporter-otlp-proto-common-1.38.0
  Attempting uninstall: opentelemetry-sdk
    Found existing installation: opentelemetry-sdk 1.38.0
    Uninstalling opentelemetry-sdk-1.38.0:
      Successfully uninstalled opentelemetry-sdk-1.38.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.42.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
Successfully installed bcrypt-5.0.0 build-1.5.0 chromadb-1.5.9 durationpy-0.10 kubernetes-36.0.2 onnxruntime-1.27.0 opentelemetry-api-1.42.1 opentelemetry-exporter-otlp-proto-common-1.42.1 opentelemetry-exporter-otlp-proto-grpc-1.42.1 opentelemetry-proto-1.42.1 opentelemetry-sdk-1.42.1 opentelemetry-semantic-conventions-0.63b1 overrides-7.7.0 pybase64-1.4.3 pypika-0.51.1 pyproject_hooks-1.2.0

In [6]:
!pip install fastmcp  # or your MCP server package

Collecting fastmcp
  Downloading fastmcp-3.4.2-py3-none-any.whl.metadata (8.5 kB)
Collecting fastmcp-slim==3.4.2 (from fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading fastmcp_slim-3.4.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: platformdirs>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim==3.4.2->fastmcp-slim[client,server]==3.4.2->fastmcp) (4.10.0)
Requirement already satisfied: pydantic-settings>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim==3.4.2->fastmcp-slim[client,server]==3.4.2->fastmcp) (2.14.1)
Requirement already satisfied: pydantic>=2.11.7 in /usr/local/lib/python3.12/dist-packages (from pydantic[email]>=2.11.7->fastmcp-slim==3.4.2->fastmcp-slim[client,server]==3.4.2->fastmcp) (2.12.3)
Requirement already satisfied: python-dotenv>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim==3.4.2->fastmcp-slim[client,server]==3.4.2->fastmcp) (1.2.2)
Requirement already satisfied: rich>=13.9.4 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim==3.4.2->fastmcp-slim[client,server]==3.4.2->fastmcp) (13.9.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim==3.4.2->fastmcp-slim[client,server]==3.4.2->fastmcp) (4.15.0)
Requirement already satisfied: authlib>=1.6.11 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim[client,server]==3.4.2->fastmcp) (1.7.2)
Collecting exceptiongroup>=1.2.2 (from fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading exceptiongroup-1.3.1-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: httpx<1.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim[client,server]==3.4.2->fastmcp) (0.28.1)
Requirement already satisfied: mcp<2.0,>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim[client,server]==3.4.2->fastmcp) (1.27.2)
Requirement already satisfied: opentelemetry-api>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim[client,server]==3.4.2->fastmcp) (1.42.1)
Collecting py-key-value-aio<0.5.0,>=0.4.4 (from py-key-value-aio[filetree,keyring,memory]<0.5.0,>=0.4.4; extra == "client"->fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading py_key_value_aio-0.4.5-py3-none-any.whl.metadata (16 kB)
Collecting starlette>=1.0.1 (from fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading starlette-1.3.1-py3-none-any.whl.metadata (6.4 kB)
Collecting cyclopts>=4.0.0 (from fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading cyclopts-4.18.0-py3-none-any.whl.metadata (12 kB)
Collecting griffelib>=2.0.0 (from fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading griffelib-2.0.2-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: joserfc>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim[client,server]==3.4.2->fastmcp) (1.7.1)
Collecting jsonref>=1.1.0 (from fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading jsonref-1.1.0-py3-none-any.whl.metadata (2.7 kB)
Collecting jsonschema-path>=0.3.4 (from fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading jsonschema_path-0.5.0-py3-none-any.whl.metadata (8.1 kB)
Collecting openapi-pydantic>=0.5.1 (from fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading openapi_pydantic-0.5.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim[client,server]==3.4.2->fastmcp) (26.2)
Requirement already satisfied: pyperclip>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim[client,server]==3.4.2->fastmcp) (1.11.0)
Requirement already satisfied: python-multipart>=0.0.26 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim[client,server]==3.4.2->fastmcp) (0.0.32)
Requirement already satisfied: pyyaml<7.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim[client,server]==3.4.2->fastmcp) (6.0.3)
Collecting uncalled-for>=0.2.0 (from fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading uncalled_for-0.3.2-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: uvicorn>=0.35 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim[client,server]==3.4.2->fastmcp) (0.49.0)
Requirement already satisfied: watchfiles>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim[client,server]==3.4.2->fastmcp) (1.2.0)
Requirement already satisfied: websockets>=15.0.1 in /usr/local/lib/python3.12/dist-packages (from fastmcp-slim[client,server]==3.4.2->fastmcp) (15.0.1)
Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (from authlib>=1.6.11->fastmcp-slim[client,server]==3.4.2->fastmcp) (48.0.1)
Requirement already satisfied: attrs>=23.1.0 in /usr/local/lib/python3.12/dist-packages (from cyclopts>=4.0.0->fastmcp-slim[client,server]==3.4.2->fastmcp) (26.1.0)
Requirement already satisfied: docstring-parser<4.0,>=0.15 in /usr/local/lib/python3.12/dist-packages (from cyclopts>=4.0.0->fastmcp-slim[client,server]==3.4.2->fastmcp) (0.18.0)
Collecting rich-rst<3.0.0,>=1.3.1 (from cyclopts>=4.0.0->fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading rich_rst-2.0.1-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.28.1->fastmcp-slim[client,server]==3.4.2->fastmcp) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.28.1->fastmcp-slim[client,server]==3.4.2->fastmcp) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.28.1->fastmcp-slim[client,server]==3.4.2->fastmcp) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.28.1->fastmcp-slim[client,server]==3.4.2->fastmcp) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.28.1->fastmcp-slim[client,server]==3.4.2->fastmcp) (0.16.0)
Collecting pathable<0.7.0,>=0.6.0 (from jsonschema-path>=0.3.4->fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading pathable-0.6.0-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: referencing<0.38.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema-path>=0.3.4->fastmcp-slim[client,server]==3.4.2->fastmcp) (0.37.0)
Requirement already satisfied: httpx-sse>=0.4 in /usr/local/lib/python3.12/dist-packages (from mcp<2.0,>=1.24.0->fastmcp-slim[client,server]==3.4.2->fastmcp) (0.4.3)
Requirement already satisfied: jsonschema>=4.20.0 in /usr/local/lib/python3.12/dist-packages (from mcp<2.0,>=1.24.0->fastmcp-slim[client,server]==3.4.2->fastmcp) (4.26.0)
Requirement already satisfied: pyjwt>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.10.1->mcp<2.0,>=1.24.0->fastmcp-slim[client,server]==3.4.2->fastmcp) (2.13.0)
Requirement already satisfied: sse-starlette>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from mcp<2.0,>=1.24.0->fastmcp-slim[client,server]==3.4.2->fastmcp) (3.4.4)
Requirement already satisfied: typing-inspection>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from mcp<2.0,>=1.24.0->fastmcp-slim[client,server]==3.4.2->fastmcp) (0.4.2)
Requirement already satisfied: beartype>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from py-key-value-aio<0.5.0,>=0.4.4->py-key-value-aio[filetree,keyring,memory]<0.5.0,>=0.4.4; extra == "client"->fastmcp-slim[client,server]==3.4.2->fastmcp) (0.22.9)
Collecting aiofile>=3.5.0 (from py-key-value-aio[filetree,keyring,memory]<0.5.0,>=0.4.4; extra == "client"->fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading aiofile-3.11.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: keyring>=25.6.0 in /usr/local/lib/python3.12/dist-packages (from py-key-value-aio[filetree,keyring,memory]<0.5.0,>=0.4.4; extra == "client"->fastmcp-slim[client,server]==3.4.2->fastmcp) (25.7.0)
Requirement already satisfied: cachetools>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from py-key-value-aio[filetree,keyring,memory]<0.5.0,>=0.4.4; extra == "client"->fastmcp-slim[client,server]==3.4.2->fastmcp) (6.2.6)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11.7->pydantic[email]>=2.11.7->fastmcp-slim==3.4.2->fastmcp-slim[client,server]==3.4.2->fastmcp) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11.7->pydantic[email]>=2.11.7->fastmcp-slim==3.4.2->fastmcp-slim[client,server]==3.4.2->fastmcp) (2.41.4)
Collecting email-validator>=2.0.0 (from pydantic[email]>=2.11.7->fastmcp-slim==3.4.2->fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading email_validator-2.3.0-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.9.4->fastmcp-slim==3.4.2->fastmcp-slim[client,server]==3.4.2->fastmcp) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.9.4->fastmcp-slim==3.4.2->fastmcp-slim[client,server]==3.4.2->fastmcp) (2.20.0)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.35->fastmcp-slim[client,server]==3.4.2->fastmcp) (8.4.1)
Collecting caio~=0.9.0 (from aiofile>=3.5.0->py-key-value-aio[filetree,keyring,memory]<0.5.0,>=0.4.4; extra == "client"->fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading caio-0.9.25-cp312-cp312-manylinux_2_34_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography->authlib>=1.6.11->fastmcp-slim[client,server]==3.4.2->fastmcp) (2.0.0)
Collecting dnspython>=2.0.0 (from email-validator>=2.0.0->pydantic[email]>=2.11.7->fastmcp-slim==3.4.2->fastmcp-slim[client,server]==3.4.2->fastmcp)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.20.0->mcp<2.0,>=1.24.0->fastmcp-slim[client,server]==3.4.2->fastmcp) (2025.9.1)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.20.0->mcp<2.0,>=1.24.0->fastmcp-slim[client,server]==3.4.2->fastmcp) (2026.5.1)
Requirement already satisfied: SecretStorage>=3.2 in /usr/local/lib/python3.12/dist-packages (from keyring>=25.6.0->py-key-value-aio[filetree,keyring,memory]<0.5.0,>=0.4.4; extra == "client"->fastmcp-slim[client,server]==3.4.2->fastmcp) (3.5.0)
Requirement already satisfied: jeepney>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from keyring>=25.6.0->py-key-value-aio[filetree,keyring,memory]<0.5.0,>=0.4.4; extra == "client"->fastmcp-slim[client,server]==3.4.2->fastmcp) (0.9.0)
Requirement already satisfied: jaraco.classes in /usr/local/lib/python3.12/dist-packages (from keyring>=25.6.0->py-key-value-aio[filetree,keyring,memory]<0.5.0,>=0.4.4; extra == "client"->fastmcp-slim[client,server]==3.4.2->fastmcp) (3.4.0)
Requirement already satisfied: jaraco.functools in /usr/local/lib/python3.12/dist-packages (from keyring>=25.6.0->py-key-value-aio[filetree,keyring,memory]<0.5.0,>=0.4.4; extra == "client"->fastmcp-slim[client,server]==3.4.2->fastmcp) (4.5.0)
Requirement already satisfied: jaraco.context in /usr/local/lib/python3.12/dist-packages (from keyring>=25.6.0->py-key-value-aio[filetree,keyring,memory]<0.5.0,>=0.4.4; extra == "client"->fastmcp-slim[client,server]==3.4.2->fastmcp) (6.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.9.4->fastmcp-slim==3.4.2->fastmcp-slim[client,server]==3.4.2->fastmcp) (0.1.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography->authlib>=1.6.11->fastmcp-slim[client,server]==3.4.2->fastmcp) (3.0)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.12/dist-packages (from jaraco.classes->keyring>=25.6.0->py-key-value-aio[filetree,keyring,memory]<0.5.0,>=0.4.4; extra == "client"->fastmcp-slim[client,server]==3.4.2->fastmcp) (10.8.0)
Downloading fastmcp-3.4.2-py3-none-any.whl (8.0 kB)
Downloading fastmcp_slim-3.4.2-py3-none-any.whl (749 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 749.2/749.2 kB 16.6 MB/s eta 0:00:00
Downloading cyclopts-4.18.0-py3-none-any.whl (221 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 221.2/221.2 kB 10.3 MB/s eta 0:00:00
Downloading exceptiongroup-1.3.1-py3-none-any.whl (16 kB)
Downloading griffelib-2.0.2-py3-none-any.whl (142 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.4/142.4 kB 9.5 MB/s eta 0:00:00
Downloading jsonref-1.1.0-py3-none-any.whl (9.4 kB)
Downloading jsonschema_path-0.5.0-py3-none-any.whl (24 kB)
Downloading openapi_pydantic-0.5.1-py3-none-any.whl (96 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.4/96.4 kB 10.3 MB/s eta 0:00:00
Downloading py_key_value_aio-0.4.5-py3-none-any.whl (170 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.0/170.0 kB 14.8 MB/s eta 0:00:00
Downloading starlette-1.3.1-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.6/73.6 kB 7.6 MB/s eta 0:00:00
Downloading uncalled_for-0.3.2-py3-none-any.whl (11 kB)
Downloading aiofile-3.11.1-py3-none-any.whl (20 kB)
Downloading email_validator-2.3.0-py3-none-any.whl (35 kB)
Downloading pathable-0.6.0-py3-none-any.whl (18 kB)
Downloading rich_rst-2.0.1-py3-none-any.whl (272 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 272.9/272.9 kB 17.0 MB/s eta 0:00:00
Downloading caio-0.9.25-cp312-cp312-manylinux_2_34_x86_64.whl (80 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.2/80.2 kB 5.8 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 25.5 MB/s eta 0:00:00
Installing collected packages: uncalled-for, py-key-value-aio, pathable, jsonref, griffelib, exceptiongroup, dnspython, caio, starlette, jsonschema-path, email-validator, aiofile, rich-rst, openapi-pydantic, fastmcp-slim, cyclopts, fastmcp
  Attempting uninstall: starlette
    Found existing installation: starlette 0.52.1
    Uninstalling starlette-0.52.1:
      Successfully uninstalled starlette-0.52.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 5.50.0 requires starlette<1.0,>=0.40.0, but you have starlette 1.3.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.42.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
google-adk 1.29.0 requires starlette<1.0.0,>=0.49.1, but you have starlette 1.3.1 which is incompatible.
Successfully installed aiofile-3.11.1 caio-0.9.25 cyclopts-4.18.0 dnspython-2.8.0 email-validator-2.3.0 exceptiongroup-1.3.1 fastmcp-3.4.2 fastmcp-slim-3.4.2 griffelib-2.0.2 jsonref-1.1.0 jsonschema-path-0.5.0 openapi-pydantic-0.5.1 pathable-0.6.0 py-key-value-aio-0.4.5 rich-rst-2.0.1 starlette-1.3.1 uncalled-for-0.3.2

In [7]:
# -----------------------------
# Standard Libraries
# -----------------------------
import sqlite3
import json
import uuid
import time
import threading
from datetime import datetime

# -----------------------------
# Data Manipulation & Visualization
# -----------------------------
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------------
# Event & Communication Simulation
# -----------------------------
from queue import Queue

# -----------------------------
# Notebook Display Helpers
# -----------------------------
from IPython.display import display, Markdown

In [8]:
import sqlite3
import os

# -----------------------------
# Database file paths
# -----------------------------
employee_db = "employees.db"
session_memory_db = "session_memory.db"
workflow_db = "workflows.db"
document_db = "documents.db"
access_db = "access_logs.db"
asset_db = "assets.db"             # ⭐ NEW

# -----------------------------
# Helper: Create a connection with dict rows enabled
# -----------------------------
def connect_db(path):
    # Ensure parent folder exists if needed
    if "/" in path:
        os.makedirs(os.path.dirname(path), exist_ok=True)

    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    return conn

# -----------------------------
# Connect to all SQLite databases
# -----------------------------
conn_employee = connect_db(employee_db)
conn_session = connect_db(session_memory_db)
conn_workflow = connect_db(workflow_db)
conn_document = connect_db(document_db)
conn_access = connect_db(access_db)
conn_asset = connect_db(asset_db)          # ⭐ NEW

# -----------------------------
# Create cursors
# -----------------------------
cur_employee = conn_employee.cursor()
cur_session = conn_session.cursor()
cur_workflow = conn_workflow.cursor()
cur_document = conn_document.cursor()
cur_access = conn_access.cursor()
cur_asset = conn_asset.cursor()            # ⭐ NEW

# -----------------------------
# Sanity checks
# -----------------------------
assert cur_employee, "❌ Employee DB failed to initialize!"
assert cur_session,  "❌ Session Memory DB failed to initialize!"
assert cur_workflow, "❌ Workflow DB failed to initialize!"
assert cur_document, "❌ Document DB failed to initialize!"
assert cur_access,   "❌ Access DB failed to initialize!"
assert cur_asset,    "❌ Asset DB failed to initialize!"     # ⭐ NEW

print("✅ All database connections initialized successfully!")

✅ All database connections initialized successfully!

In [9]:
import sqlite3
import os

# -----------------------------
# Database file paths
# -----------------------------
employee_db = "employees.db"
session_memory_db = "session_memory.db"
workflow_db = "workflows.db"
document_db = "documents.db"
access_db = "access_logs.db"
asset_db = "assets.db"             # ⭐ NEW

# -----------------------------
# Helper: Create a connection with dict rows enabled
# -----------------------------
def connect_db(path):
    # Ensure parent folder exists if needed
    if "/" in path:
        os.makedirs(os.path.dirname(path), exist_ok=True)

    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    return conn

# -----------------------------
# Connect to all SQLite databases
# -----------------------------
conn_employee = connect_db(employee_db)
conn_session = connect_db(session_memory_db)
conn_workflow = connect_db(workflow_db)
conn_document = connect_db(document_db)
conn_access = connect_db(access_db)
conn_asset = connect_db(asset_db)          # ⭐ NEW

# -----------------------------
# Create cursors
# -----------------------------
cur_employee = conn_employee.cursor()
cur_session = conn_session.cursor()
cur_workflow = conn_workflow.cursor()
cur_document = conn_document.cursor()
cur_access = conn_access.cursor()
cur_asset = conn_asset.cursor()            # ⭐ NEW

# -----------------------------
# Sanity checks
# -----------------------------
assert cur_employee, "❌ Employee DB failed to initialize!"
assert cur_session,  "❌ Session Memory DB failed to initialize!"
assert cur_workflow, "❌ Workflow DB failed to initialize!"
assert cur_document, "❌ Document DB failed to initialize!"
assert cur_access,   "❌ Access DB failed to initialize!"
assert cur_asset,    "❌ Asset DB failed to initialize!"     # ⭐ NEW

print("✅ All database connections initialized successfully!")

# ============================================================
# CREATE TABLES (DROP + CREATE)
# ============================================================

# -----------------------------
# Employees
# -----------------------------
cur_employee.execute("DROP TABLE IF EXISTS employees")
cur_employee.execute("""
CREATE TABLE employees (
    employee_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    department TEXT,
    role TEXT,
    hire_date DATE,
    email TEXT,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
""")
conn_employee.commit()

# -----------------------------
# Agent Context / Session
# -----------------------------
cur_session.execute("DROP TABLE IF EXISTS agent_context")
cur_session.execute("""
CREATE TABLE agent_context (
    session_id TEXT PRIMARY KEY,
    agent_name TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    context_json TEXT,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
)
""")
conn_session.commit()

# -----------------------------
# Workflows
# -----------------------------
cur_workflow.execute("DROP TABLE IF EXISTS workflows")
cur_workflow.execute("""
CREATE TABLE workflows (
    workflow_id TEXT PRIMARY KEY,
    workflow_type TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    current_step TEXT,
    status TEXT DEFAULT 'Pending',
    triggered_by TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
)
""")
conn_workflow.commit()

# -----------------------------
# Documents
# -----------------------------
cur_document.execute("DROP TABLE IF EXISTS documents")
cur_document.execute("""
CREATE TABLE documents (
    document_id TEXT PRIMARY KEY,
    employee_id TEXT NOT NULL,
    agent_name TEXT,
    doc_type TEXT,
    template_version TEXT,
    content TEXT,
    generated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
)
""")
conn_document.commit()

# -----------------------------
# Access Logs
# -----------------------------
cur_access.execute("DROP TABLE IF EXISTS access_logs")
cur_access.execute("""
CREATE TABLE access_logs (
    access_id TEXT PRIMARY KEY,
    employee_id TEXT NOT NULL,
    system_name TEXT NOT NULL,
    access_type TEXT,
    granted_by TEXT,
    granted_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    revoked_on TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
)
""")
conn_access.commit()

# -----------------------------
# ⭐ NEW: Assets Table
# -----------------------------
cur_asset.execute("DROP TABLE IF EXISTS assets")
cur_asset.execute("""
CREATE TABLE assets (
    asset_id TEXT PRIMARY KEY,
    asset_name TEXT,
    asset_type TEXT,
    serial_number TEXT,
    status TEXT,
    assigned_to TEXT,
    assigned_on TEXT,
    reclaimed_on TEXT
);
""")
conn_asset.commit()

print("✅ All tables dropped (if existed) and recreated successfully !")

✅ All database connections initialized successfully!
✅ All tables dropped (if existed) and recreated successfully !

In [10]:
# =========================================
# Canonical Synthetic HR + Asset Data Setup
# =========================================
from faker import Faker
import random
import json
import sqlite3
import uuid
from datetime import datetime, timedelta
from pathlib import Path

fake = Faker()

# =========================================
# CONFIG
# =========================================
NUM_EMPLOYEES = 1000
NUM_SESSIONS = 1000
NUM_WORKFLOWS = 1000
NUM_DOCUMENTS = 1000
NUM_ACCESS = 1000
NUM_ASSETS = 200

EMPLOYEE_DB = Path("employees.db")
SESSION_DB = Path("session_memory.db")
WORKFLOW_DB = Path("workflows.db")
DOCUMENT_DB = Path("documents.db")
ACCESS_DB = Path("access_logs.db")
ASSET_DB = Path("assets.db")

# =========================================
# HELPERS
# =========================================
def connect_db(path: Path) -> sqlite3.Connection:
    path.parent.mkdir(parents=True, exist_ok=True) if path.parent != Path(".") else None
    conn = sqlite3.connect(str(path))
    conn.row_factory = sqlite3.Row
    return conn

def now_iso() -> str:
    return datetime.utcnow().isoformat()

def create_tables() -> None:
    with connect_db(EMPLOYEE_DB) as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS employees (
                employee_id TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                department TEXT NOT NULL,
                role TEXT NOT NULL,
                hire_date TEXT NOT NULL,
                email TEXT NOT NULL,
                status TEXT DEFAULT 'Active',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP
            );
            """
        )

    with connect_db(SESSION_DB) as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS agent_context (
                session_id TEXT PRIMARY KEY,
                agent_name TEXT NOT NULL,
                employee_id TEXT NOT NULL,
                context_json TEXT NOT NULL,
                last_updated TEXT DEFAULT CURRENT_TIMESTAMP
            );
            """
        )

    with connect_db(WORKFLOW_DB) as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS workflows (
                workflow_id TEXT PRIMARY KEY,
                workflow_type TEXT NOT NULL,
                employee_id TEXT NOT NULL,
                current_step TEXT,
                status TEXT NOT NULL,
                triggered_by TEXT,
                last_updated TEXT DEFAULT CURRENT_TIMESTAMP
            );
            """
        )

    with connect_db(DOCUMENT_DB) as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS documents (
                document_id TEXT PRIMARY KEY,
                employee_id TEXT NOT NULL,
                agent_name TEXT NOT NULL,
                doc_type TEXT NOT NULL,
                template_version TEXT NOT NULL,
                content TEXT NOT NULL,
                generated_on TEXT DEFAULT CURRENT_TIMESTAMP
            );
            """
        )

    with connect_db(ACCESS_DB) as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS access_logs (
                access_id TEXT PRIMARY KEY,
                employee_id TEXT NOT NULL,
                system_name TEXT NOT NULL,
                access_type TEXT NOT NULL,
                granted_by TEXT,
                granted_on TEXT NOT NULL,
                revoked_on TEXT
            );
            """
        )

    with connect_db(ASSET_DB) as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS assets (
                asset_id TEXT PRIMARY KEY,
                asset_name TEXT,
                asset_type TEXT,
                serial_number TEXT,
                assigned_to TEXT,
                assigned_on TEXT,
                reclaimed_on TEXT,
                status TEXT DEFAULT 'Available'
            );
            """
        )

def seed_reference_data() -> None:
    departments = ["Engineering", "HR", "IT", "Finance", "Marketing", "Operations", "Legal"]
    department_roles = {
        "Engineering": ["Software Engineer", "DevOps Engineer"],
        "HR": ["HR Manager", "Recruiter"],
        "IT": ["IT Support", "System Admin"],
        "Finance": ["Accountant", "Financial Analyst"],
        "Marketing": ["Marketing Analyst", "Content Strategist"],
        "Operations": ["Operations Executive", "Supply Chain Analyst"],
        "Legal": ["Legal Advisor", "Compliance Officer"],
    }
    agent_names = [
        "Onboarding Agent", "Offboarding Agent", "Knowledge Retrieval Agent",
        "Document Generation Agent", "Access Management Agent", "Compliance Monitoring Agent"
    ]

    employees_data = []
    for i in range(1, NUM_EMPLOYEES + 1):
        emp_id = f"E{i:04d}"
        name = fake.name()
        department = random.choice(departments)
        role = random.choice(department_roles[department])
        hire_date = fake.date_between(start_date='-5y', end_date='today').isoformat()
        email = name.lower().replace(" ", ".") + "@example.com"
        employees_data.append((emp_id, name, department, role, hire_date, email, "Active", now_iso(), now_iso()))

    with connect_db(EMPLOYEE_DB) as conn:
        conn.executemany(
            """
            INSERT OR IGNORE INTO employees
                (employee_id, name, department, role, hire_date, email, status, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            employees_data,
        )

    session_rows = []
    for _ in range(NUM_SESSIONS):
        session_rows.append(
            (
                str(uuid.uuid4()),
                random.choice(agent_names),
                f"E{random.randint(1, NUM_EMPLOYEES):04d}",
                json.dumps({"last_action": fake.sentence(), "notes": fake.text(max_nb_chars=100)}),
                now_iso(),
            )
        )

    with connect_db(SESSION_DB) as conn:
        conn.executemany(
            """
            INSERT OR IGNORE INTO agent_context
                (session_id, agent_name, employee_id, context_json, last_updated)
            VALUES (?, ?, ?, ?, ?)
            """,
            session_rows,
        )

    workflow_types = ["Onboarding", "Offboarding", "Role Change", "Leave Approval", "Performance Review"]
    workflow_statuses = ["Pending", "In Progress", "Completed", "Escalated"]
    workflows_data = []
    for _ in range(NUM_WORKFLOWS):
        workflows_data.append(
            (
                str(uuid.uuid4()),
                random.choice(workflow_types),
                f"E{random.randint(1, NUM_EMPLOYEES):04d}",
                fake.word(),
                random.choice(workflow_statuses),
                fake.name(),
                now_iso(),
            )
        )

    with connect_db(WORKFLOW_DB) as conn:
        conn.executemany(
            """
            INSERT OR IGNORE INTO workflows
                (workflow_id, workflow_type, employee_id, current_step, status, triggered_by, last_updated)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            workflows_data,
        )

    doc_types = ["Offer Letter", "NDA", "Experience Letter", "Contract", "Policy Document"]
    documents_data = []
    for _ in range(NUM_DOCUMENTS):
        documents_data.append(
            (
                str(uuid.uuid4()),
                f"E{random.randint(1, NUM_EMPLOYEES):04d}",
                random.choice(agent_names),
                random.choice(doc_types),
                f"v{random.randint(1, 3)}",
                fake.text(max_nb_chars=200),
                now_iso(),
            )
        )

    with connect_db(DOCUMENT_DB) as conn:
        conn.executemany(
            """
            INSERT OR IGNORE INTO documents
                (document_id, employee_id, agent_name, doc_type, template_version, content, generated_on)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            documents_data,
        )

    systems = ["Google Workspace", "Slack", "HRIS System", "Finance System", "IT Ticketing"]
    access_types = ["Read", "Write", "Admin"]
    access_data = []
    for _ in range(NUM_ACCESS):
        granted_on = datetime.utcnow() - timedelta(days=random.randint(0, 180))
        revoked_on = granted_on + timedelta(days=random.randint(1, 180)) if random.random() < 0.3 else None
        access_data.append(
            (
                str(uuid.uuid4()),
                f"E{random.randint(1, NUM_EMPLOYEES):04d}",
                random.choice(systems),
                random.choice(access_types),
                fake.name(),
                granted_on.isoformat(),
                revoked_on.isoformat() if revoked_on else None,
            )
        )

    with connect_db(ACCESS_DB) as conn:
        conn.executemany(
            """
            INSERT OR IGNORE INTO access_logs
                (access_id, employee_id, system_name, access_type, granted_by, granted_on, revoked_on)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            access_data,
        )

    asset_types = ["Laptop", "Monitor", "Phone", "Access Card", "Headset", "Tablet"]
    asset_rows = []
    for _ in range(NUM_ASSETS):
        assigned_to = f"E{random.randint(1, NUM_EMPLOYEES):04d}" if random.random() < 0.7 else None
        assigned_on = (datetime.utcnow() - timedelta(days=random.randint(0, 365))).isoformat() if assigned_to else None
        asset_rows.append(
            (
                str(uuid.uuid4()),
                f"{fake.word().title()} Asset",
                random.choice(asset_types),
                f"S-{fake.bothify(text='??#####')}",
                assigned_to,
                assigned_on,
                None,
                "Assigned" if assigned_to else "Available",
            )
        )

    with connect_db(ASSET_DB) as conn:
        conn.executemany(
            """
            INSERT OR IGNORE INTO assets
                (asset_id, asset_name, asset_type, serial_number, assigned_to, assigned_on, reclaimed_on, status)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            asset_rows,
        )

create_tables()
seed_reference_data()

print("✅ Canonical tables created and seeded successfully")

/tmp/ipykernel_1272/504063118.py:41: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().isoformat()

✅ Canonical tables created and seeded successfully

/tmp/ipykernel_1272/504063118.py:248: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  granted_on = datetime.utcnow() - timedelta(days=random.randint(0, 180))
/tmp/ipykernel_1272/504063118.py:276: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  assigned_on = (datetime.utcnow() - timedelta(days=random.randint(0, 365))).isoformat() if assigned_to else None

In [11]:
# ----------------------------------------
# Quick sanity check queries for all tables
# ----------------------------------------

def preview_table(db_path, name, limit=5):
    """Fetch and display the first 'limit' records from a given table."""
    print(f"\n🔍 Preview of table: {name}")
    try:
        with connect_db(db_path) as conn:
            df = pd.read_sql_query(f"SELECT * FROM {name} LIMIT {limit};", conn)
            display(df)
    except Exception as e:
        print(f"Error reading {name}: {e}")

print("\n==============================")
print("📌 DATABASE VALIDATION PREVIEWS")
print("==============================")

preview_table(EMPLOYEE_DB, "employees")
preview_table(SESSION_DB, "agent_context")
preview_table(WORKFLOW_DB, "workflows")
preview_table(DOCUMENT_DB, "documents")
preview_table(ACCESS_DB, "access_logs")
preview_table(ASSET_DB, "assets")

print("\n✅ All previews completed.")

==============================
📌 DATABASE VALIDATION PREVIEWS
==============================

🔍 Preview of table: employees

,employee_id,name,department,role,hire_date,email,status,created_at,updated_at
0,E0001,Kiara Larsen,Finance,Accountant,2026-03-12,kiara.larsen@example.com,Active,2026-06-19T01:53:54.587626,2026-06-19T01:53:54.587637
1,E0002,Jessica Price,Operations,Supply Chain Analyst,2024-12-31,jessica.price@example.com,Active,2026-06-19T01:53:54.587886,2026-06-19T01:53:54.587889
2,E0003,Joshua Scott,Finance,Accountant,2026-01-24,joshua.scott@example.com,Active,2026-06-19T01:53:54.588085,2026-06-19T01:53:54.588089
3,E0004,Edward Washington,Marketing,Marketing Analyst,2022-02-13,edward.washington@example.com,Active,2026-06-19T01:53:54.588318,2026-06-19T01:53:54.588321
4,E0005,Thomas Buck,IT,System Admin,2024-03-16,thomas.buck@example.com,Active,2026-06-19T01:53:54.588482,2026-06-19T01:53:54.588485

🔍 Preview of table: agent_context

,session_id,agent_name,employee_id,context_json,last_updated
0,4b5a7c5e-37e7-4fc6-b38e-91b63624da2f,Access Management Agent,E0667,"{""last_action"": ""Anyone end green whether citi...",2026-06-19T01:53:54.771276
1,61950f1c-c916-49f9-bc41-7d748fdbb27a,Knowledge Retrieval Agent,E0468,"{""last_action"": ""Choice hot material report pr...",2026-06-19T01:53:54.771400
2,e1be26f0-96be-4827-81fe-e1b4a969ad71,Compliance Monitoring Agent,E0122,"{""last_action"": ""Event media writer strategy a...",2026-06-19T01:53:54.771500
3,38b3c3e3-fb43-4475-8a5d-f3b8fb2a373b,Compliance Monitoring Agent,E0226,"{""last_action"": ""Some necessary determine can ...",2026-06-19T01:53:54.771650
4,7f34db98-806c-4477-9a8f-59f173638158,Onboarding Agent,E0436,"{""last_action"": ""Food bed least land show exam...",2026-06-19T01:53:54.771774

🔍 Preview of table: workflows

,workflow_id,workflow_type,employee_id,current_step,status,triggered_by,created_at,last_updated
0,5857e204-6e19-499e-9f2e-7aa48b15b02c,Offboarding,E0046,realize,Pending,Brendan Moore,2026-06-19 01:53:55,2026-06-19T01:53:54.949504
1,65fefa0e-744e-44e2-90ae-bb5e3370f713,Offboarding,E0639,under,Pending,Brian Matthews,2026-06-19 01:53:55,2026-06-19T01:53:54.949677
2,b5cf3588-e4af-471c-81f6-59c75639cf9e,Offboarding,E0689,newspaper,Completed,Haley Williams,2026-06-19 01:53:55,2026-06-19T01:53:54.949836
3,a0160c11-7bc7-414c-8c63-9899348338d3,Onboarding,E0439,summer,Completed,Caleb Maldonado,2026-06-19 01:53:55,2026-06-19T01:53:54.949978
4,48edcfa5-96ac-4b73-8642-13e0a1895219,Performance Review,E0205,board,Completed,Kevin Mathis,2026-06-19 01:53:55,2026-06-19T01:53:54.950121

🔍 Preview of table: documents

,document_id,employee_id,agent_name,doc_type,template_version,content,generated_on
0,5e85911a-183c-467d-8359-1f714862ec84,E0413,Onboarding Agent,Experience Letter,v3,Lose painting television they two degree. War ...,2026-06-19T01:53:55.110055
1,657897d0-d24b-4851-9a93-b5ef22fd716a,E0072,Document Generation Agent,Offer Letter,v3,His painting and yeah identify hotel stay. But...,2026-06-19T01:53:55.110275
2,3609fd83-5c90-4612-9011-b562bad49b0f,E0194,Document Generation Agent,Experience Letter,v1,Politics according food cup common industry. L...,2026-06-19T01:53:55.110397
3,44ef7a63-f113-439a-9abb-604ca2953588,E0817,Access Management Agent,Offer Letter,v3,Maybe add sort have inside another parent. Mov...,2026-06-19T01:53:55.110521
4,4ceb1f4c-9ed4-40c9-b4a6-65e08947bdb3,E0689,Compliance Monitoring Agent,Offer Letter,v1,Human education television trade little. Keep ...,2026-06-19T01:53:55.110630

🔍 Preview of table: access_logs

,access_id,employee_id,system_name,access_type,granted_by,granted_on,revoked_on
0,86d5e442-2aa0-4246-9083-c86fb5479eb9,E0136,Slack,Admin,Sarah Pham,2026-02-16T01:53:55.234513,None
1,6e20b982-87b6-45b3-92ec-5b9e047d7b46,E0159,Finance System,Read,Wendy Morris,2026-03-02T01:53:55.234793,2026-04-29T01:53:55.234793
2,00516397-48c6-4275-a825-7c663f263cd5,E0193,Finance System,Admin,Sandra Brown,2026-04-17T01:53:55.235023,2026-07-18T01:53:55.235023
3,6e98c5d7-3eac-4b01-9ef3-642dd951a676,E0026,Finance System,Admin,Jeffrey Moore,2026-04-02T01:53:55.235285,None
4,c3cb62fc-01f8-4b24-bf5a-6edb2652d298,E0619,Finance System,Read,David Fisher,2025-12-29T01:53:55.235495,None

🔍 Preview of table: assets

,asset_id,asset_name,asset_type,serial_number,status,assigned_to,assigned_on,reclaimed_on
0,1b914ec0-8bf8-4dab-9fba-d5ad30b6c126,Parent Asset,Headset,S-kL53287,Available,None,None,None
1,9d9e2c99-f862-4b2d-8783-f3adee09c6b6,Then Asset,Laptop,S-RX93795,Available,None,None,None
2,b6257bf8-30bc-4bcb-9dc7-635f31aba5c0,Commercial Asset,Monitor,S-KD52886,Assigned,E0875,2025-08-31T01:53:55.389451,None
3,a4771bca-dd14-49f4-8f3b-bc1afea970d3,These Asset,Headset,S-lJ66515,Assigned,E0096,2025-11-16T01:53:55.389514,None
4,10b516be-e181-4ea2-9c78-f44f18465ba2,Whose Asset,Monitor,S-sj66343,Assigned,E0347,2026-06-09T01:53:55.389559,None

✅ All previews completed.

In [12]:
 #Clean up the doc

import chromadb

chroma_client = chromadb.Client()

# Delete entire collection to clean slate
try:
     chroma_client.delete_collection("hr_documents")
     print("🧹 Deleted existing hr_documents collection.")
except Exception as e:
    print("Already deleted or not found:", e)

Already deleted or not found: Collection [hr_documents] does not exist

In [13]:
# ======================================================
# BLOCK 1 — Generate Realistic HR Documents & Populate DB
# ======================================================

import random
import pandas as pd
from datetime import datetime, timedelta
import uuid

# Reuse canonical DB path and helper from earlier cells
# EMPLOYEE_DB = Path("employees.db")
# DOCUMENT_DB = Path("documents.db")
# def connect_db(path): ...

# ---------------------------------------
# 1. Synthetic HR variable pools
# ---------------------------------------
with connect_db(EMPLOYEE_DB) as conn_employee:
    df_emp = pd.read_sql_query(
        "SELECT employee_id, name, department, role FROM employees",
        conn_employee
    )

employee_pool = df_emp.to_dict(orient="records")
employee_ids = [e["employee_id"] for e in employee_pool]

department_roles = {
    "Engineering": ["Software Engineer", "DevOps Engineer"],
    "HR": ["HR Manager", "Recruiter"],
    "IT": ["IT Support", "System Admin"],
    "Finance": ["Accountant", "Financial Analyst"],
    "Marketing": ["Marketing Analyst", "Content Strategist"],
    "Operations": ["Operations Executive", "Supply Chain Analyst"],
    "Legal": ["Legal Advisor", "Compliance Officer"]
}

agent_names = [
    "Onboarding Agent", "Offboarding Agent", "Knowledge Retrieval Agent",
    "Document Generation Agent", "Access Management Agent", "Compliance Monitoring Agent"
]

doc_types = ["Offer Letter", "NDA", "Contract", "Experience Letter"]

salary_ranges = {
    "Senior Developer": (1200000, 2400000),
    "Software Engineer": (800000, 1800000),
    "DevOps Engineer": (900000, 1700000),
    "HR Manager": (1000000, 1800000),
    "Recruiter": (500000, 900000),
    "IT Support": (400000, 800000),
    "System Admin": (700000, 1300000),
    "Accountant": (600000, 1200000),
    "Financial Analyst": (700000, 1400000),
    "Marketing Analyst": (500000, 1000000),
    "Content Strategist": (600000, 1200000),
    "Operations Executive": (400000, 900000),
    "Supply Chain Analyst": (700000, 1400000),
    "Legal Advisor": (1000000, 2000000),
    "Compliance Officer": (900000, 1800000),
}
# ---------------------------------------
# 2. HR Document Templates
# ---------------------------------------
def generate_offer_letter(name, role, salary, start_date, dept):
    return f"""
Offer Letter – ACME Corporation

Dear {name},

We are pleased to offer you the position of **{role}** in the **{dept} Department** at ACME Corporation.
Your total annual compensation will be **₹{salary:,}**, payable according to the company's standard payroll cycle.

Your tentative joining date is **{start_date.strftime('%d %B %Y')}**.
You will be on a probation period of 6 months, after which your performance will be reviewed.

We welcome you to ACME Corporation and look forward to your contribution.

Sincerely,
ACME HR Team
"""

def generate_nda(name, dept):
    return f"""
Non-Disclosure Agreement (NDA)

This Non-Disclosure Agreement is entered into between ACME Corporation and **{name}**
of the **{dept} Department** for the purpose of protecting confidential and proprietary information.

The employee agrees not to disclose any confidential data including business strategies,
client information, internal documents, and financial reports during or after employment.

This agreement remains in effect for 3 years post-employment.

ACME Legal Team
"""

def generate_contract(name, role, salary, dept):
    return f"""
Employment Contract

This Employment Agreement is made between ACME Corporation ("Employer")
and **{name}** ("Employee") for the role of **{role}** in the **{dept} Department**.

1. Compensation: The employee will be paid an annual CTC of **₹{salary:,}**.
2. Work Hours: 40 hours per week, Monday to Friday.
3. Notice Period: 60 days.
4. Confidentiality: Employee agrees to maintain confidentiality of all company data.

By signing this contract, the employee agrees to abide by the policies of ACME Corporation.

ACME HR & Legal Team
"""

def generate_experience_letter(name, role, dept, years):
    return f"""
Experience Letter

To whom it may concern,

This is to certify that **{name}** worked as a **{role}** in the **{dept} Department**
at ACME Corporation for a period of **{years} years**.

During this time, the employee demonstrated strong professional skills, teamwork,
and adherence to organizational values.

We wish them continued success in their future endeavors.

Sincerely,
ACME HR Team
"""

templates = {
    "Offer Letter": generate_offer_letter,
    "NDA": generate_nda,
    "Contract": generate_contract,
    "Experience Letter": generate_experience_letter,
}

# ---------------------------------------
# 3. Generate documents and insert into SQLite
# ---------------------------------------
records = []

for _ in range(1000):
    emp = random.choice(employee_pool)
    name = emp["name"]
    dept = emp["department"]
    role = emp["role"]
    salary = random.randint(*salary_ranges[role])
    start_date = datetime.today() + timedelta(days=random.randint(10, 60))
    years_exp = random.randint(1, 5)
    doc_type = random.choice(doc_types)

    if doc_type == "Offer Letter":
        content = generate_offer_letter(name, role, salary, start_date, dept)
    elif doc_type == "NDA":
        content = generate_nda(name, dept)
    elif doc_type == "Contract":
        content = generate_contract(name, role, salary, dept)
    else:
        content = generate_experience_letter(name, role, dept, years_exp)

    records.append((
        str(uuid.uuid4()),
        emp["employee_id"],
        random.choice(agent_names),
        doc_type,
        f"v{random.randint(1,3)}",
        content,
        datetime.now()
    ))

with connect_db(DOCUMENT_DB) as conn_document:
    conn_document.execute("DELETE FROM documents;")
    conn_document.executemany(
        """
        INSERT INTO documents (
            document_id, employee_id, agent_name, doc_type,
            template_version, content, generated_on
        ) VALUES (?, ?, ?, ?, ?, ?, ?);
        """,
        records
    )

print("✅ Populated SQLite with fully realistic, schema-consistent HR documents.")

✅ Populated SQLite with fully realistic, schema-consistent HR documents.

/tmp/ipykernel_1272/150504193.py:175: DeprecationWarning: The default datetime adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  conn_document.executemany(

In [14]:
# ------------------------------------------------------
# Resume generation helpers
# Add this after offer letter / NDA / contract templates
# ------------------------------------------------------

resume_title_pool = {
    "Engineering": [
        "Python, SQL, Git, APIs, Docker, AWS, Kubernetes",
        "Data structures, algorithms, REST APIs, PostgreSQL, CI/CD",
        "Machine learning, pandas, scikit-learn, feature engineering"
    ],
    "HR": [
        "Talent acquisition, interview coordination, onboarding, HRIS",
        "Employee relations, policy drafting, performance management",
        "Recruiting, stakeholder management, ATS, sourcing"
    ],
    "IT": [
        "Windows/Linux support, networking, Active Directory, VPN",
        "Helpdesk, endpoint management, ticketing systems, scripting",
        "System administration, patching, monitoring, access control"
    ],
    "Finance": [
        "Budgeting, forecasting, Excel, financial reporting",
        "Accounts payable, reconciliations, audits, ERP systems",
        "Variance analysis, compliance, MIS reporting"
    ],
    "Marketing": [
        "Campaign planning, analytics, SEO, content strategy",
        "Brand management, social media, performance marketing",
        "Copywriting, CRM, email campaigns, lead generation"
    ],
    "Operations": [
        "Process improvement, vendor management, logistics",
        "Supply chain planning, SOPs, reporting, coordination",
        "Workflow optimization, inventory, operations analytics"
    ],
    "Legal": [
        "Contract review, compliance, policy interpretation",
        "Risk management, research, documentation, governance",
        "Regulatory support, legal drafting, confidentiality"
    ],
}

education_pool = [
    "B.Tech in Computer Science from Delhi Technological University",
    "MBA in HR from Symbiosis Institute of Business Management",
    "B.Com from University of Mumbai",
    "BBA from Christ University",
    "MCA from Anna University",
    "LLB from National Law University",
    "B.Sc. in Information Technology from Pune University",
]

def generate_resume(name, role, dept, years_exp):
    skills = random.choice(resume_title_pool.get(dept, ["Communication, teamwork, documentation"]))
    education = random.choice(education_pool)

    projects = [
        f"Worked on {dept.lower()} process improvements and cross-functional coordination.",
        f"Delivered measurable improvements in {role.lower()} execution and reporting.",
        f"Supported operational workflows, stakeholder communication, and documentation.",
    ]
    project_lines = "\n".join(f"- {p}" for p in random.sample(projects, k=2))

    return f"""
Resume

Name: {name}
Target Role: {role}
Department: {dept}
Years of Experience: {years_exp}

Summary:
Experienced professional with a background in {dept.lower()} operations and strong execution skills.
Known for ownership, communication, and process improvement.

Core Skills:
{skills}

Education:
{education}

Selected Experience:
{project_lines}

Keywords:
resume, {dept.lower()}, {role.lower()}, operations, communication, stakeholder management
"""

def generate_sample_resumes(n=25):
    rows = []
    for _ in range(n):
        emp = random.choice(employee_pool)
        name = emp["name"]
        dept = emp["department"]
        role = emp["role"]
        years_exp = random.randint(1, 10)
        content = generate_resume(name, role, dept, years_exp)

        rows.append((
            str(uuid.uuid4()),            # document_id
            emp["employee_id"],           # employee_id
            "Resume Reviewer Agent",       # agent_name
            "Resume",                      # doc_type
            "v1",                          # template_version
            content,                       # content
            datetime.now()                 # generated_on
        ))
    return rows

In [15]:
# ------------------------------------------------------
# Insert sample resumes into documents table
# ------------------------------------------------------
resume_records = generate_sample_resumes(n=30)

cursor = conn_document.cursor()
cursor.executemany(
    """
    INSERT INTO documents (
        document_id, employee_id, agent_name, doc_type,
        template_version, content, generated_on
    ) VALUES (?, ?, ?, ?, ?, ?, ?);
    """,
    resume_records
)
conn_document.commit()

print("✅ Inserted sample resumes into the documents table.")

✅ Inserted sample resumes into the documents table.

/tmp/ipykernel_1272/2747672505.py:7: DeprecationWarning: The default datetime adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  cursor.executemany(

In [16]:
import chromadb
from sentence_transformers import SentenceTransformer
import pandas as pd

# -----------------------------
# 1. Initialize Chroma client
# -----------------------------
chroma_client = chromadb.Client()

# -----------------------------
# 2. Recreate fresh collection
# -----------------------------
# Delete old collection if it exists
try:
    chroma_client.delete_collection("hr_documents")
except:
    pass

collection = chroma_client.create_collection("hr_documents")

# -----------------------------
# 3. Load freshly generated SQLite docs
# -----------------------------
df_documents = pd.read_sql("SELECT document_id, content, doc_type FROM documents", conn_document)

# -----------------------------
# 4. Embedding model
# -----------------------------
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = embedding_model.encode(df_documents["content"].tolist(), show_progress_bar=True)

# -----------------------------
# 5. Insert into ChromaDB
# -----------------------------
collection.add(
    ids=df_documents["document_id"].tolist(),
    documents=df_documents["content"].tolist(),
    metadatas=df_documents[["doc_type"]].to_dict(orient="records"),
    embeddings=embeddings.tolist()
)

print("✅ ChromaDB repopulated with fresh synthetic HR documents")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/33 [00:00<?, ?it/s]

✅ ChromaDB repopulated with fresh synthetic HR documents

In [17]:
import chromadb

# ---------------------------------------
# 1. Connect to Chroma & open collection
# ---------------------------------------
chroma_client = chromadb.Client()
collection = chroma_client.get_collection("hr_documents")

# ---------------------------------------
# 2. Count documents stored
# ---------------------------------------
count = collection.count()
print(f"📦 Total documents in ChromaDB: {count}")

# ---------------------------------------
# 3. Retrieve first 3 documents
# ---------------------------------------
docs = collection.get(
    ids=None,
    limit=3,
    include=["embeddings", "documents", "metadatas"]
)

print("\n📄 Sample Documents (First 3):\n")

for i in range(len(docs["ids"])):
    print(f"--- Document {i+1} ---")
    print(f"ID: {docs['ids'][i]}")
    print(f"Metadata: {docs['metadatas'][i]}")
    content = docs['documents'][i]
    print(f"Content snippet:\n{content[:300]}...")
    print()

# ---------------------------------------
# 4. Simple similarity search
# ---------------------------------------
query = "salary compensation offer letter software engineer"
results = collection.query(
    query_texts=[query],
    n_results=3,
    include=["documents", "metadatas", "distances"]
)

print("\n🔎 Similarity Search Results:\n")

for i in range(len(results["ids"][0])):
    print(f"Result {i+1}:")
    print(f"ID: {results['ids'][0][i]}")
    print(f"Score: {results['distances'][0][i]}")
    print(f"Metadata: {results['metadatas'][0][i]}")
    snippet = results['documents'][0][i]
    print(f"Content snippet:\n{snippet[:300]}...\n")

print("✅ ChromaDB inspection complete.")

📦 Total documents in ChromaDB: 1030

📄 Sample Documents (First 3):

--- Document 1 ---
ID: bb5dac7e-5757-449b-b2ce-e1942d14ff02
Metadata: {'doc_type': 'NDA'}
Content snippet:

Non-Disclosure Agreement (NDA)

This Non-Disclosure Agreement is entered into between ACME Corporation and **Thomas Ramsey**
of the **Marketing Department** for the purpose of protecting confidential and proprietary information.

The employee agrees not to disclose any confidential data including b...

--- Document 2 ---
ID: f42ab90f-7ebb-4306-b812-b262bfd49148
Metadata: {'doc_type': 'Offer Letter'}
Content snippet:

Offer Letter – ACME Corporation

Dear Brandon Blake,

We are pleased to offer you the position of **System Admin** in the **IT Department** at ACME Corporation.
Your total annual compensation will be **₹1,033,866**, payable according to the company's standard payroll cycle.

Your tentative joining ...

--- Document 3 ---
ID: 16264611-6578-4c64-968d-0c46677be430
Metadata: {'doc_type': 'Contract'}
Content snippet:

Employment Contract

This Employment Agreement is made between ACME Corporation ("Employer")
and **Rachel Price** ("Employee") for the role of **Recruiter** in the **HR Department**.

1. Compensation: The employee will be paid an annual CTC of **₹594,974**.
2. Work Hours: 40 hours per week, Monday ...

/root/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx.tar.gz: 100%|██████████| 79.3M/79.3M [00:09<00:00, 8.60MiB/s]

🔎 Similarity Search Results:

Result 1:
ID: 14db77db-45bd-4d3c-baf5-d13a2b90a82b
Score: 0.8971852660179138
Metadata: {'doc_type': 'Offer Letter'}
Content snippet:

Offer Letter – ACME Corporation

Dear Matthew Allison,

We are pleased to offer you the position of **Software Engineer** in the **Engineering Department** at ACME Corporation.
Your total annual compensation will be **₹1,260,713**, payable according to the company's standard payroll cycle.

Your te...

Result 2:
ID: 82db1779-8ffc-4009-9379-29da877269f3
Score: 0.9047088623046875
Metadata: {'doc_type': 'Offer Letter'}
Content snippet:

Offer Letter – ACME Corporation

Dear Christopher Stark,

We are pleased to offer you the position of **Software Engineer** in the **Engineering Department** at ACME Corporation.
Your total annual compensation will be **₹1,609,215**, payable according to the company's standard payroll cycle.

Your ...

Result 3:
ID: 69290ebe-69c9-4deb-b551-906281a45c1c
Score: 0.9065195322036743
Metadata: {'doc_type': 'Offer Letter'}
Content snippet:

Offer Letter – ACME Corporation

Dear Jason Townsend,

We are pleased to offer you the position of **Software Engineer** in the **Engineering Department** at ACME Corporation.
Your total annual compensation will be **₹1,296,699**, payable according to the company's standard payroll cycle.

Your ten...

✅ ChromaDB inspection complete.

In [18]:
import sqlite3
import random
import uuid
from faker import Faker
from datetime import datetime, timedelta

fake = Faker()

NUM_EMPLOYEES = 1000
NUM_WORKFLOWS = 1000
NUM_DOCUMENTS = 1000

# ==========================================================
# CONNECT TO EXISTING DATABASES
# ==========================================================

conn_employee = sqlite3.connect("employees.db")
conn_workflow = sqlite3.connect("workflows.db")
conn_document = sqlite3.connect("documents.db")

cur_employee = conn_employee.cursor()
cur_workflow = conn_workflow.cursor()
cur_document = conn_document.cursor()

# ==========================================================
# EMPLOYEE DATA
# ==========================================================

departments = {
    "Engineering": [
        "Software Engineer",
        "Senior Software Engineer",
        "DevOps Engineer",
        "Engineering Manager"
    ],
    "HR": [
        "Recruiter",
        "HR Executive",
        "HR Manager"
    ],
    "IT": [
        "IT Support Engineer",
        "System Administrator",
        "Cloud Administrator"
    ],
    "Finance": [
        "Accountant",
        "Financial Analyst",
        "Finance Manager"
    ],
    "Marketing": [
        "Marketing Analyst",
        "Content Strategist",
        "SEO Specialist"
    ],
    "Operations": [
        "Operations Executive",
        "Operations Manager",
        "Supply Chain Analyst"
    ],
    "Legal": [
        "Legal Advisor",
        "Compliance Officer",
        "Corporate Counsel"
    ]
}

employees_data = []

for i in range(1, NUM_EMPLOYEES + 1):

    employee_id = f"E{i:04d}"

    name = fake.name()
    department = random.choice(list(departments.keys()))
    role = random.choice(departments[department])

    hire_date = fake.date_between(
        start_date="-5y",
        end_date="today"
    )

    email = (
        name.lower()
        .replace(" ", ".")
        .replace("'", "")
        + "@example.com"
    )

    status = random.choice(
        ["Active"] * 9 +
        ["On Leave"] +
        ["Inactive"]
    )

    employees_data.append(
        (
            employee_id,
            name,
            department,
            role,
            hire_date,
            email,
            status
        )
    )

cur_employee.executemany("""
INSERT OR REPLACE INTO employees (
    employee_id,
    name,
    department,
    role,
    hire_date,
    email,
    status
)
VALUES (?, ?, ?, ?, ?, ?, ?)
""", employees_data)

conn_employee.commit()

print(f"✅ Inserted {NUM_EMPLOYEES} employees")

employee_lookup = {
    emp[0]: {
        "name": emp[1],
        "department": emp[2],
        "role": emp[3],
        "hire_date": emp[4],
        "email": emp[5],
        "status": emp[6]
    }
    for emp in employees_data
}

# ==========================================================
# WORKFLOW DATA
# ==========================================================

workflow_steps = {
    "Onboarding": [
        "Document Collection",
        "Background Verification",
        "Manager Approval",
        "IT Provisioning"
    ],
    "Offboarding": [
        "Resignation Submitted",
        "Manager Approval",
        "Knowledge Transfer",
        "Asset Return"
    ],
    "Role Change": [
        "Request Submitted",
        "Manager Approval",
        "HR Approval",
        "System Update"
    ],
    "Leave Approval": [
        "Request Submitted",
        "Manager Review",
        "HR Validation"
    ],
    "Performance Review": [
        "Self Assessment",
        "Manager Review",
        "Calibration",
        "Final Rating"
    ]
}

workflow_types = list(workflow_steps.keys())

workflows_data = []

for _ in range(NUM_WORKFLOWS):

    workflow_id = str(uuid.uuid4())

    workflow_type = random.choice(workflow_types)

    employee_id = random.choice(
        list(employee_lookup.keys())
    )

    current_step = random.choice(
        workflow_steps[workflow_type]
    )

    status = random.choice(
        ["Pending", "In Progress", "Completed", "Escalated"]
    )

    triggered_by = random.choice(
        [emp[1] for emp in employees_data]
    )

    created_at = (
        datetime.now()
        - timedelta(days=random.randint(0, 90))
    )

    last_updated = (
        created_at +
        timedelta(days=random.randint(0, 30))
    )

    workflows_data.append(
        (
            workflow_id,
            workflow_type,
            employee_id,
            current_step,
            status,
            triggered_by,
            created_at,
            last_updated
        )
    )

cur_workflow.executemany("""
INSERT OR REPLACE INTO workflows (
    workflow_id,
    workflow_type,
    employee_id,
    current_step,
    status,
    triggered_by,
    created_at,
    last_updated
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
""", workflows_data)

conn_workflow.commit()

print(f"✅ Inserted {NUM_WORKFLOWS} workflows")

# ==========================================================
# DOCUMENT DATA
# ==========================================================

agent_names = [
    "Onboarding Agent",
    "Offboarding Agent",
    "Knowledge Retrieval Agent",
    "Document Generation Agent",
    "Access Management Agent",
    "Compliance Monitoring Agent"
]

DOCUMENT_TEMPLATES = {
    "Offer Letter": """
OFFER LETTER

Dear {name},

We are pleased to offer you the position of {role}
in the {department} department.

Your employment start date is {hire_date}.

Regards,
Human Resources
""",

    "NDA": """
NON-DISCLOSURE AGREEMENT

Employee: {name}
Department: {department}

The employee agrees to maintain confidentiality of
company systems, customer information, and internal data.

Authorized By:
{agent_name}
""",

    "Experience Letter": """
EXPERIENCE LETTER

This is to certify that {name}
worked as a {role} in the
{department} department.

The employee demonstrated professionalism,
ownership, and commitment to business goals.

Regards,
{agent_name}
""",

    "Contract": """
EMPLOYMENT CONTRACT

Employee: {name}
Role: {role}
Department: {department}

The employee agrees to perform all responsibilities
associated with the designated role and follow
company policies and procedures.

Approved By:
{agent_name}
""",

    "Policy Document": """
REMOTE WORK POLICY

Version: {template_version}

Employees must:

1. Follow security requirements.
2. Protect confidential information.
3. Attend mandatory meetings.
4. Maintain productivity standards.
5. Follow compliance guidelines.

Issued By:
{agent_name}
"""
}

documents_data = []

for _ in range(NUM_DOCUMENTS):

    document_id = str(uuid.uuid4())

    employee_id = random.choice(
        list(employee_lookup.keys())
    )

    employee = employee_lookup[employee_id]

    doc_type = random.choice(
        list(DOCUMENT_TEMPLATES.keys())
    )

    template_version = f"v{random.randint(1,3)}"

    agent_name = random.choice(agent_names)

    content = DOCUMENT_TEMPLATES[doc_type].format(
        name=employee["name"],
        role=employee["role"],
        department=employee["department"],
        hire_date=employee["hire_date"],
        template_version=template_version,
        agent_name=agent_name
    ).strip()

    generated_on = (
        datetime.now()
        - timedelta(days=random.randint(0, 90))
    )

    documents_data.append(
        (
            document_id,
            employee_id,
            agent_name,
            doc_type,
            template_version,
            content,
            generated_on
        )
    )

cur_document.executemany("""
INSERT OR REPLACE INTO documents (
    document_id,
    employee_id,
    agent_name,
    doc_type,
    template_version,
    content,
    generated_on
)
VALUES (?, ?, ?, ?, ?, ?, ?)
""", documents_data)

conn_document.commit()

print(f"✅ Inserted {NUM_DOCUMENTS} documents")

# ==========================================================
# VALIDATION
# ==========================================================

employee_count = cur_employee.execute(
    "SELECT COUNT(*) FROM employees"
).fetchone()[0]

workflow_count = cur_workflow.execute(
    "SELECT COUNT(*) FROM workflows"
).fetchone()[0]

document_count = cur_document.execute(
    "SELECT COUNT(*) FROM documents"
).fetchone()[0]

print(f"Employees : {employee_count}")
print(f"Workflows : {workflow_count}")
print(f"Documents : {document_count}")

# ==========================================================
# CLEANUP
# ==========================================================

conn_employee.close()
conn_workflow.close()
conn_document.close()

print("✅ Synthetic HR data generated successfully")

✅ Inserted 1000 employees
✅ Inserted 1000 workflows
✅ Inserted 1000 documents
Employees : 1000
Workflows : 2000
Documents : 2030
✅ Synthetic HR data generated successfully

/tmp/ipykernel_1272/3622825036.py:108: DeprecationWarning: The default date adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  cur_employee.executemany("""
/tmp/ipykernel_1272/3622825036.py:222: DeprecationWarning: The default datetime adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  cur_workflow.executemany("""
/tmp/ipykernel_1272/3622825036.py:374: DeprecationWarning: The default datetime adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  cur_document.executemany("""

In [19]:
import os, signal

# Kill anything running on port 8000
!lsof -t -i:8000 | xargs -r kill -9

In [20]:
conn = sqlite3.connect("employees.db")
df = pd.read_sql("SELECT * FROM employees", conn)
conn.close()

df.head()

,employee_id,name,department,role,hire_date,email,status,created_at,updated_at
0,E0001,John Harris,Finance,Accountant,2024-05-29,john.harris@example.com,Active,2026-06-19 01:55:22,2026-06-19 01:55:22
1,E0002,Brian Bryant,IT,IT Support Engineer,2024-08-06,brian.bryant@example.com,On Leave,2026-06-19 01:55:22,2026-06-19 01:55:22
2,E0003,Christopher Higgins,Engineering,Senior Software Engineer,2021-11-15,christopher.higgins@example.com,On Leave,2026-06-19 01:55:22,2026-06-19 01:55:22
3,E0004,Heather Ruiz,HR,HR Executive,2024-12-22,heather.ruiz@example.com,Active,2026-06-19 01:55:22,2026-06-19 01:55:22
4,E0005,Pamela Bailey,Legal,Compliance Officer,2024-05-23,pamela.bailey@example.com,Active,2026-06-19 01:55:22,2026-06-19 01:55:22

In [21]:
import threading
import sqlite3
import pandas as pd
from flask import Flask, request, jsonify

# -----------------------------
# Flask app
# -----------------------------
app = Flask(__name__)


# -----------------------------
# Safe SQLite connection factory
# (each request creates its own connection)
# -----------------------------
def get_conn(db_path):
    return sqlite3.connect(db_path)


# -----------------------------
# Endpoints
# -----------------------------
@app.route("/employees", methods=["GET"])
def get_employees():
    conn = get_conn("employees.db")
    df = pd.read_sql("SELECT * FROM employees", conn)
    conn.close()
    return jsonify(df.to_dict(orient="records"))


@app.route("/workflow/current", methods=["GET"])
def get_workflow():
    employee_id = request.args.get("employee_id", "")
    conn = get_conn("workflows.db")

    df = pd.read_sql(
        "SELECT * FROM workflows WHERE employee_id = ?",
        conn,
        params=[employee_id]
    )
    conn.close()
    return jsonify(df.to_dict(orient="records"))


@app.route("/documents/search", methods=["GET"])
def search_documents():
    query_text = request.args.get("query_text", "")
    conn = get_conn("documents.db")

    df = pd.read_sql(
        "SELECT * FROM documents WHERE content LIKE ?",
        conn,
        params=[f"%{query_text}%"]
    )
    conn.close()
    return jsonify(df.to_dict(orient="records"))


# -----------------------------
# NEW: Assets Table Endpoints
# -----------------------------
@app.route("/assets", methods=["GET"])
def get_assets():
    """
    Returns all assets from assets.db
    Optional filters:
        ?employee_id=E0123
        ?asset_type=Laptop
    """
    employee_id = request.args.get("employee_id", None)
    asset_type = request.args.get("asset_type", None)

    conn = get_conn("assets.db")

    query = "SELECT * FROM assets WHERE 1=1"
    params = []

    if employee_id:
        query += " AND assigned_to = ?"
        params.append(employee_id)

    if asset_type:
        query += " AND asset_type = ?"
        params.append(asset_type)

    df = pd.read_sql(query, conn, params=params)
    conn.close()
    return jsonify(df.to_dict(orient="records"))


# -----------------------------
# Start Flask only once
# -----------------------------
def run_api():
    app.run(host="127.0.0.1", port=9000, debug=False, use_reloader=False)


if "api_thread" not in globals():
    api_thread = threading.Thread(target=run_api, daemon=True)
    api_thread.start()
    print("🚀 Flask API running at http://127.0.0.1:9000")
else:
    print("⚠️ Flask API already running — no restart.")

🚀 Flask API running at http://127.0.0.1:9000
 * Serving Flask app '__main__'
 * Debug mode: off

In [22]:
import requests
response = requests.get("http://127.0.0.1:9000/employees")
data = response.json()
print(data[:3])  # print first 3 records

INFO:werkzeug:127.0.0.1 - - [19/Jun/2026 01:55:57] "GET /employees HTTP/1.1" 200 -

[{'created_at': '2026-06-19 01:55:22', 'department': 'Finance', 'email': 'john.harris@example.com', 'employee_id': 'E0001', 'hire_date': '2024-05-29', 'name': 'John Harris', 'role': 'Accountant', 'status': 'Active', 'updated_at': '2026-06-19 01:55:22'}, {'created_at': '2026-06-19 01:55:22', 'department': 'IT', 'email': 'brian.bryant@example.com', 'employee_id': 'E0002', 'hire_date': '2024-08-06', 'name': 'Brian Bryant', 'role': 'IT Support Engineer', 'status': 'On Leave', 'updated_at': '2026-06-19 01:55:22'}, {'created_at': '2026-06-19 01:55:22', 'department': 'Engineering', 'email': 'christopher.higgins@example.com', 'employee_id': 'E0003', 'hire_date': '2021-11-15', 'name': 'Christopher Higgins', 'role': 'Senior Software Engineer', 'status': 'On Leave', 'updated_at': '2026-06-19 01:55:22'}]

In [23]:
columns = [
    "employee_id",
    "department",
    "role",
    "tenure_months",
    "performance_rating",
    "last_promotion_months",
    "training_completed",
    "job_satisfaction",  # scale 1-5
    "salary_increase_pct",
    "retention_risk"     # 0 = low risk, 1 = high risk
]

In [24]:
# =========================================
# Synthetic Employee Data Generation & ML Pipeline
# (Consistent employee IDs with employees.db)
# =========================================

from faker import Faker
import pandas as pd
import random
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
import sqlite3

# -----------------------------
# Step 0: Load employee IDs and departments from employees.db
# -----------------------------
conn = sqlite3.connect("employees.db")
employees_df = pd.read_sql("SELECT employee_id, department FROM employees", conn)
conn.close()

fake = Faker()
NUM_EMPLOYEES = len(employees_df)

# -----------------------------
# Step 1: Generate Synthetic ML Data
# -----------------------------
data = []

for idx, row in employees_df.iterrows():
    emp_id = row['employee_id']
    dept = row['department']

    age = random.randint(22, 60)
    tenure = round(random.uniform(0.5, min(age-21, 35)), 1)  # tenure cannot exceed age-21

    # Salary depends on department and tenure
    base_salary_dict = {
        "HR": 40000,
        "Engineering": 60000,
        "Sales": 45000,
        "Finance": 50000,
        "Marketing": 42000,
        "IT": 48000,
        "Operations": 43000,
        "Legal": 47000
    }
    base_salary = base_salary_dict.get(dept, 45000)
    salary = base_salary + int(tenure * random.randint(1000, 2000))

    # Retention risk: probabilistic based on tenure and salary
    if tenure < 2 or salary < 50000:
        prob = 0.7
    else:
        prob = 0.2
    retention_risk = 1 if random.random() < prob else 0

    data.append({
        "employee_id": emp_id,
        "age": age,
        "department": dept,
        "tenure_years": tenure,
        "salary": salary,
        "retention_risk": retention_risk
    })

df = pd.DataFrame(data)

print("Sample synthetic ML data:")
print(df.head())

# -----------------------------
# Step 2: Prepare Data for ML
# -----------------------------
le_dept = LabelEncoder()
df['department_enc'] = le_dept.fit_transform(df['department'])

X = df[['age', 'tenure_years', 'salary', 'department_enc']]
y = df['retention_risk']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# -----------------------------
# Step 3: Random Forest with GridSearchCV
# -----------------------------
rf = RandomForestClassifier(random_state=42)

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2']
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=cv,
    scoring='f1',
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

print("\nBest hyperparameters:", grid_search.best_params_)

# -----------------------------
# Step 4: Evaluate on Test Set
# -----------------------------
y_pred = grid_search.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("\nMetrics on test set:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1 Score:  {f1:.4f}")

print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Sample synthetic ML data:
  employee_id  age   department  tenure_years  salary  retention_risk
0       E0001   26      Finance           2.9   55428               0
1       E0002   40           IT           8.9   60629               0
2       E0003   32  Engineering           7.9   70649               1
3       E0004   37           HR          14.7   63137               0
4       E0005   39        Legal          12.1   62379               0
Fitting 5 folds for each of 324 candidates, totalling 1620 fits

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
540 fits failed out of a total of 1620.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
355 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
185 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.54147046 0.53972888 0.5497058
 0.55066509 0.56305488 0.56004797 0.5697835  0.58251156 0.58251156
 0.56809068 0.56819736 0.56652243 0.56815079 0.5657079  0.56596611
 0.59580021 0.59017262 0.58489228 0.59020724 0.59341494 0.59030767
 0.59020724 0.59341494 0.59030767 0.59841155 0.59955823 0.59466933
 0.54147046 0.53972888 0.5497058  0.55066509 0.56305488 0.56004797
 0.5697835  0.58251156 0.58251156 0.56809068 0.56819736 0.56652243
 0.56815079 0.5657079  0.56596611 0.59580021 0.59017262 0.58489228
 0.59020724 0.59341494 0.59030767 0.59020724 0.59341494 0.59030767
 0.59841155 0.59955823 0.59466933        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.58924319 0.58767086 0.5897024  0.5915713  0.58363101 0.58513386
 0.58398865 0.58420649 0.58221938 0.59139097 0.58656141 0.58795274
 0.59392249 0.58630602 0.59100246 0.59209211 0.59035088 0.59343426
 0.59748623 0.59556704 0.59574581 0.59748623 0.59556704 0.59574581
 0.59419985 0.5974043  0.60206435 0.58924319 0.58767086 0.5897024
 0.5915713  0.58363101 0.58513386 0.58398865 0.58420649 0.58221938
 0.59139097 0.58656141 0.58795274 0.59392249 0.58630602 0.59100246
 0.59209211 0.59035088 0.59343426 0.59748623 0.59556704 0.59574581
 0.59748623 0.59556704 0.59574581 0.59419985 0.5974043  0.60206435
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.54654731 0.57405032 0.5603677
 0.5692438  0.58189725 0.57058349 0.57854527 0.58660734 0.58805662
 0.56792857 0.57387937 0.57526937 0.57952647 0.58045929 0.57522261
 0.59968466 0.582205   0.59099024 0.59739297 0.59634535 0.59564703
 0.59739297 0.59634535 0.59564703 0.59786534 0.59833795 0.59592353
 0.54654731 0.57405032 0.5603677  0.5692438  0.58189725 0.57058349
 0.57854527 0.58660734 0.58805662 0.56792857 0.57387937 0.57526937
 0.57952647 0.58045929 0.57522261 0.59968466 0.582205   0.59099024
 0.59739297 0.59634535 0.59564703 0.59739297 0.59634535 0.59564703
 0.59786534 0.59833795 0.59592353        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.54208755 0.53907643 0.54521595 0.55066509 0.56305488 0.56004797
 0.56845562 0.58251156 0.58251156 0.56809068 0.56819736 0.56652243
 0.56815079 0.5657079  0.56596611 0.59580021 0.59017262 0.58489228
 0.59020724 0.59341494 0.59030767 0.59020724 0.59341494 0.59030767
 0.59841155 0.59955823 0.59466933 0.54208755 0.53907643 0.54521595
 0.55066509 0.56305488 0.56004797 0.56845562 0.58251156 0.58251156
 0.56809068 0.56819736 0.56652243 0.56815079 0.5657079  0.56596611
 0.59580021 0.59017262 0.58489228 0.59020724 0.59341494 0.59030767
 0.59020724 0.59341494 0.59030767 0.59841155 0.59955823 0.59466933]
  warnings.warn(

Best hyperparameters: {'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'min_samples_split': 10, 'n_estimators': 200}

Metrics on test set:
Accuracy:  0.7750
Precision: 0.7174
Recall:    0.5077
F1 Score:  0.5946

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.90      0.84       135
           1       0.72      0.51      0.59        65

    accuracy                           0.78       200
   macro avg       0.75      0.71      0.72       200
weighted avg       0.77      0.78      0.76       200

Confusion Matrix:
 [[122  13]
 [ 32  33]]

In [25]:
# Save generated synthetic dataset for later use
df.to_csv("employees.csv", index=False)
print("Saved employees.csv")

Saved employees.csv

In [26]:
import joblib

# Save ML model
joblib.dump(grid_search.best_estimator_, "retention_model.pkl")
print("Saved retention_model.pkl")

Saved retention_model.pkl

In [27]:
import sqlite3

# Connect to SQLite database
conn_retention = sqlite3.connect("retention.db")

# Save DataFrame to SQLite
df.to_sql(
    "retention_data",
    conn_retention,
    if_exists="replace",  # or "append"
    index=False
)

conn_retention.close()
print("Data pushed to SQLite successfully.")

Data pushed to SQLite successfully.

In [28]:
import sqlite3
import pandas as pd

# Connect (read-only mode optional)
conn = sqlite3.connect("retention.db")

# List all tables (just to confirm)
tables = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)
print("Tables in DB:")
print(tables)

# Read the table you created
df_check = pd.read_sql("SELECT * FROM retention_data LIMIT 10;", conn)

conn.close()

print("\nSample rows from retention_data:")
print(df_check)

Tables in DB:
             name
0  retention_data

Sample rows from retention_data:
  employee_id  age   department  tenure_years  salary  retention_risk  \
0       E0001   26      Finance           2.9   55428               0
1       E0002   40           IT           8.9   60629               0
2       E0003   32  Engineering           7.9   70649               1
3       E0004   37           HR          14.7   63137               0
4       E0005   39        Legal          12.1   62379               0
5       E0006   28           HR           2.5   42507               1
6       E0007   43           IT           7.6   57044               1
7       E0008   47      Finance           9.3   63689               0
8       E0009   27           IT           3.9   53744               0
9       E0010   44      Finance           6.9   62137               0

   department_enc
0               1
1               3
2               0
3               2
4               4
5               2
6               3
7               1
8               3
9               1

In [29]:
from flask import Flask, request, jsonify
import joblib
import pandas as pd
import threading

model = joblib.load("retention_model.pkl")
df = pd.read_csv("employees.csv")

dept_mapping = {dept: i for i, dept in enumerate(df['department'].unique())}

app = Flask(__name__)

@app.route("/predict", methods=["POST"])
def predict_retention():
    data = request.get_json()
    age = data["age"]
    tenure_years = data["tenure_years"]
    salary = data["salary"]
    department = data["department"]

    dept_enc = dept_mapping.get(department, 0)

    X_input = pd.DataFrame([{
        "age": age,
        "tenure_years": tenure_years,
        "salary": salary,
        "department_enc": dept_enc
    }])

    pred = model.predict(X_input)[0]
    prob = model.predict_proba(X_input)[0][pred]

    return jsonify({
        "retention_risk": int(pred),
        "probability": float(prob)
    })

# --------------------------
# Run Flask in background
# --------------------------
def run_flask():
    app.run(host="127.0.0.1", port=5000, debug=False, use_reloader=False)

thread = threading.Thread(target=run_flask)
thread.start()

print("Flask server started on http://127.0.0.1:5000")

Flask server started on http://127.0.0.1:5000 * Serving Flask app '__main__'

 * Debug mode: off

INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000

In [30]:
import requests

url = "http://127.0.0.1:5000/predict"

payload = {
    "age": 28,
    "tenure_years": 1.2,
    "salary": 47000,
    "department": "Sales"
}

response = requests.post(url, json=payload)

print("Status Code:", response.status_code)
print("Response JSON:", response.json())

INFO:werkzeug:127.0.0.1 - - [19/Jun/2026 02:01:33] "POST /predict HTTP/1.1" 200 -

Status Code: 200
Response JSON: {'probability': 0.7033260046277031, 'retention_risk': 1}

In [31]:
from google.adk.agents import LlmAgent
from google.adk.models.google_llm import Gemini
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools.mcp_tool.mcp_toolset import McpToolset
from google.adk.tools.tool_context import ToolContext
from google.adk.tools.mcp_tool.mcp_session_manager import StdioConnectionParams
from mcp import StdioServerParameters

from google.adk.apps.app import App, ResumabilityConfig
from google.adk.tools.function_tool import FunctionTool
from google.adk.tools.mcp_tool import McpToolset, StreamableHTTPConnectionParams

print("✅ ADK components imported successfully.")

✅ ADK components imported successfully.

/usr/local/lib/python3.12/dist-packages/google/adk/features/_feature_decorator.py:72: UserWarning: [EXPERIMENTAL] feature FeatureName.PLUGGABLE_AUTH is enabled.
  check_feature_enabled()

In [32]:
import os
# Access it
# Gemini API Key (Get from Google AI Studio: https://aistudio.google.com/app/apikey)
os.environ["GOOGLE_API_KEY"] = 'AIzaSyAmr8Zo7FURIkHTJqlyV9JltZjdzy8_mAM'

In [33]:
from google.adk.tools.mcp_tool.mcp_toolset import (
    McpToolset,
    StreamableHTTPConnectionParams,
)

mcp_toolset = McpToolset(
    connection_params=StreamableHTTPConnectionParams(
        url="http://127.0.0.1:9001/mcp",
        timeout=300,
    )
)

In [34]:
# =========================================
# HR Automation MCP Server (Curated Tools)
# =========================================

from fastmcp import FastMCP
from pydantic import BaseModel
import requests
import threading
from typing import Optional, List

# -----------------------------
# External ML API
# -----------------------------
ML_API = "http://127.0.0.1:5000"

# -----------------------------
# MCP server
# -----------------------------
mcp = FastMCP("mcp_toolset")

# ======================================================
# ML-backed tools
# ======================================================

class RetentionInput(BaseModel):
    age: int
    tenure_years: float
    salary: int
    department: str

@mcp.tool()
def predict_retention(payload: RetentionInput):
    """
    Predict employee retention risk using ML service.
    """
    resp = requests.post(f"{ML_API}/predict", json=payload.dict())
    resp.raise_for_status()
    return resp.json()

# ======================================================
# Employee tools
# ======================================================

@mcp.tool()
def get_employee_profile(employee_id: str):
    """Fetch an employee profile."""
    return get_employee(employee_id)

@mcp.tool()
def search_employees(
    name: Optional[str] = None,
    department: Optional[str] = None,
    role: Optional[str] = None,
    limit: int = 10,
):
    """Search employees by name, department, or role."""
    return search_employee(
        name=name,
        department=department,
        role=role,
        limit=limit,
    )

@mcp.tool()
def deactivate_employee(employee_id: str):
    """
    Mark an employee as inactive.
    """
    return update_employee_status(employee_id, "Inactive")

# ======================================================
# Workflow tools
# ======================================================

@mcp.tool()
def start_workflow(
    workflow_type: str,
    employee_id: str,
    triggered_by: Optional[str] = None,
):
    """Create a new workflow for an employee."""
    return create_workflow(
        workflow_type=workflow_type,
        employee_id=employee_id,
        triggered_by=triggered_by,
    )

@mcp.tool()
def advance_employee_workflow(
    workflow_id: str,
    next_step: str,
):
    """Advance a workflow to its next step."""
    return advance_workflow(workflow_id, next_step)

# ======================================================
# Asset tools
# ======================================================

@mcp.tool()
def assign_employee_asset(asset_id: str, employee_id: str):
    """Assign an asset to an employee."""
    return assign_asset(asset_id, employee_id)

@mcp.tool()
def reclaim_employee_asset(asset_id: str):
    """Reclaim an assigned asset."""
    return reclaim_asset(asset_id)

# ======================================================
# Document tools
# ======================================================

@mcp.tool()
def generate_employee_document(
    employee_id: str,
    agent_name: str,
    doc_type: str,
    template_version: str,
    content: str,
):
    """Generate and store an HR document."""
    return create_document(
        employee_id=employee_id,
        agent_name=agent_name,
        doc_type=doc_type,
        template_version=template_version,
        content=content,
    )

@mcp.tool()
def get_employee_document(document_id: str):
    """Fetch a document by ID."""
    return get_document(document_id)

@mcp.tool()
def search_hr_documents(query: str, limit: int = 20):
    """Search HR documents."""
    return search_documents(query, limit)

# ======================================================
# Access control tools
# ======================================================

@mcp.tool()
def grant_employee_access(
    employee_id: str,
    system_name: str,
    granted_by: Optional[str] = None,
):
    """Grant system access to an employee."""
    return grant_access(employee_id, system_name, granted_by)

@mcp.tool()
def revoke_employee_access(employee_id: str, system_name: str):
    """Revoke system access from an employee."""
    return revoke_access(employee_id, system_name)

@mcp.tool()
def check_employee_access(
    employee_id: str,
    system_name: Optional[str] = None,
):
    """Check employee access permissions."""
    return check_access_permissions(employee_id, system_name)

# ======================================================
# Start MCP server (background thread, Colab-safe)
# ======================================================

def start_mcp():
    mcp.run(
        transport="http",
        host="127.0.0.1",
        port=9001,
    )

if "mcp_thread" not in globals():
    mcp_thread = threading.Thread(target=start_mcp, daemon=True)
    mcp_thread.start()
    print("🚀 MCP server running at http://127.0.0.1:9001")
else:
    print("⚠️ MCP server already running — no restart.")

🚀 MCP server running at http://127.0.0.1:9001

In [35]:
import sqlite3
import uuid
import datetime
import json
import pandas as pd

from typing import Dict, Any, Optional, List
from pydantic import BaseModel
# ---------------------------------------------------------------------
# SQL-backed function tools (ready to use with your test harness)
# Uses the exact DB filenames you confirmed:
#   employees.db, workflows.db, documents.db, access_logs.db, session.db
# ---------------------------------------------------------------------

import sqlite3
import uuid
from datetime import datetime
import json
from typing import Dict, Any, Optional, List

# ---------- helpers ----------
def _now_iso() -> str:
    return datetime.utcnow().isoformat()

def _make_id(prefix: str = "ID") -> str:
    return f"{prefix}-{uuid.uuid4().hex[:8]}"

# ---------- open DB connections (reuse if already present) ----------
try:
    conn_employee
except NameError:
    conn_employee = sqlite3.connect("employees.db", check_same_thread=False)
    conn_employee.row_factory = sqlite3.Row

try:
    conn_workflow
except NameError:
    conn_workflow = sqlite3.connect("workflows.db", check_same_thread=False)
    conn_workflow.row_factory = sqlite3.Row

try:
    conn_document
except NameError:
    conn_document = sqlite3.connect("documents.db", check_same_thread=False)
    conn_document.row_factory = sqlite3.Row

try:
    conn_access
except NameError:
    conn_access = sqlite3.connect("access_logs.db", check_same_thread=False)
    conn_access.row_factory = sqlite3.Row

try:
    conn_session
except NameError:
    conn_session = sqlite3.connect("session_memory.db", check_same_thread=False)
    conn_session.row_factory = sqlite3.Row

# ---------- Chroma collection (if present) ----------
try:
    collection
    chroma_client
except NameError:
    try:
        import chromadb
        chroma_client = chromadb.Client()
        collection = chroma_client.get_collection("hr_documents")
    except Exception:
        collection = None

# -------------------------
# Employee functions (public names expected by tests)
# -------------------------
def get_employee(employee_id: str) -> Dict[str, Any]:
    """Return employee row as dict."""
    cur = conn_employee.execute("SELECT * FROM employees WHERE employee_id = ?", (employee_id,))
    row = cur.fetchone()
    if not row:
        return {"status": "error", "error_message": "Employee not found"}
    return {"status": "success", "employee": dict(row)}

def search_employee(name: Optional[str] = None, department: Optional[str] = None, role: Optional[str] = None, limit: int = 10) -> Dict[str, Any]:
    """Search employees by name/department/role with simple LIKE queries."""
    clauses = []
    params = []
    if name:
        clauses.append("(name LIKE ?)")
        params.append(f"%{name}%")
    if department:
        clauses.append("(department LIKE ?)")
        params.append(f"%{department}%")
    if role:
        clauses.append("(role LIKE ?)")
        params.append(f"%{role}%")
    where = " OR ".join(clauses) if clauses else "1"
    q = f"SELECT * FROM employees WHERE {where} LIMIT ?"
    params.append(limit)
    cur = conn_employee.execute(q, tuple(params))
    rows = [dict(r) for r in cur.fetchall()]
    return {"status": "success", "results": rows}

def update_employee_status(employee_id: str, status: str) -> Dict[str, Any]:
    """Update the status column for an employee (e.g., Active/Inactive)."""
    with conn_employee:
        conn_employee.execute("UPDATE employees SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE employee_id = ?", (status, employee_id))
    return get_employee(employee_id)

def update_employee(employee_id: str, updates: Dict[str, Any]) -> Dict[str, Any]:
    """Generic update for employee fields. 'updates' is a dict column->value."""
    if not updates:
        return {"status": "error", "error_message": "No updates provided"}
    keys = list(updates.keys())
    set_clause = ", ".join([f"{k} = ?" for k in keys])
    params = [updates[k] for k in keys] + [employee_id]
    with conn_employee:
        conn_employee.execute(f"UPDATE employees SET {set_clause}, updated_at = CURRENT_TIMESTAMP WHERE employee_id = ?", params)
    return get_employee(employee_id)

# -------------------------
# Workflow functions
# -------------------------
def create_workflow(workflow_type: str, employee_id: str, current_step: Optional[str] = None, triggered_by: Optional[str] = None) -> Dict[str, Any]:
    workflow_id = str(uuid.uuid4())
    now = _now_iso()
    with conn_workflow:
        conn_workflow.execute(
            "INSERT INTO workflows (workflow_id, workflow_type, employee_id, current_step, status, triggered_by, last_updated) VALUES (?, ?, ?, ?, ?, ?, ?)",
            (workflow_id, workflow_type, employee_id, current_step or "", "Pending", triggered_by, now)
        )
    return {"status": "success", "workflow_id": workflow_id}

def get_workflow_state(workflow_id: str) -> Dict[str, Any]:
    cur = conn_workflow.execute("SELECT * FROM workflows WHERE workflow_id = ?", (workflow_id,))
    r = cur.fetchone()
    if not r:
        return {"status": "error", "error_message": "Workflow not found"}
    return {"status": "success", "workflow": dict(r)}

def update_workflow_status(workflow_id: str, status: str) -> Dict[str, Any]:
    with conn_workflow:
        conn_workflow.execute("UPDATE workflows SET status = ?, last_updated = CURRENT_TIMESTAMP WHERE workflow_id = ?", (status, workflow_id))
    return get_workflow_state(workflow_id)

def advance_workflow(workflow_id: str, new_step: str) -> Dict[str, Any]:
    with conn_workflow:
        conn_workflow.execute("UPDATE workflows SET current_step = ?, last_updated = CURRENT_TIMESTAMP WHERE workflow_id = ?", (new_step, workflow_id))
    return get_workflow_state(workflow_id)

# -------------------------
# Asset Functions
# -------------------------

def assign_asset(asset_id: str, employee_id: str):
    """
    Assigns an asset to an employee.
    Updates:
    - status = 'Assigned'
    - assigned_to
    - assigned_on (UTC ISO timestamp)
    - reclaimed_on = NULL
    """
    conn = sqlite3.connect("assets.db")
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    # Check if asset exists
    cur.execute("SELECT * FROM assets WHERE asset_id = ?", (asset_id,))
    asset = cur.fetchone()

    if not asset:
        conn.close()
        return {"error": f"Asset {asset_id} does not exist"}

    # Check if already assigned
    if asset["assigned_to"] and asset["reclaimed_on"] is None:
        conn.close()
        return {"error": f"Asset {asset_id} is already assigned to {asset['assigned_to']}"}

    timestamp = datetime.utcnow().isoformat()

    cur.execute("""
        UPDATE assets
        SET status = 'Assigned',
            assigned_to = ?,
            assigned_on = ?,
            reclaimed_on = NULL
        WHERE asset_id = ?
    """, (employee_id, timestamp, asset_id))

    conn.commit()
    conn.close()

    return {
        "status": "success",
        "asset_id": asset_id,
        "assigned_to": employee_id,
        "assigned_on": timestamp
    }


def reclaim_asset(asset_id: str) -> Dict[str, Any]:
    conn = sqlite3.connect("assets.db")
    try:
        cursor = conn.cursor()
        cursor.execute(
            """
            UPDATE assets
            SET assigned_to = NULL,
                assigned_on = NULL,
                reclaimed_on = ?
            WHERE asset_id = ?
            """,
            (datetime.utcnow().isoformat(), asset_id),
        )
        conn.commit()
        return {"status": "success", "asset_id": asset_id}
    except Exception as e:
        conn.rollback()
        return {"status": "error", "error_message": str(e)}
    finally:
        conn.close()

# ======================================================
# Resume tools
# ======================================================

class ResumeReviewInput(BaseModel):
    resume_text: str
    target_role: str
    target_department: str
    minimum_years_experience: Optional[int] = 0

def score_resume_text(resume_text: str, target_role: str, target_department: str) -> dict:
    text = resume_text.lower()
    score = 0
    reasons = []

    role_keywords = {
        "Engineering": ["python", "sql", "api", "docker", "aws", "git", "kubernetes", "machine learning"],
        "HR": ["recruiting", "onboarding", "hris", "employee relations", "ats", "talent acquisition"],
        "IT": ["support", "active directory", "windows", "linux", "network", "ticketing", "helpdesk"],
        "Finance": ["budget", "forecast", "excel", "audit", "reporting", "reconciliation"],
        "Marketing": ["campaign", "seo", "content", "social media", "analytics", "branding"],
        "Operations": ["process", "supply chain", "vendor", "workflow", "logistics", "sop"],
        "Legal": ["contract", "compliance", "policy", "legal", "risk", "governance"],
    }

    keywords = role_keywords.get(target_department, [])
    matches = [kw for kw in keywords if kw in text]
    score += len(matches) * 15

    if target_role.lower() in text:
        score += 20
        reasons.append("Target role appears in the resume text.")

    if target_department.lower() in text:
        score += 15
        reasons.append("Target department appears in the resume text.")

    if "years of experience" in text or "experience" in text:
        score += 10
        reasons.append("Resume includes an experience section.")

    if "education" in text:
        score += 5
        reasons.append("Resume includes an education section.")

    if matches:
        reasons.append(f"Matched keywords: {', '.join(matches[:8])}")

    score = min(score, 100)
    return {
        "score": score,
        "reasons": reasons or ["No strong matches found."],
        "matched_keywords": matches,
    }

@mcp.tool()
def generate_sample_resumes_tool(n: int = 10):
    """
    Generate and store synthetic resumes in the documents table.
    """
    rows = generate_sample_resumes(n=n)
    cursor = conn_document.cursor()
    cursor.executemany(
        """
        INSERT INTO documents (
            document_id, employee_id, agent_name, doc_type,
            template_version, content, generated_on
        ) VALUES (?, ?, ?, ?, ?, ?, ?);
        """,
        rows
    )
    conn_document.commit()
    return {"inserted": len(rows), "doc_type": "Resume"}

@mcp.tool()
def review_resume(document_id: str, target_role: str, target_department: str):
    """
    Review a single resume and return a score + rationale.
    """
    row = pd.read_sql(
        """
        SELECT document_id, employee_id, agent_name, doc_type, content, generated_on
        FROM documents
        WHERE document_id = ?
        """,
        conn_document,
        params=(document_id,)
    )

    if row.empty:
        return {"error": "Resume not found", "document_id": document_id}

    content = row.iloc[0]["content"]
    result = score_resume_text(content, target_role, target_department)

    return {
        "document_id": document_id,
        "employee_id": row.iloc[0]["employee_id"],
        "agent_name": row.iloc[0]["agent_name"],
        "doc_type": row.iloc[0]["doc_type"],
        "review": result,
    }

@mcp.tool()
def shortlist_resumes(target_role: str, target_department: str, min_score: int = 50, limit: int = 10):
    """
    Search resume documents and return the best matches.
    """
    df = pd.read_sql(
        """
        SELECT document_id, employee_id, agent_name, doc_type, content, generated_on
        FROM documents
        WHERE doc_type = 'Resume'
        ORDER BY generated_on DESC
        """,
        conn_document
    )

    if df.empty:
        return {"shortlist": [], "message": "No resumes found."}

    ranked = []
    for _, row in df.iterrows():
        result = score_resume_text(row["content"], target_role, target_department)
        if result["score"] >= min_score:
            ranked.append({
                "document_id": row["document_id"],
                "employee_id": row["employee_id"],
                "agent_name": row["agent_name"],
                "score": result["score"],
                "reasons": result["reasons"],
            })

    ranked = sorted(ranked, key=lambda x: x["score"], reverse=True)[:limit]
    return {"shortlist": ranked, "count": len(ranked)}


# -------------------------
# Document functions (SQL + Chroma)
# -------------------------
def create_document(employee_id: str, agent_name: str, doc_type: str, template_version: str, content: str) -> Dict[str, Any]:
    document_id = str(uuid.uuid4())
    now = _now_iso()
    with conn_document:
        conn_document.execute(
            "INSERT OR REPLACE INTO documents (document_id, employee_id, agent_name, doc_type, template_version, content, generated_on) VALUES (?, ?, ?, ?, ?, ?, ?)",
            (document_id, employee_id, agent_name, doc_type, template_version, content, now)
        )
    # Add to Chroma if available
    try:
        if collection is not None:
            collection.add(
                ids=[document_id],
                documents=[content],
                metadatas=[{"doc_type": doc_type, "employee_id": employee_id, "agent_name": agent_name}],
                embeddings=None
            )
    except Exception:
        pass
    return {"status": "success", "document_id": document_id}

def get_document(document_id: str) -> Dict[str, Any]:
    cur = conn_document.execute("SELECT * FROM documents WHERE document_id = ?", (document_id,))
    r = cur.fetchone()
    if not r:
        return {"status": "error", "error_message": "Document not found"}
    return {"status": "success", "document": dict(r)}

def list_employee_documents(employee_id: str, limit: int = 20) -> Dict[str, Any]:
    cur = conn_document.execute("SELECT * FROM documents WHERE employee_id = ? ORDER BY generated_on DESC LIMIT ?", (employee_id, limit))
    rows = [dict(r) for r in cur.fetchall()]
    return {"status": "success", "documents": rows}

import sqlite3

def search_documents(query: str, limit: int = 20):
    """
    Simple SQLite full-text search across:
    - doc_type
    - template_version
    - content
    - agent_name

    Returns a list of dict rows.
    """
    conn = sqlite3.connect("documents.db")
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    pattern = f"%{query}%"

    cur.execute("""
        SELECT *
        FROM documents
        WHERE doc_type LIKE ?
           OR template_version LIKE ?
           OR content LIKE ?
           OR agent_name LIKE ?
        ORDER BY generated_on DESC
        LIMIT ?
    """, (pattern, pattern, pattern, pattern, limit))

    results = [dict(row) for row in cur.fetchall()]
    conn.close()

    return results

# -------------------------
# Access management (access_logs.db)
# -------------------------
def grant_access(employee_id: str, system_name: str, granted_by: Optional[str] = None) -> Dict[str, Any]:
    access_id = str(uuid.uuid4())
    now = _now_iso()
    with conn_access:
        conn_access.execute(
            "INSERT INTO access_logs (access_id, employee_id, system_name, access_type, granted_by, granted_on) VALUES (?, ?, ?, ?, ?, ?)",
            (access_id, employee_id, system_name, "granted", granted_by, now)
        )
    return {"status": "success", "access_id": access_id}

def revoke_access(employee_id: str, system_name: str) -> Dict[str, Any]:
    # find last granted, not revoked
    cur = conn_access.execute("SELECT * FROM access_logs WHERE employee_id = ? AND system_name = ? AND revoked_on IS NULL ORDER BY granted_on DESC LIMIT 1", (employee_id, system_name))
    row = cur.fetchone()
    if not row:
        return {"status": "error", "error_message": "Access not found or already revoked"}
    access_id = row["access_id"]
    with conn_access:
        conn_access.execute("UPDATE access_logs SET revoked_on = ? WHERE access_id = ?", (_now_iso(), access_id))
    return {"status": "success", "access_id": access_id}

def check_access_permissions(employee_id: str, system_name: Optional[str] = None) -> Dict[str, Any]:
    """
    Returns the access state(s) of an employee for a specific system,
    or all systems if none is specified.
    """
    cur = conn_access.execute(
        """
        SELECT * FROM access_logs
        WHERE employee_id = ?
          AND (system_name = ? OR ? IS NULL)
        ORDER BY granted_on DESC
        """,
        (employee_id, system_name, system_name)
    )

    rows = [dict(r) for r in cur.fetchall()]

    if not rows:
        return {
            "status": "success",
            "access": [],
            "message": "No access found"
        }

    return {
        "status": "success",
        "access": rows
    }

def list_access(employee_id: str) -> Dict[str, Any]:
    cur = conn_access.execute("SELECT * FROM access_logs WHERE employee_id = ? ORDER BY granted_on DESC", (employee_id,))
    rows = [dict(r) for r in cur.fetchall()]
    return {"status": "success", "access_logs": rows}

# =====================================================
# Session Memory / Agent Context Helpers
# =====================================================

SESSION_DB = "session_memory.db"

def get_session_connection():
    conn = sqlite3.connect(SESSION_DB)
    conn.row_factory = sqlite3.Row
    return conn


def save_agent_context_sql(
    agent_name: str,
    employee_id: str,
    context: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Save or update agent context for an employee.
    """

    session_id = f"{agent_name}::{employee_id}"
    now = _now_iso()

    try:
        conn = get_session_connection()

        with conn:
            conn.execute(
                """
                INSERT OR REPLACE INTO agent_context (
                    session_id,
                    agent_name,
                    employee_id,
                    context_json,
                    last_updated
                )
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    session_id,
                    agent_name,
                    employee_id,
                    json.dumps(context),
                    now,
                ),
            )

        conn.close()

        return {
            "status": "success",
            "session_id": session_id,
            "last_updated": now,
        }

    except Exception as exc:
        return {
            "status": "error",
            "error_message": str(exc),
            "session_id": session_id,
        }


def load_agent_context_sql(
    agent_name: str,
    employee_id: str
) -> Dict[str, Any]:
    """
    Load previously saved context.
    """

    session_id = f"{agent_name}::{employee_id}"

    try:
        conn = get_session_connection()

        cur = conn.execute(
            """
            SELECT context_json, last_updated
            FROM agent_context
            WHERE session_id = ?
            """,
            (session_id,),
        )

        row = cur.fetchone()
        conn.close()

        if not row:
            return {
                "status": "error",
                "error_message": "Context not found",
                "session_id": session_id,
            }

        return {
            "status": "success",
            "session_id": session_id,
            "context": json.loads(row["context_json"]),
            "last_updated": row["last_updated"],
        }

    except Exception as exc:
        return {
            "status": "error",
            "error_message": str(exc),
            "session_id": session_id,
        }


def clear_agent_context_sql(
    agent_name: str,
    employee_id: str
) -> Dict[str, Any]:
    """
    Delete stored context.
    """

    session_id = f"{agent_name}::{employee_id}"

    try:
        conn = get_session_connection()

        with conn:
            conn.execute(
                """
                DELETE FROM agent_context
                WHERE session_id = ?
                """,
                (session_id,),
            )

        conn.close()

        return {
            "status": "success",
            "session_id": session_id,
        }

    except Exception as exc:
        return {
            "status": "error",
            "error_message": str(exc),
            "session_id": session_id,
        }

@mcp.tool()
def save_agent_context(agent_name: str, employee_id: str, context: dict):
    return save_agent_context_sql(agent_name, employee_id, context)

@mcp.tool()
def load_agent_context(agent_name: str, employee_id: str):
    return load_agent_context_sql(agent_name, employee_id)

@mcp.tool()
def clear_agent_context(agent_name: str, employee_id: str):
    return clear_agent_context_sql(agent_name, employee_id)


# -------------------------
# Misc helpers for demo/test
# -------------------------
def demo_summary() -> Dict[str, Any]:
    cur_e = conn_employee.execute("SELECT COUNT(*) as c FROM employees")
    total_emps = cur_e.fetchone()["c"]
    cur_d = conn_document.execute("SELECT COUNT(*) as c FROM documents")
    total_docs = cur_d.fetchone()["c"]
    return {"status": "success", "total_employees": total_emps, "total_documents": total_docs}

print("✅ SQL-backed function tools loaded: get_employee, search_employee, update_employee_status, create_workflow, create_document, search_documents, grant_access, revoke_access, save_agent_context, load_agent_context.")

✅ SQL-backed function tools loaded: get_employee, search_employee, update_employee_status, create_workflow, create_document, search_documents, grant_access, revoke_access, save_agent_context, load_agent_context.

In [36]:
from pathlib import Path
from typing import Any, Dict, Optional
import json
import sqlite3
import uuid
from datetime import datetime

AGENT_MODEL = globals().get("AGENT_MODEL", "gemini-2.5-flash-lite")
SESSION_DB = Path("session_memory.db")
EVAL_DB = Path("agent_evaluation.db")

def _connect(path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(str(path))
    conn.row_factory = sqlite3.Row
    return conn

def init_session_and_eval_store() -> None:
    with _connect(SESSION_DB) as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS agent_context (
                session_id TEXT PRIMARY KEY,
                agent_name TEXT NOT NULL,
                employee_id TEXT NOT NULL,
                context_json TEXT NOT NULL,
                last_updated TEXT DEFAULT CURRENT_TIMESTAMP
            );
            """
        )
        conn.commit()

    with _connect(EVAL_DB) as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS workflow_eval_runs (
                eval_run_id TEXT PRIMARY KEY,
                workflow_id TEXT,
                scenario TEXT,
                employee_id TEXT,
                orchestrator_agent TEXT,
                started_at TEXT,
                finished_at TEXT,
                status TEXT,
                score INTEGER,
                summary_json TEXT
            );

            CREATE TABLE IF NOT EXISTS workflow_eval_events (
                event_id TEXT PRIMARY KEY,
                eval_run_id TEXT NOT NULL,
                ts TEXT NOT NULL,
                agent_name TEXT NOT NULL,
                phase TEXT NOT NULL,
                status TEXT NOT NULL,
                event_json TEXT
            );
            """
        )
        conn.commit()

def start_eval_run(
    workflow_id: str,
    scenario: str,
    employee_id: str,
    orchestrator_agent: str = "workflow_orchestrator_agent",
) -> Dict[str, Any]:
    eval_run_id = str(uuid.uuid4())
    started_at = datetime.utcnow().isoformat()

    with _connect(EVAL_DB) as conn:
        conn.execute(
            """
            INSERT INTO workflow_eval_runs
                (eval_run_id, workflow_id, scenario, employee_id, orchestrator_agent,
                 started_at, status, score, summary_json)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (eval_run_id, workflow_id, scenario, employee_id, orchestrator_agent, started_at, "running", None, None),
        )
        conn.commit()

    return {"status": "success", "eval_run_id": eval_run_id, "started_at": started_at}

def log_eval_event(
    eval_run_id: str,
    agent_name: str,
    phase: str,
    status: str,
    event: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    event_id = str(uuid.uuid4())
    ts = datetime.utcnow().isoformat()

    with _connect(EVAL_DB) as conn:
        conn.execute(
            """
            INSERT INTO workflow_eval_events
                (event_id, eval_run_id, ts, agent_name, phase, status, event_json)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (event_id, eval_run_id, ts, agent_name, phase, status, json.dumps(event or {}, default=str)),
        )
        conn.commit()

    return {"status": "success", "event_id": event_id, "ts": ts}

def finish_eval_run(eval_run_id: str, final_payload: Dict[str, Any]) -> Dict[str, Any]:
    score = 0
    if final_payload.get("workflow_status") == "Completed":
        score += 40
    if final_payload.get("memory_roundtrip_ok"):
        score += 20
    if final_payload.get("resume_review_used"):
        score += 15
    if final_payload.get("access_handled"):
        score += 15
    if final_payload.get("asset_handled"):
        score += 10

    summary = {
        "workflow_status": final_payload.get("workflow_status"),
        "memory_roundtrip_ok": final_payload.get("memory_roundtrip_ok"),
        "resume_review_used": final_payload.get("resume_review_used"),
        "access_handled": final_payload.get("access_handled"),
        "asset_handled": final_payload.get("asset_handled"),
        "notes": final_payload.get("notes", []),
    }

    with _connect(EVAL_DB) as conn:
        conn.execute(
            """
            UPDATE workflow_eval_runs
            SET finished_at = ?, status = ?, score = ?, summary_json = ?
            WHERE eval_run_id = ?
            """,
            (datetime.utcnow().isoformat(), "finished", score, json.dumps(summary, default=str), eval_run_id),
        )
        conn.commit()

    return {"status": "success", "eval_run_id": eval_run_id, "score": score, "summary": summary}

workflow_evaluator_agent = LlmAgent(
    name="workflow_evaluator_agent",
    model=Gemini(model=AGENT_MODEL),
    instruction="""
You evaluate HR workflow runs.

Score the run on:
- completion
- session memory roundtrip
- A2A handoff usage
- access handling
- asset handling

Return a concise rubric-based assessment.
""",
    tools=[mcp_toolset],
)

init_session_and_eval_store()
print("✅ Session store and evaluation store initialized")

✅ Session store and evaluation store initialized

In [37]:
import json
import sqlite3
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd
from fastmcp import FastMCP
from pydantic import BaseModel

mcp = FastMCP("mcp_toolset")
mcp_toolset = mcp

EMPLOYEE_DB = Path("employees.db")
WORKFLOW_DB = Path("workflows.db")
DOCUMENT_DB = Path("documents.db")
ACCESS_DB = Path("access_logs.db")
ASSET_DB = Path("assets.db")
SESSION_DB = Path("session_memory.db")

collection = globals().get("collection")  # optional Chroma collection from earlier cells

def _connect(path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(str(path))
    conn.row_factory = sqlite3.Row
    return conn

def _now_iso() -> str:
    return datetime.utcnow().isoformat()

def _make_id(prefix: str = "ID") -> str:
    return f"{prefix}-{uuid.uuid4().hex[:8]}"

# -------------------------
# Employee functions
# -------------------------
def get_employee(employee_id: str) -> Dict[str, Any]:
    with _connect(EMPLOYEE_DB) as conn:
        row = conn.execute("SELECT * FROM employees WHERE employee_id = ?", (employee_id,)).fetchone()
    if not row:
        return {"status": "error", "error_message": "Employee not found"}
    return {"status": "success", "employee": dict(row)}

def search_employee(
    name: Optional[str] = None,
    department: Optional[str] = None,
    role: Optional[str] = None,
    limit: int = 10,
) -> Dict[str, Any]:
    clauses = []
    params: List[Any] = []

    if name:
        clauses.append("name LIKE ?")
        params.append(f"%{name}%")
    if department:
        clauses.append("department LIKE ?")
        params.append(f"%{department}%")
    if role:
        clauses.append("role LIKE ?")
        params.append(f"%{role}%")

    where = " OR ".join(clauses) if clauses else "1"
    query = f"SELECT * FROM employees WHERE {where} LIMIT ?"
    params.append(limit)

    with _connect(EMPLOYEE_DB) as conn:
        rows = [dict(r) for r in conn.execute(query, params).fetchall()]
    return {"status": "success", "results": rows}

def update_employee_status(employee_id: str, status: str) -> Dict[str, Any]:
    with _connect(EMPLOYEE_DB) as conn:
        conn.execute(
            """
            UPDATE employees
            SET status = ?, updated_at = CURRENT_TIMESTAMP
            WHERE employee_id = ?
            """,
            (status, employee_id),
        )
        conn.commit()
    return get_employee(employee_id)

def update_employee(employee_id: str, updates: Dict[str, Any]) -> Dict[str, Any]:
    if not updates:
        return {"status": "error", "error_message": "No updates provided"}

    allowed = {"name", "department", "role", "hire_date", "email", "status"}
    bad_keys = [k for k in updates.keys() if k not in allowed]
    if bad_keys:
        return {"status": "error", "error_message": f"Unsupported employee field(s): {bad_keys}"}

    set_clause = ", ".join([f"{k} = ?" for k in updates.keys()])
    params = list(updates.values()) + [employee_id]

    with _connect(EMPLOYEE_DB) as conn:
        conn.execute(
            f"""
            UPDATE employees
            SET {set_clause}, updated_at = CURRENT_TIMESTAMP
            WHERE employee_id = ?
            """,
            params,
        )
        conn.commit()
    return get_employee(employee_id)

# -------------------------
# Workflow functions
# -------------------------
def create_workflow(
    workflow_type: str,
    employee_id: str,
    current_step: Optional[str] = None,
    triggered_by: Optional[str] = None,
) -> Dict[str, Any]:
    workflow_id = str(uuid.uuid4())
    now = _now_iso()
    with _connect(WORKFLOW_DB) as conn:
        conn.execute(
            """
            INSERT INTO workflows
                (workflow_id, workflow_type, employee_id, current_step, status, triggered_by, last_updated)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (workflow_id, workflow_type, employee_id, current_step or "", "Pending", triggered_by, now),
        )
        conn.commit()
    return {"status": "success", "workflow_id": workflow_id}

def get_workflow_state(workflow_id: str) -> Dict[str, Any]:
    with _connect(WORKFLOW_DB) as conn:
        row = conn.execute("SELECT * FROM workflows WHERE workflow_id = ?", (workflow_id,)).fetchone()
    if not row:
        return {"status": "error", "error_message": "Workflow not found"}
    return {"status": "success", "workflow": dict(row)}

def update_workflow_status(workflow_id: str, status: str) -> Dict[str, Any]:
    with _connect(WORKFLOW_DB) as conn:
        conn.execute(
            """
            UPDATE workflows
            SET status = ?, last_updated = CURRENT_TIMESTAMP
            WHERE workflow_id = ?
            """,
            (status, workflow_id),
        )
        conn.commit()
    return get_workflow_state(workflow_id)

def advance_workflow(workflow_id: str, new_step: str) -> Dict[str, Any]:
    with _connect(WORKFLOW_DB) as conn:
        conn.execute(
            """
            UPDATE workflows
            SET current_step = ?, last_updated = CURRENT_TIMESTAMP
            WHERE workflow_id = ?
            """,
            (new_step, workflow_id),
        )
        conn.commit()
    return get_workflow_state(workflow_id)

# -------------------------
# Asset functions
# -------------------------
def assign_asset(asset_id: str, employee_id: str) -> Dict[str, Any]:
    with _connect(ASSET_DB) as conn:
        row = conn.execute("SELECT * FROM assets WHERE asset_id = ?", (asset_id,)).fetchone()
        if not row:
            return {"status": "error", "error_message": f"Asset {asset_id} does not exist"}

        if row["assigned_to"] and row["reclaimed_on"] is None:
            return {"status": "error", "error_message": f"Asset {asset_id} is already assigned to {row['assigned_to']}"}

        timestamp = _now_iso()
        conn.execute(
            """
            UPDATE assets
            SET status = 'Assigned',
                assigned_to = ?,
                assigned_on = ?,
                reclaimed_on = NULL
            WHERE asset_id = ?
            """,
            (employee_id, timestamp, asset_id),
        )
        conn.commit()

    return {
        "status": "success",
        "asset_id": asset_id,
        "assigned_to": employee_id,
        "assigned_on": timestamp,
    }

def reclaim_asset(asset_id: str) -> Dict[str, Any]:
    with _connect(ASSET_DB) as conn:
        row = conn.execute("SELECT * FROM assets WHERE asset_id = ?", (asset_id,)).fetchone()
        if not row:
            return {"status": "error", "error_message": f"Asset {asset_id} does not exist"}

        timestamp = _now_iso()
        conn.execute(
            """
            UPDATE assets
            SET status = 'Available',
                assigned_to = NULL,
                assigned_on = NULL,
                reclaimed_on = ?
            WHERE asset_id = ?
            """,
            (timestamp, asset_id),
        )
        conn.commit()

    return {"status": "success", "asset_id": asset_id, "reclaimed_on": timestamp}

# -------------------------
# Resume tools
# -------------------------
class ResumeReviewInput(BaseModel):
    resume_text: str
    target_role: str
    target_department: str
    minimum_years_experience: Optional[int] = 0

def score_resume_text(resume_text: str, target_role: str, target_department: str) -> dict:
    text = resume_text.lower()
    score = 0
    reasons = []

    role_keywords = {
        "Engineering": ["python", "sql", "api", "docker", "aws", "git", "kubernetes", "machine learning"],
        "HR": ["recruiting", "onboarding", "hris", "employee relations", "ats", "talent acquisition"],
        "IT": ["support", "active directory", "windows", "linux", "network", "ticketing", "helpdesk"],
        "Finance": ["budget", "forecast", "excel", "audit", "reporting", "reconciliation"],
        "Marketing": ["campaign", "seo", "content", "social media", "analytics", "branding"],
        "Operations": ["process", "supply chain", "vendor", "workflow", "logistics", "sop"],
        "Legal": ["contract", "compliance", "policy", "legal", "risk", "governance"],
    }

    keywords = role_keywords.get(target_department, [])
    matches = [kw for kw in keywords if kw in text]
    score += len(matches) * 15

    if target_role.lower() in text:
        score += 20
        reasons.append("Target role appears in the resume text.")
    if target_department.lower() in text:
        score += 15
        reasons.append("Target department appears in the resume text.")
    if "years of experience" in text or "experience" in text:
        score += 10
        reasons.append("Resume includes an experience section.")
    if "education" in text:
        score += 5
        reasons.append("Resume includes an education section.")
    if matches:
        reasons.append(f"Matched keywords: {', '.join(matches[:8])}")

    return {"score": min(score, 100), "reasons": reasons or ["No strong matches found."], "matched_keywords": matches}

@mcp.tool()
def generate_sample_resumes_tool(n: int = 10):
    rows = generate_sample_resumes(n=n)
    with _connect(DOCUMENT_DB) as conn:
        conn.executemany(
            """
            INSERT INTO documents
                (document_id, employee_id, agent_name, doc_type, template_version, content, generated_on)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            rows,
        )
        conn.commit()
    return {"status": "success", "inserted": len(rows), "doc_type": "Resume"}

@mcp.tool()
def review_resume(document_id: str, target_role: str, target_department: str):
    with _connect(DOCUMENT_DB) as conn:
        row = pd.read_sql_query(
            """
            SELECT document_id, employee_id, agent_name, doc_type, content, generated_on
            FROM documents
            WHERE document_id = ?
            """,
            conn,
            params=(document_id,),
        )

    if row.empty:
        return {"status": "error", "error_message": "Resume not found", "document_id": document_id}

    content = row.iloc[0]["content"]
    result = score_resume_text(content, target_role, target_department)
    return {
        "status": "success",
        "document_id": document_id,
        "employee_id": row.iloc[0]["employee_id"],
        "agent_name": row.iloc[0]["agent_name"],
        "doc_type": row.iloc[0]["doc_type"],
        "review": result,
    }

@mcp.tool()
def shortlist_resumes(target_role: str, target_department: str, min_score: int = 50, limit: int = 10):
    with _connect(DOCUMENT_DB) as conn:
        df = pd.read_sql_query(
            """
            SELECT document_id, employee_id, agent_name, doc_type, content, generated_on
            FROM documents
            WHERE doc_type = 'Resume'
            ORDER BY generated_on DESC
            """,
            conn,
        )

    if df.empty:
        return {"shortlist": [], "message": "No resumes found."}

    ranked = []
    for _, row in df.iterrows():
        result = score_resume_text(row["content"], target_role, target_department)
        if result["score"] >= min_score:
            ranked.append(
                {
                    "document_id": row["document_id"],
                    "employee_id": row["employee_id"],
                    "agent_name": row["agent_name"],
                    "score": result["score"],
                    "reasons": result["reasons"],
                }
            )

    ranked = sorted(ranked, key=lambda x: x["score"], reverse=True)[:limit]
    return {"status": "success", "shortlist": ranked, "count": len(ranked)}

# -------------------------
# Document functions
# -------------------------
def create_document(employee_id: str, agent_name: str, doc_type: str, template_version: str, content: str) -> Dict[str, Any]:
    document_id = str(uuid.uuid4())
    now = _now_iso()

    with _connect(DOCUMENT_DB) as conn:
        conn.execute(
            """
            INSERT OR REPLACE INTO documents
                (document_id, employee_id, agent_name, doc_type, template_version, content, generated_on)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (document_id, employee_id, agent_name, doc_type, template_version, content, now),
        )
        conn.commit()

    try:
        if collection is not None:
            collection.add(
                ids=[document_id],
                documents=[content],
                metadatas=[{"doc_type": doc_type, "employee_id": employee_id, "agent_name": agent_name}],
            )
    except Exception:
        pass

    return {"status": "success", "document_id": document_id}

def get_document(document_id: str) -> Dict[str, Any]:
    with _connect(DOCUMENT_DB) as conn:
        row = conn.execute("SELECT * FROM documents WHERE document_id = ?", (document_id,)).fetchone()
    if not row:
        return {"status": "error", "error_message": "Document not found"}
    return {"status": "success", "document": dict(row)}

def list_employee_documents(employee_id: str, limit: int = 20) -> Dict[str, Any]:
    with _connect(DOCUMENT_DB) as conn:
        rows = conn.execute(
            """
            SELECT *
            FROM documents
            WHERE employee_id = ?
            ORDER BY generated_on DESC
            LIMIT ?
            """,
            (employee_id, limit),
        ).fetchall()
    return {"status": "success", "documents": [dict(r) for r in rows]}

def search_documents(query: str, limit: int = 20):
    pattern = f"%{query}%"
    with _connect(DOCUMENT_DB) as conn:
        rows = conn.execute(
            """
            SELECT *
            FROM documents
            WHERE doc_type LIKE ?
               OR template_version LIKE ?
               OR content LIKE ?
               OR agent_name LIKE ?
            ORDER BY generated_on DESC
            LIMIT ?
            """,
            (pattern, pattern, pattern, pattern, limit),
        ).fetchall()
    return [dict(r) for r in rows]

# -------------------------
# Access management
# -------------------------
def grant_access(employee_id: str, system_name: str, granted_by: Optional[str] = None) -> Dict[str, Any]:
    access_id = str(uuid.uuid4())
    now = _now_iso()
    with _connect(ACCESS_DB) as conn:
        conn.execute(
            """
            INSERT INTO access_logs
                (access_id, employee_id, system_name, access_type, granted_by, granted_on)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (access_id, employee_id, system_name, "granted", granted_by, now),
        )
        conn.commit()
    return {"status": "success", "access_id": access_id}

def revoke_access(employee_id: str, system_name: str) -> Dict[str, Any]:
    with _connect(ACCESS_DB) as conn:
        row = conn.execute(
            """
            SELECT *
            FROM access_logs
            WHERE employee_id = ?
              AND system_name = ?
              AND revoked_on IS NULL
            ORDER BY granted_on DESC
            LIMIT 1
            """,
            (employee_id, system_name),
        ).fetchone()

        if not row:
            return {"status": "error", "error_message": "Access not found or already revoked"}

        access_id = row["access_id"]
        conn.execute(
            "UPDATE access_logs SET revoked_on = ? WHERE access_id = ?",
            (_now_iso(), access_id),
        )
        conn.commit()

    return {"status": "success", "access_id": access_id}

def check_access_permissions(employee_id: str, system_name: Optional[str] = None) -> Dict[str, Any]:
    with _connect(ACCESS_DB) as conn:
        rows = conn.execute(
            """
            SELECT *
            FROM access_logs
            WHERE employee_id = ?
              AND (? IS NULL OR system_name = ?)
            ORDER BY granted_on DESC
            """,
            (employee_id, system_name, system_name),
        ).fetchall()

    if not rows:
        return {"status": "success", "access": [], "message": "No access found"}
    return {"status": "success", "access": [dict(r) for r in rows]}

def list_access(employee_id: str) -> Dict[str, Any]:
    with _connect(ACCESS_DB) as conn:
        rows = conn.execute(
            "SELECT * FROM access_logs WHERE employee_id = ? ORDER BY granted_on DESC",
            (employee_id,),
        ).fetchall()
    return {"status": "success", "access_logs": [dict(r) for r in rows]}

# -------------------------
# Session memory helpers
# -------------------------
def save_agent_context_sql(agent_name: str, employee_id: str, context: Dict[str, Any]) -> Dict[str, Any]:
    session_id = f"{agent_name}::{employee_id}"
    now = _now_iso()
    with _connect(SESSION_DB) as conn:
        conn.execute(
            """
            INSERT OR REPLACE INTO agent_context
                (session_id, agent_name, employee_id, context_json, last_updated)
            VALUES (?, ?, ?, ?, ?)
            """,
            (session_id, agent_name, employee_id, json.dumps(context, default=str), now),
        )
        conn.commit()
    return {"status": "success", "session_id": session_id, "last_updated": now}

def load_agent_context_sql(agent_name: str, employee_id: str) -> Dict[str, Any]:
    session_id = f"{agent_name}::{employee_id}"
    with _connect(SESSION_DB) as conn:
        row = conn.execute(
            "SELECT context_json, last_updated FROM agent_context WHERE session_id = ?",
            (session_id,),
        ).fetchone()

    if not row:
        return {"status": "error", "error_message": "Context not found", "session_id": session_id}

    return {
        "status": "success",
        "session_id": session_id,
        "context": json.loads(row["context_json"]),
        "last_updated": row["last_updated"],
    }

def clear_agent_context_sql(agent_name: str, employee_id: str) -> Dict[str, Any]:
    session_id = f"{agent_name}::{employee_id}"
    with _connect(SESSION_DB) as conn:
        conn.execute("DELETE FROM agent_context WHERE session_id = ?", (session_id,))
        conn.commit()
    return {"status": "success", "session_id": session_id}

@mcp.tool()
def save_agent_context(agent_name: str, employee_id: str, context: dict):
    return save_agent_context_sql(agent_name, employee_id, context)

@mcp.tool()
def load_agent_context(agent_name: str, employee_id: str):
    return load_agent_context_sql(agent_name, employee_id)

@mcp.tool()
def clear_agent_context(agent_name: str, employee_id: str):
    return clear_agent_context_sql(agent_name, employee_id)

def demo_summary() -> Dict[str, Any]:
    with _connect(EMPLOYEE_DB) as conn:
        total_emps = conn.execute("SELECT COUNT(*) AS c FROM employees").fetchone()["c"]
    with _connect(DOCUMENT_DB) as conn:
        total_docs = conn.execute("SELECT COUNT(*) AS c FROM documents").fetchone()["c"]
    return {"status": "success", "total_employees": total_emps, "total_documents": total_docs}

print("✅ HR function tools loaded with per-call connections and canonical session_memory.db")

✅ HR function tools loaded with per-call connections and canonical session_memory.db

In [39]:
# ====================================================================
# HR AUTOMATION — FULL FUNCTION TEST SUITE (MCP-Compatible Style)
# Cleaned up to avoid long-lived SQLite handles in the test harness.
# ====================================================================

import os
import json
import uuid
from datetime import datetime, timezone

# ============================================================
# Helpers
# ============================================================
def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()

def run_test(test_name, func, *args, **kwargs):
    print("\n" + "-" * 70)
    print(f"🔍 TEST: {test_name}")
    print("-" * 70)
    try:
        result = func(*args, **kwargs)
        print("✅ PASSED")
        print("Result:", result)
        return result
    except Exception as e:
        print("❌ FAILED:", test_name)
        raise

# ============================================================
# TEST CONSTANTS
# ============================================================
EMP_ID = "E0001"
SYS_NAME = "EmailSystem"
AGENT = "HR_Onboarding_Agent"

# ============================================================
# RUN TESTS — EMPLOYEES
# ============================================================
run_test("get_employee()", get_employee, EMP_ID)
run_test("search_employee(name contains)", search_employee, **{"name": "a"})
run_test("update_employee_status()", update_employee_status, EMP_ID, "Inactive")
run_test("update_employee()", update_employee, EMP_ID, {"role": "Senior Developer"})

# ============================================================
# WORKFLOW TESTS
# ============================================================
print("\n=== Creating new workflow for testing ===")
new_wf = create_workflow("onboarding", EMP_ID)
WF_ID = new_wf["workflow_id"]

run_test("get_workflow_state()", get_workflow_state, WF_ID)
run_test("update_workflow_status()", update_workflow_status, WF_ID, "In Progress")
run_test("advance_workflow()", advance_workflow, WF_ID, "background_check")

# ============================================================
# ASSET ASSIGNMENT TESTS
# ============================================================
print("\n=== Testing asset assignment ===")
ASSET_ID = "1b8720aa-657e-4799-9279-7464e98e3710"

run_test("assign_asset()", assign_asset, ASSET_ID, EMP_ID)
run_test("reclaim_asset()", reclaim_asset, ASSET_ID)

# ============================================================
# DOCUMENT TESTS
# ============================================================
print("\n=== Creating test document ===")
doc = create_document(EMP_ID, "TestAgent", "NDA", "v1", "Confidential Document")
DOC_ID = doc["document_id"]

run_test("get_document()", get_document, DOC_ID)
run_test("list_employee_documents()", list_employee_documents, EMP_ID)
run_test("search_documents() (local SQLite search)", search_documents, "Confidential", 3)

# ============================================================
# ACCESS LOG TESTS
# ============================================================
if os.path.exists("access_logs.db"):
    run_test("grant_access()", grant_access, EMP_ID, SYS_NAME)
    run_test("list_access()", list_access, EMP_ID)
    run_test("check_access_permissions()", check_access_permissions, EMP_ID)
    run_test("revoke_access()", revoke_access, EMP_ID, SYS_NAME)
else:
    print("\n⚠️ Access DB missing — skipping access_log tests")

# ============================================================
# SESSION CONTEXT TESTS
# ============================================================
if os.path.exists("session_memory.db"):
    print("\n=== Saving session context ===")
    ctx = {"step": "initial", "notes": "testing context tool", "timestamp": now_iso()}
    save_agent_context(AGENT, EMP_ID, ctx)

    run_test("load_agent_context()", load_agent_context, AGENT, EMP_ID)
    run_test("clear_agent_context()", clear_agent_context, AGENT, EMP_ID)
else:
    print("\n⚠️ Session DB missing — skipping agent_context tests")

# ============================================================
# SUMMARY TEST
# ============================================================
run_test("demo_summary()", demo_summary)

print("\n🎉 All tests executed.\n")

----------------------------------------------------------------------
🔍 TEST: get_employee()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'employee': {'employee_id': 'E0001', 'name': 'John Harris', 'department': 'Finance', 'role': 'Senior Developer', 'hire_date': '2024-05-29', 'email': 'john.harris@example.com', 'status': 'Inactive', 'created_at': '2026-06-19 01:55:22', 'updated_at': '2026-06-19 02:02:33'}}

----------------------------------------------------------------------
🔍 TEST: search_employee(name contains)
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'results': [{'employee_id': 'E0001', 'name': 'John Harris', 'department': 'Finance', 'role': 'Senior Developer', 'hire_date': '2024-05-29', 'email': 'john.harris@example.com', 'status': 'Inactive', 'created_at': '2026-06-19 01:55:22', 'updated_at': '2026-06-19 02:02:33'}, {'employee_id': 'E0002', 'name': 'Brian Bryant', 'department': 'IT', 'role': 'IT Support Engineer', 'hire_date': '2024-08-06', 'email': 'brian.bryant@example.com', 'status': 'On Leave', 'created_at': '2026-06-19 01:55:22', 'updated_at': '2026-06-19 01:55:22'}, {'employee_id': 'E0004', 'name': 'Heather Ruiz', 'department': 'HR', 'role': 'HR Executive', 'hire_date': '2024-12-22', 'email': 'heather.ruiz@example.com', 'status': 'Active', 'created_at': '2026-06-19 01:55:22', 'updated_at': '2026-06-19 01:55:22'}, {'employee_id': 'E0005', 'name': 'Pamela Bailey', 'department': 'Legal', 'role': 'Compliance Officer', 'hire_date': '2024-05-23', 'email': 'pamela.bailey@example.com', 'status': 'Active', 'created_at': '2026-06-19 01:55:22', 'updated_at': '2026-06-19 01:55:22'}, {'employee_id': 'E0007', 'name': 'Karen Mercado', 'department': 'IT', 'role': 'IT Support Engineer', 'hire_date': '2026-06-15', 'email': 'karen.mercado@example.com', 'status': 'Active', 'created_at': '2026-06-19 01:55:22', 'updated_at': '2026-06-19 01:55:22'}, {'employee_id': 'E0008', 'name': 'Sean Reynolds', 'department': 'Finance', 'role': 'Finance Manager', 'hire_date': '2023-12-11', 'email': 'sean.reynolds@example.com', 'status': 'On Leave', 'created_at': '2026-06-19 01:55:22', 'updated_at': '2026-06-19 01:55:22'}, {'employee_id': 'E0009', 'name': 'Gerald Acosta', 'department': 'IT', 'role': 'Cloud Administrator', 'hire_date': '2024-04-23', 'email': 'gerald.acosta@example.com', 'status': 'Active', 'created_at': '2026-06-19 01:55:22', 'updated_at': '2026-06-19 01:55:22'}, {'employee_id': 'E0011', 'name': 'Jennifer Williams', 'department': 'Engineering', 'role': 'DevOps Engineer', 'hire_date': '2022-08-11', 'email': 'jennifer.williams@example.com', 'status': 'Active', 'created_at': '2026-06-19 01:55:22', 'updated_at': '2026-06-19 01:55:22'}, {'employee_id': 'E0012', 'name': 'Morgan Ramirez', 'department': 'HR', 'role': 'HR Manager', 'hire_date': '2025-05-15', 'email': 'morgan.ramirez@example.com', 'status': 'Active', 'created_at': '2026-06-19 01:55:22', 'updated_at': '2026-06-19 01:55:22'}, {'employee_id': 'E0013', 'name': 'Madison Brown', 'department': 'Engineering', 'role': 'Engineering Manager', 'hire_date': '2022-08-20', 'email': 'madison.brown@example.com', 'status': 'Active', 'created_at': '2026-06-19 01:55:22', 'updated_at': '2026-06-19 01:55:22'}]}

----------------------------------------------------------------------
🔍 TEST: update_employee_status()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'employee': {'employee_id': 'E0001', 'name': 'John Harris', 'department': 'Finance', 'role': 'Senior Developer', 'hire_date': '2024-05-29', 'email': 'john.harris@example.com', 'status': 'Inactive', 'created_at': '2026-06-19 01:55:22', 'updated_at': '2026-06-19 02:02:40'}}

----------------------------------------------------------------------
🔍 TEST: update_employee()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'employee': {'employee_id': 'E0001', 'name': 'John Harris', 'department': 'Finance', 'role': 'Senior Developer', 'hire_date': '2024-05-29', 'email': 'john.harris@example.com', 'status': 'Inactive', 'created_at': '2026-06-19 01:55:22', 'updated_at': '2026-06-19 02:02:40'}}

=== Creating new workflow for testing ===

----------------------------------------------------------------------
🔍 TEST: get_workflow_state()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'workflow': {'workflow_id': 'c61f42bd-1ce0-42a3-96bf-980b2be65c29', 'workflow_type': 'onboarding', 'employee_id': 'E0001', 'current_step': '', 'status': 'Pending', 'triggered_by': None, 'created_at': '2026-06-19 02:02:40', 'last_updated': '2026-06-19T02:02:40.763551'}}

----------------------------------------------------------------------
🔍 TEST: update_workflow_status()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'workflow': {'workflow_id': 'c61f42bd-1ce0-42a3-96bf-980b2be65c29', 'workflow_type': 'onboarding', 'employee_id': 'E0001', 'current_step': '', 'status': 'In Progress', 'triggered_by': None, 'created_at': '2026-06-19 02:02:40', 'last_updated': '2026-06-19 02:02:40'}}

----------------------------------------------------------------------
🔍 TEST: advance_workflow()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'workflow': {'workflow_id': 'c61f42bd-1ce0-42a3-96bf-980b2be65c29', 'workflow_type': 'onboarding', 'employee_id': 'E0001', 'current_step': 'background_check', 'status': 'In Progress', 'triggered_by': None, 'created_at': '2026-06-19 02:02:40', 'last_updated': '2026-06-19 02:02:40'}}

=== Testing asset assignment ===

----------------------------------------------------------------------
🔍 TEST: assign_asset()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'error', 'error_message': 'Asset 1b8720aa-657e-4799-9279-7464e98e3710 does not exist'}

----------------------------------------------------------------------
🔍 TEST: reclaim_asset()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'error', 'error_message': 'Asset 1b8720aa-657e-4799-9279-7464e98e3710 does not exist'}

=== Creating test document ===

/tmp/ipykernel_1272/3783282363.py:30: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().isoformat()

----------------------------------------------------------------------
🔍 TEST: get_document()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'document': {'document_id': '9bedf045-de27-4e8f-9643-60186ccd699e', 'employee_id': 'E0001', 'agent_name': 'TestAgent', 'doc_type': 'NDA', 'template_version': 'v1', 'content': 'Confidential Document', 'generated_on': '2026-06-19T02:02:40.798386'}}

----------------------------------------------------------------------
🔍 TEST: list_employee_documents()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'documents': [{'document_id': '9bedf045-de27-4e8f-9643-60186ccd699e', 'employee_id': 'E0001', 'agent_name': 'TestAgent', 'doc_type': 'NDA', 'template_version': 'v1', 'content': 'Confidential Document', 'generated_on': '2026-06-19T02:02:40.798386'}, {'document_id': '29888c29-0fd6-44d9-86c4-b231c301a8a0', 'employee_id': 'E0001', 'agent_name': 'TestAgent', 'doc_type': 'NDA', 'template_version': 'v1', 'content': 'Confidential Document', 'generated_on': '2026-06-19T02:02:33.799546'}, {'document_id': '7cda3c91-3365-4a9d-9dd1-5cf0c1db0eb1', 'employee_id': 'E0001', 'agent_name': 'Compliance Monitoring Agent', 'doc_type': 'Offer Letter', 'template_version': 'v2', 'content': "\nOffer Letter – ACME Corporation\n\nDear Kiara Larsen,\n\nWe are pleased to offer you the position of **Accountant** in the **Finance Department** at ACME Corporation.\nYour total annual compensation will be **₹685,108**, payable according to the company's standard payroll cycle.\n\nYour tentative joining date is **10 July 2026**.\nYou will be on a probation period of 6 months, after which your performance will be reviewed.\n\nWe welcome you to ACME Corporation and look forward to your contribution.\n\nSincerely,\nACME HR Team\n", 'generated_on': '2026-06-19 01:54:15.367436'}, {'document_id': 'e8bf78de-78b2-4351-9937-4ebcd0eb3885', 'employee_id': 'E0001', 'agent_name': 'Document Generation Agent', 'doc_type': 'Offer Letter', 'template_version': 'v2', 'content': 'OFFER LETTER\n\nDear John Harris,\n\nWe are pleased to offer you the position of Accountant\nin the Finance department.\n\nYour employment start date is 2024-05-29.\n\nRegards,\nHuman Resources', 'generated_on': '2026-06-05 01:55:22.649246'}, {'document_id': '65b3d371-fd8f-44d5-b620-d81d8436c602', 'employee_id': 'E0001', 'agent_name': 'Access Management Agent', 'doc_type': 'Experience Letter', 'template_version': 'v1', 'content': 'EXPERIENCE LETTER\n\nThis is to certify that John Harris\nworked as a Accountant in the\nFinance department.\n\nThe employee demonstrated professionalism,\nownership, and commitment to business goals.\n\nRegards,\nAccess Management Agent', 'generated_on': '2026-04-02 01:55:22.652148'}]}

----------------------------------------------------------------------
🔍 TEST: search_documents() (local SQLite search)
----------------------------------------------------------------------
✅ PASSED
Result: [{'document_id': '9bedf045-de27-4e8f-9643-60186ccd699e', 'employee_id': 'E0001', 'agent_name': 'TestAgent', 'doc_type': 'NDA', 'template_version': 'v1', 'content': 'Confidential Document', 'generated_on': '2026-06-19T02:02:40.798386'}, {'document_id': '29888c29-0fd6-44d9-86c4-b231c301a8a0', 'employee_id': 'E0001', 'agent_name': 'TestAgent', 'doc_type': 'NDA', 'template_version': 'v1', 'content': 'Confidential Document', 'generated_on': '2026-06-19T02:02:33.799546'}, {'document_id': 'bdfef8b8-8ab4-43c7-8f96-c45d661efe41', 'employee_id': 'E0457', 'agent_name': 'Knowledge Retrieval Agent', 'doc_type': 'Policy Document', 'template_version': 'v1', 'content': 'REMOTE WORK POLICY\n\nVersion: v1\n\nEmployees must:\n\n1. Follow security requirements.\n2. Protect confidential information.\n3. Attend mandatory meetings.\n4. Maintain productivity standards.\n5. Follow compliance guidelines.\n\nIssued By:\nKnowledge Retrieval Agent', 'generated_on': '2026-06-19 01:55:22.638835'}]

----------------------------------------------------------------------
🔍 TEST: grant_access()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'access_id': 'f17c70b8-60ed-44f3-be63-a2a9bd83d685'}

----------------------------------------------------------------------
🔍 TEST: list_access()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'access_logs': [{'access_id': 'f17c70b8-60ed-44f3-be63-a2a9bd83d685', 'employee_id': 'E0001', 'system_name': 'EmailSystem', 'access_type': 'granted', 'granted_by': None, 'granted_on': '2026-06-19T02:02:41.261178', 'revoked_on': None}, {'access_id': '943721df-c3af-46e7-b712-23867a4e5ae5', 'employee_id': 'E0001', 'system_name': 'EmailSystem', 'access_type': 'granted', 'granted_by': None, 'granted_on': '2026-06-19T02:02:34.124672', 'revoked_on': '2026-06-19T02:02:34.133778'}, {'access_id': '754283a4-abef-4bf0-b4b0-bb3bd1d8c327', 'employee_id': 'E0001', 'system_name': 'IT Ticketing', 'access_type': 'Read', 'granted_by': 'Philip Obrien', 'granted_on': '2026-03-12T01:53:55.252155', 'revoked_on': None}]}

----------------------------------------------------------------------
🔍 TEST: check_access_permissions()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'access': [{'access_id': 'f17c70b8-60ed-44f3-be63-a2a9bd83d685', 'employee_id': 'E0001', 'system_name': 'EmailSystem', 'access_type': 'granted', 'granted_by': None, 'granted_on': '2026-06-19T02:02:41.261178', 'revoked_on': None}, {'access_id': '943721df-c3af-46e7-b712-23867a4e5ae5', 'employee_id': 'E0001', 'system_name': 'EmailSystem', 'access_type': 'granted', 'granted_by': None, 'granted_on': '2026-06-19T02:02:34.124672', 'revoked_on': '2026-06-19T02:02:34.133778'}, {'access_id': '754283a4-abef-4bf0-b4b0-bb3bd1d8c327', 'employee_id': 'E0001', 'system_name': 'IT Ticketing', 'access_type': 'Read', 'granted_by': 'Philip Obrien', 'granted_on': '2026-03-12T01:53:55.252155', 'revoked_on': None}]}

----------------------------------------------------------------------
🔍 TEST: revoke_access()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'access_id': 'f17c70b8-60ed-44f3-be63-a2a9bd83d685'}

=== Saving session context ===

----------------------------------------------------------------------
🔍 TEST: load_agent_context()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'session_id': 'HR_Onboarding_Agent::E0001', 'context': {'step': 'initial', 'notes': 'testing context tool', 'timestamp': '2026-06-19T02:02:41.274489+00:00'}, 'last_updated': '2026-06-19T02:02:41.274517'}

----------------------------------------------------------------------
🔍 TEST: clear_agent_context()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'session_id': 'HR_Onboarding_Agent::E0001'}

----------------------------------------------------------------------
🔍 TEST: demo_summary()
----------------------------------------------------------------------
✅ PASSED
Result: {'status': 'success', 'total_employees': 1000, 'total_documents': 2032}

🎉 All tests executed.

In [40]:
from google.adk.tools.mcp_tool.mcp_toolset import (
    McpToolset,
    StreamableHTTPConnectionParams,
)

mcp_toolset = McpToolset(
    connection_params=StreamableHTTPConnectionParams(
        url="http://127.0.0.1:9001/mcp",
        timeout=300,
    )
)

In [41]:
# ---------------------------------------------------------------------
# 7. RESUME REVIEWER AGENT (Synthetic Resume Screening)
# ---------------------------------------------------------------------
resume_reviewer_agent = LlmAgent(
    name="resume_reviewer_agent",
    model=Gemini(model="gemini-2.5-flash-lite"),

    instruction="""
You are the Resume Reviewer Agent.

Responsibilities:
1. Generate sample resumes using `generate_sample_resumes_tool`
2. Review a single resume using `review_resume`
3. Create a shortlist using `shortlist_resumes`

Rules:
- Score resumes against the target role and department.
- Return concise hiring recommendations.
- Prefer structured output with shortlist, score, and rationale.
""",
    tools=[mcp_toolset],
)

print("✅ Resume Reviewer agent created with tools:")
print("  • generate_sample_resumes_tool")
print("  • review_resume")
print("  • shortlist_resumes")

✅ Resume Reviewer agent created with tools:
  • generate_sample_resumes_tool
  • review_resume
  • shortlist_resumes

In [42]:
employee_agent = LlmAgent(
    name="employee_agent",
    model=Gemini(model="gemini-2.5-flash-lite"),

    instruction="""
You are the Employee Information Agent.

Responsibilities:
1. Fetch employee details using `get_employee_profile`
2. Search for employees using `search_employees`
3. Deactivate employees using `deactivate_employee`

Rules:
- ALWAYS check the `status` field in tool responses.
- If status == "error", explain clearly.
- Summarize employee details concisely.
""",

    tools=[mcp_toolset],
)

print("✅ Employee agent created with function tools:")
print("  • get_employee")
print("  • search_employee")
print("  • update_employee_status")

✅ Employee agent created with function tools:
  • get_employee
  • search_employee
  • update_employee_status

In [43]:
access_management_agent = LlmAgent(
    name="access_management_agent",
    model=Gemini(model="gemini-2.5-flash-lite"),

    instruction="""
You are the Access Management Agent.

Responsibilities:
1. Grant access using `grant_employee_access`
2. Revoke access using `revoke_employee_access`
3. Check permissions using `check_employee_access`

Rules:
- Always validate tool response status.
- Clearly state system, employee, and final access state.
""",

    tools=[mcp_toolset],
)


print("✅ Access Management agent created with tools:")
print("  • grant_access")
print("  • revoke_access")
print("  • check_access_permissions")

✅ Access Management agent created with tools:
  • grant_access
  • revoke_access
  • check_access_permissions

In [44]:
asset_management_agent = LlmAgent(
    name="asset_management_agent",
    model=Gemini(model="gemini-2.5-flash-lite"),

    instruction="""
You are the Asset Management Agent.

Responsibilities:
1. Assign assets using `assign_employee_asset`
2. Reclaim assets using `reclaim_employee_asset`

Rules:
- Always inspect `status`.
- If asset unavailable, explain why and suggest alternatives.
""",

    tools=[mcp_toolset],
)

print("✅ Asset Management agent created with tools:")
print("  • assign_asset")
print("  • reclaim_asset")

✅ Asset Management agent created with tools:
  • assign_asset
  • reclaim_asset

In [45]:
# =====================================================================
# ADDITIONAL AGENTS FOR FULL HR WORKFLOW AUTOMATION (MCP-AWARE)
# =====================================================================

# ---------------------------------------------------------------------
# 1. DOCUMENT GENERATION AGENT
# ---------------------------------------------------------------------
document_generation_agent = LlmAgent(
    name="document_generation_agent",
    model=Gemini(model="gemini-2.5-flash-lite"),

    instruction="""
You are the Document Generation Agent.

Responsibilities:
1. Generate documents using `generate_employee_document`
2. Fetch documents using `get_employee_document`
3. Search documents using `search_hr_documents`

Rules:
- Validate tool responses.
- Summarize document metadata and versions.
""",

    tools=[mcp_toolset],
)


print("✅ Document Generation agent created with tools:")
print("  • create_document")
print("  • get_document")
print("  • list_employee_documents")





# ---------------------------------------------------------------------
# 3. POLICY/Q&A KNOWLEDGE AGENT (DOCUMENT SEARCH + SEMANTIC QA)
# ---------------------------------------------------------------------
policy_agent = LlmAgent(
    name="policy_agent",
    model=Gemini(model="gemini-2.5-flash-lite"),

    instruction="""
You are the HR Policy & Compliance Agent.

Responsibilities:
1. Search documents using `search_hr_documents`
2. Retrieve documents using `get_employee_document`
3. Answer policy questions with citations.

Rules:
- Validate search results.
- Cite sections from document content.
""",

    tools=[mcp_toolset],
)

print("✅ Policy/Knowledge agent created with tools:")
print("  • search_documents")
print("  • get_document")


# ---------------------------------------------------------------------
# 4. SESSION CONTEXT & MEMORY AGENT (MCP STATE MANAGER)
# ---------------------------------------------------------------------
session_agent = LlmAgent(
    name="session_agent",
    model=Gemini(model="gemini-2.5-flash-lite"),

    instruction="""
You are the MCP Session & Context Agent.

Responsibilities:
1. Save context using `save_agent_context`
2. Load context using `load_agent_context`
3. Clear context using `clear_agent_context`

Rules:
- Ensure continuity across agents.
- Always validate status fields.
""",

    tools=[mcp_toolset],
)

print("✅ Session/Context agent created with tools:")
print("  • save_agent_context")
print("  • load_agent_context")
print("  • clear_agent_context")


# ---------------------------------------------------------------------
# 5. OFFBOARDING AGENT (Combines Access + Assets + Workflows)
# ---------------------------------------------------------------------
offboarding_agent = LlmAgent(
    name="offboarding_agent",
    model=Gemini(model="gemini-2.5-flash-lite"),

    instruction="""
You are the Employee Offboarding Automation Agent.

Sequence:
1. Check access (`check_employee_access`)
2. Revoke access (`revoke_employee_access`)
3. Reclaim assets (`reclaim_employee_asset`)
4. Generate exit documents (`generate_employee_document`)
5. Deactivate employee (`deactivate_employee`)
6. Start & close workflow (`start_workflow`, `advance_employee_workflow`)

Rules:
- Execute steps strictly in order.
- Maintain workflow + asset + access context.
- Output a structured offboarding summary.
""",

    tools=[mcp_toolset],
)

print("✅ Offboarding agent created with tools:")
print("  • revoke_access")
print("  • reclaim_asset")
print("  • update_employee_status")
print("  • create_document")
print("  • create_workflow")
print("  • advance_workflow")
print("  • update_workflow_status")
print("  • check_access_permissions")


# ---------------------------------------------------------------------
# 6. ONBOARDING AGENT (Assets + Access + Documents + Workflow)
# ---------------------------------------------------------------------
onboarding_agent = LlmAgent(
    name="onboarding_agent",
    model=Gemini(model="gemini-2.5-flash-lite"),

    instruction="""
You are the Employee Onboarding Automation Agent.

Responsibilities:
1. Generate documents (`generate_employee_document`)
2. Assign assets (`assign_employee_asset`)
3. Grant access (`grant_employee_access`)
4. Start workflow (`start_workflow`)
5. Save context (`save_agent_context`)

Rules:
- Track onboarding checklist.
- Validate all tool responses.
""",

    tools=[mcp_toolset],
)

print("✅ Onboarding agent created with tools:")
print("  • create_document")
print("  • assign_asset")
print("  • grant_access")
print("  • update_employee_status")
print("  • create_workflow")
print("  • advance_workflow")
print("  • save_agent_context")

✅ Document Generation agent created with tools:
  • create_document
  • get_document
  • list_employee_documents
✅ Policy/Knowledge agent created with tools:
  • search_documents
  • get_document
✅ Session/Context agent created with tools:
  • save_agent_context
  • load_agent_context
  • clear_agent_context
✅ Offboarding agent created with tools:
  • revoke_access
  • reclaim_asset
  • update_employee_status
  • create_document
  • create_workflow
  • advance_workflow
  • update_workflow_status
  • check_access_permissions
✅ Onboarding agent created with tools:
  • create_document
  • assign_asset
  • grant_access
  • update_employee_status
  • create_workflow
  • advance_workflow
  • save_agent_context

In [46]:
from dataclasses import dataclass, asdict, field

A2A_HANDLERS: Dict[str, Any] = {}

@dataclass
class A2AMessage:
    message_id: str
    conversation_id: str
    trace_id: str
    sender: str
    recipient: str
    intent: str
    payload: Dict[str, Any]
    context_ref: Optional[str] = None
    eval_run_id: Optional[str] = None
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())

def register_a2a_handler(agent_name: str, handler) -> None:
    A2A_HANDLERS[agent_name] = handler

def create_a2a_message(
    sender: str,
    recipient: str,
    intent: str,
    payload: Dict[str, Any],
    conversation_id: Optional[str] = None,
    trace_id: Optional[str] = None,
    context_ref: Optional[str] = None,
    eval_run_id: Optional[str] = None,
) -> A2AMessage:
    return A2AMessage(
        message_id=str(uuid.uuid4()),
        conversation_id=conversation_id or str(uuid.uuid4()),
        trace_id=trace_id or str(uuid.uuid4()),
        sender=sender,
        recipient=recipient,
        intent=intent,
        payload=payload,
        context_ref=context_ref,
        eval_run_id=eval_run_id,
    )

def send_a2a_message(message: A2AMessage) -> Dict[str, Any]:
    handler = A2A_HANDLERS.get(message.recipient)
    if not handler:
        return {
            "status": "error",
            "error_message": f"No A2A handler registered for {message.recipient}",
            "message": asdict(message),
        }

    if message.eval_run_id:
        log_eval_event(
            message.eval_run_id,
            message.sender,
            f"a2a:{message.intent}:sent",
            "ok",
            asdict(message),
        )

    response = handler(asdict(message))

    if message.eval_run_id:
        log_eval_event(
            message.eval_run_id,
            message.recipient,
            f"a2a:{message.intent}:received",
            "ok",
            response if isinstance(response, dict) else {"response": str(response)},
        )

    return {
        "status": "success",
        "message": asdict(message),
        "response": response,
    }

def resume_reviewer_a2a_handler(message: Dict[str, Any]) -> Dict[str, Any]:
    payload = message.get("payload", {})
    intent = message.get("intent", "")

    if intent != "review_candidates":
        return {"status": "error", "error_message": f"Unsupported intent: {intent}"}

    target_role = payload.get("target_role", "Software Engineer")
    target_department = payload.get("target_department", "Engineering")
    sample_count = int(payload.get("sample_count", 12))
    shortlist_limit = int(payload.get("shortlist_limit", 5))

    gen = generate_sample_resumes_tool(n=sample_count)
    shortlist = shortlist_resumes(
        target_role=target_role,
        target_department=target_department,
        min_score=50,
        limit=shortlist_limit,
    )

    ranked = shortlist.get("shortlist", [])
    selected = ranked[0] if ranked else None

    return {
        "status": "success",
        "generated": gen,
        "shortlist": shortlist,
        "selected_employee_id": selected.get("employee_id") if selected else None,
        "selected_document_id": selected.get("document_id") if selected else None,
        "selected_score": selected.get("score") if selected else None,
        "selected_reasons": selected.get("reasons", []) if selected else [],
    }

def orchestrator_a2a_handler(message: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "status": "success",
        "ack": True,
        "received_intent": message.get("intent"),
        "from": message.get("sender"),
    }

register_a2a_handler("resume_reviewer_agent", resume_reviewer_a2a_handler)
register_a2a_handler("workflow_orchestrator_agent", orchestrator_a2a_handler)

def request_resume_review_via_a2a(
    *,
    eval_run_id: Optional[str],
    trace_id: str,
    target_role: str,
    target_department: str,
    sample_count: int = 12,
    shortlist_limit: int = 5,
) -> Dict[str, Any]:
    msg = create_a2a_message(
        sender="workflow_orchestrator_agent",
        recipient="resume_reviewer_agent",
        intent="review_candidates",
        payload={
            "target_role": target_role,
            "target_department": target_department,
            "sample_count": sample_count,
            "shortlist_limit": shortlist_limit,
        },
        trace_id=trace_id,
        eval_run_id=eval_run_id,
    )
    return send_a2a_message(msg)

print("✅ A2A protocol registered")

✅ A2A protocol registered

In [47]:
from datetime import datetime

def _run_resume_review_phase(
    results: Dict[str, Any],
    target_role: str,
    target_department: str,
    sample_count: int = 12,
    shortlist_limit: int = 5,
) -> Optional[str]:

    generated = generate_sample_resumes_tool(n=sample_count)

    _execute_step(
        results,
        "generate_sample_resumes",
        generated,
    )

    shortlist = shortlist_resumes(
        target_role=target_role,
        target_department=target_department,
        min_score=50,
        limit=shortlist_limit,
    )

    _execute_step(
        results,
        "shortlist_resumes",
        shortlist,
    )

    ranked = shortlist.get("shortlist", [])

    if not ranked:
        return None

    top = ranked[0]

    results["resume_review"] = {
        "status": "success",
        "selected_employee_id": top["employee_id"],
        "selected_score": top["score"],
        "selected_reasons": top.get("reasons", []),
    }

    return top["employee_id"]

In [48]:
from typing import Any, Dict, List, Optional
import json
import uuid
from datetime import datetime, timezone

AGENT_MODEL = globals().get("AGENT_MODEL", "gemini-2.5-flash-lite")

# Assumptions:
# - LlmAgent, Gemini, mcp_toolset exist
# - Tool functions from cell 37 exist:
#   generate_sample_resumes_tool, shortlist_resumes, get_employee, create_workflow,
#   advance_workflow, update_workflow_status, save_agent_context, load_agent_context,
#   clear_agent_context, grant_access, revoke_access, check_access_permissions,
#   assign_asset, reclaim_asset, create_document, update_employee_status,
#   get_workflow_state, list_employee_documents

resume_reviewer_agent = LlmAgent(
    name="resume_reviewer_agent",
    model=Gemini(model=AGENT_MODEL),
    instruction="""
You are the Resume Reviewer Agent.

Use the available tools to generate sample resumes, review them, and shortlist the best candidates.
Focus on role fit, department fit, years of experience, and relevant keywords.
Return concise, structured recommendations.
""",
    tools=[mcp_toolset],
)

workflow_orchestrator_agent = LlmAgent(
    name="workflow_orchestrator_agent",
    model=Gemini(model=AGENT_MODEL),
    instruction="""
You are the top-level HR workflow orchestrator.

You coordinate onboarding, offboarding, onboarding_then_offboarding, resume review,
document generation, access provisioning and revocation, asset assignment and reclaim,
and session memory updates.

Rules:
- Inspect the employee record first whenever employee_id is provided.
- If employee_id is missing for onboarding, use the resume review phase to select a candidate.
- Save session context after each major phase.
- Load context before resuming a partially completed workflow.
- Clear context after offboarding completes.
- Validate tool outputs before continuing.
- Return a concise final summary with workflow status, employee, documents, access, and asset state.
""",
    tools=[mcp_toolset],
)

print("✅ Resume reviewer agent created")
print("✅ Workflow orchestrator agent created")

def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()

def _execute_step(results: Dict[str, Any], step_name: str, payload: Any) -> Any:
    results["steps"].append({"step": step_name, "result": payload})
    return payload

def _session_memory_demo(results: Dict[str, Any], employee_id: str, phase_label: str) -> Dict[str, Any]:
    save_result = save_agent_context(
        agent_name="workflow_orchestrator_agent",
        employee_id=employee_id,
        context={
            "phase": phase_label,
            "employee_id": employee_id,
            "workflow_id": results.get("workflow_id"),
            "scenario": results.get("scenario"),
            "trace_id": results.get("trace_id"),
            "timestamp": _utc_now_iso(),
        },
    )
    _execute_step(results, f"save_context_{phase_label}", save_result)

    load_result = load_agent_context(
        agent_name="workflow_orchestrator_agent",
        employee_id=employee_id,
    )
    _execute_step(results, f"load_context_{phase_label}", load_result)

    results[f"session_context_{phase_label}"] = load_result
    return load_result

def _first_available_asset_id() -> Optional[str]:
    try:
        with sqlite3.connect("assets.db") as conn:
            conn.row_factory = sqlite3.Row
            row = conn.execute(
                """
                SELECT asset_id
                FROM assets
                WHERE assigned_to IS NULL
                ORDER BY asset_id ASC
                LIMIT 1
                """
            ).fetchone()
        return row["asset_id"] if row else None
    except Exception:
        return None

def _memory_roundtrip(agent_name: str, employee_id: str, expected_phase: str) -> bool:
    loaded = load_agent_context(agent_name, employee_id)
    if loaded.get("status") != "success":
        return False
    ctx = loaded.get("context", {})
    return ctx.get("phase") == expected_phase

def run_full_hr_workflow(
    employee_id: Optional[str] = None,
    scenario: str = "onboarding_then_offboarding",
    systems: Optional[List[str]] = None,
    doc_type: str = "workflow_summary",
    use_resume_review: bool = True,
    review_target_role: str = "Software Engineer",
    review_target_department: str = "Engineering",
    resume_batch_size: int = 12,
) -> Dict[str, Any]:
    if systems is None:
        systems = ["email", "slack", "hr-portal"]

    results: Dict[str, Any] = {
        "employee_id": employee_id,
        "scenario": scenario,
        "timestamp": datetime.utcnow().isoformat(),
        "steps": [],
        "trace_id": str(uuid.uuid4()),
        "resume_review_used": False,
        "access_handled": False,
        "asset_handled": False,
    }

    selected_employee_id = employee_id
    eval_run_id: Optional[str] = None

    if selected_employee_id:
        eval_start = start_eval_run(
            workflow_id="pending",
            scenario=scenario,
            employee_id=selected_employee_id,
        )
        _execute_step(results, "start_eval_run", eval_start)
        eval_run_id = eval_start["eval_run_id"]

    if selected_employee_id is None and use_resume_review:
        _execute_step(results, "generate_sample_resumes", generate_sample_resumes_tool(n=resume_batch_size))
        shortlist = shortlist_resumes(
            target_role=review_target_role,
            target_department=review_target_department,
            min_score=50,
            limit=5,
        )
        _execute_step(results, "shortlist_resumes", shortlist)
        candidates = shortlist.get("shortlist", [])
        if not candidates:
            results["status"] = "error"
            results["error_message"] = "No suitable resume candidates found."
            return results

        selected_employee_id = candidates[0]["employee_id"]
        results["resume_review_used"] = True
        results["resume_selection"] = candidates[0]
        eval_start = start_eval_run(
            workflow_id="pending",
            scenario=scenario,
            employee_id=selected_employee_id,
        )
        _execute_step(results, "start_eval_run", eval_start)
        eval_run_id = eval_start["eval_run_id"]

    if not selected_employee_id:
        results["status"] = "error"
        results["error_message"] = "employee_id is required unless resume review finds a candidate."
        return results

    employee_record = get_employee(selected_employee_id)
    _execute_step(results, "get_employee", employee_record)
    if employee_record.get("status") != "success":
        results["status"] = "error"
        results["error_message"] = employee_record.get("error_message", "Unable to load employee")
        return results

    workflow = create_workflow(
        workflow_type=scenario,
        employee_id=selected_employee_id,
        current_step="start",
        triggered_by="run_full_hr_workflow",
    )
    _execute_step(results, "create_workflow", workflow)
    if workflow.get("status") != "success":
        results["status"] = "error"
        results["error_message"] = "Failed to create workflow"
        return results

    workflow_id = workflow["workflow_id"]
    results["workflow_id"] = workflow_id

    initial_context = _session_memory_demo(results, selected_employee_id, "workflow_started")
    results["initial_context"] = initial_context

    if scenario in {"onboarding", "onboarding_then_offboarding"}:
        _execute_step(results, "update_employee_status", update_employee_status(selected_employee_id, "Active"))

        access_results = []
        for system_name in systems:
            access_results.append(grant_access(selected_employee_id, system_name, granted_by="workflow_orchestrator_agent"))
        _execute_step(results, "grant_access", {"status": "success", "results": access_results})
        results["access_handled"] = True

        asset_id = _first_available_asset_id()
        if asset_id:
            asset_payload = assign_asset(asset_id, selected_employee_id)
            _execute_step(results, "assign_asset", asset_payload)
            results["asset_handled"] = True
            results["assigned_asset_id"] = asset_id
        else:
            _execute_step(results, "assign_asset", {"status": "error", "error_message": "No available asset found"})

        welcome_doc = create_document(
            employee_id=selected_employee_id,
            agent_name="workflow_orchestrator_agent",
            doc_type=doc_type,
            template_version="v1",
            content=json.dumps(
                {
                    "phase": "onboarding",
                    "employee_id": selected_employee_id,
                    "workflow_id": workflow_id,
                    "systems": systems,
                    "generated_at": _utc_now_iso(),
                },
                indent=2,
            ),
        )
        _execute_step(results, "create_document", welcome_doc)

        save_onboarding = save_agent_context(
            agent_name="workflow_orchestrator_agent",
            employee_id=selected_employee_id,
            context={
                "phase": "onboarding_complete",
                "employee_id": selected_employee_id,
                "workflow_id": workflow_id,
                "systems": systems,
                "assigned_asset_id": results.get("assigned_asset_id"),
                "document_id": welcome_doc.get("document_id"),
                "timestamp": _utc_now_iso(),
            },
        )
        _execute_step(results, "save_context_onboarding_complete", save_onboarding)
        loaded_onboarding = load_agent_context("workflow_orchestrator_agent", selected_employee_id)
        _execute_step(results, "load_context_onboarding_complete", loaded_onboarding)

    if scenario in {"offboarding", "onboarding_then_offboarding"}:
        current_access = check_access_permissions(selected_employee_id)
        _execute_step(results, "check_access_permissions", current_access)

        revoked = []
        for item in current_access.get("access", []):
            if item.get("revoked_on") is None:
                revoked.append(revoke_access(selected_employee_id, item["system_name"]))
        _execute_step(results, "revoke_access", {"status": "success", "results": revoked})
        results["access_handled"] = True

        try:
            if results.get("assigned_asset_id"):
                _execute_step(results, "reclaim_asset", reclaim_asset(results["assigned_asset_id"]))
                results["asset_handled"] = True
            else:
                with sqlite3.connect("assets.db") as conn:
                    conn.row_factory = sqlite3.Row
                    row = conn.execute(
                        """
                        SELECT asset_id
                        FROM assets
                        WHERE assigned_to = ?
                        ORDER BY assigned_on DESC
                        LIMIT 1
                        """,
                        (selected_employee_id,),
                    ).fetchone()
                if row:
                    _execute_step(results, "reclaim_asset", reclaim_asset(row["asset_id"]))
                    results["asset_handled"] = True
        except Exception as exc:
            _execute_step(results, "reclaim_asset", {"status": "error", "error_message": str(exc)})

        exit_doc = create_document(
            employee_id=selected_employee_id,
            agent_name="workflow_orchestrator_agent",
            doc_type=doc_type,
            template_version="v1",
            content=json.dumps(
                {
                    "phase": "offboarding",
                    "employee_id": selected_employee_id,
                    "workflow_id": workflow_id,
                    "generated_at": _utc_now_iso(),
                },
                indent=2,
            ),
        )
        _execute_step(results, "create_document", exit_doc)

        pre_clear = load_agent_context("workflow_orchestrator_agent", selected_employee_id)
        _execute_step(results, "load_context_before_clear", pre_clear)

        _execute_step(results, "deactivate_employee", update_employee_status(selected_employee_id, "Inactive"))

        clear_result = clear_agent_context("workflow_orchestrator_agent", selected_employee_id)
        _execute_step(results, "clear_agent_context", clear_result)

        post_clear = load_agent_context("workflow_orchestrator_agent", selected_employee_id)
        _execute_step(results, "load_context_after_clear", post_clear)

    _execute_step(results, "update_workflow_status", update_workflow_status(workflow_id, "Completed"))
    results["workflow"] = get_workflow_state(workflow_id)
    results["documents"] = list_employee_documents(selected_employee_id, limit=10)
    results["access"] = check_access_permissions(selected_employee_id)
    results["memory_roundtrip_ok"] = _memory_roundtrip("workflow_orchestrator_agent", selected_employee_id, "workflow_started")

    final_payload = {
        "workflow_status": results["workflow"].get("workflow", {}).get("status", "Unknown") if isinstance(results["workflow"], dict) else "Unknown",
        "memory_roundtrip_ok": results["memory_roundtrip_ok"],
        "resume_review_used": results["resume_review_used"],
        "access_handled": results["access_handled"],
        "asset_handled": results["asset_handled"],
        "notes": [step["step"] for step in results["steps"]],
    }
    results["evaluation"] = finish_eval_run(eval_run_id, final_payload) if eval_run_id else None
    results["status"] = "success"
    return results

def run_orchestrator_demo(
    employee_id: Optional[str] = None,
    scenario: str = "onboarding_then_offboarding",
) -> Dict[str, Any]:
    return run_full_hr_workflow(employee_id=employee_id, scenario=scenario)

print("✅ Final workflow loaded: run_full_hr_workflow(...)")

✅ Resume reviewer agent created
✅ Workflow orchestrator agent created
✅ Final workflow loaded: run_full_hr_workflow(...)

In [49]:
result = run_full_hr_workflow(
    employee_id=None,
    scenario="onboarding_then_offboarding",
    use_resume_review=True,
    review_target_role="Software Engineer",
    review_target_department="Engineering",
    resume_batch_size=15
)

print(json.dumps(result, indent=2, default=str))

/tmp/ipykernel_1272/128120074.py:126: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  "timestamp": datetime.utcnow().isoformat(),
/tmp/ipykernel_1272/2351905436.py:68: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  started_at = datetime.utcnow().isoformat()
/tmp/ipykernel_1272/3783282363.py:30: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().isoformat()

{
  "employee_id": null,
  "scenario": "onboarding_then_offboarding",
  "timestamp": "2026-06-19T02:03:20.324858",
  "steps": [
    {
      "step": "generate_sample_resumes",
      "result": {
        "status": "success",
        "inserted": 15,
        "doc_type": "Resume"
      }
    },
    {
      "step": "shortlist_resumes",
      "result": {
        "status": "success",
        "shortlist": [
          {
            "document_id": "d2ee2b24-f260-4fe3-8ade-b72107b7c4e9",
            "employee_id": "E0301",
            "agent_name": "Resume Reviewer Agent",
            "score": 65,
            "reasons": [
              "Target role appears in the resume text.",
              "Target department appears in the resume text.",
              "Resume includes an experience section.",
              "Resume includes an education section.",
              "Matched keywords: machine learning"
            ]
          },
          {
            "document_id": "85d14668-a3d2-4866-9398-daf6b2e77939",
            "employee_id": "E0392",
            "agent_name": "Resume Reviewer Agent",
            "score": 60,
            "reasons": [
              "Target department appears in the resume text.",
              "Resume includes an experience section.",
              "Resume includes an education section.",
              "Matched keywords: sql, api"
            ]
          },
          {
            "document_id": "df5fc5d2-6992-42d6-9711-e593819383fd",
            "employee_id": "E0392",
            "agent_name": "Resume Reviewer Agent",
            "score": 60,
            "reasons": [
              "Target department appears in the resume text.",
              "Resume includes an experience section.",
              "Resume includes an education section.",
              "Matched keywords: sql, api"
            ]
          }
        ],
        "count": 3
      }
    },
    {
      "step": "start_eval_run",
      "result": {
        "status": "success",
        "eval_run_id": "83c4d525-a258-4640-9e12-e03bbb76a5ba",
        "started_at": "2026-06-19T02:03:20.341292"
      }
    },
    {
      "step": "get_employee",
      "result": {
        "status": "success",
        "employee": {
          "employee_id": "E0301",
          "name": "Oscar Marsh",
          "department": "HR",
          "role": "Recruiter",
          "hire_date": "2024-03-03",
          "email": "oscar.marsh@example.com",
          "status": "Active",
          "created_at": "2026-06-19 01:55:22",
          "updated_at": "2026-06-19 01:55:22"
        }
      }
    },
    {
      "step": "create_workflow",
      "result": {
        "status": "success",
        "workflow_id": "f1e4d59f-99b9-4a8a-b7ce-f1600abb97b2"
      }
    },
    {
      "step": "save_context_workflow_started",
      "result": {
        "status": "success",
        "session_id": "workflow_orchestrator_agent::E0301",
        "last_updated": "2026-06-19T02:03:20.352950"
      }
    },
    {
      "step": "load_context_workflow_started",
      "result": {
        "status": "success",
        "session_id": "workflow_orchestrator_agent::E0301",
        "context": {
          "phase": "workflow_started",
          "employee_id": "E0301",
          "workflow_id": "f1e4d59f-99b9-4a8a-b7ce-f1600abb97b2",
          "scenario": "onboarding_then_offboarding",
          "trace_id": "6298b043-a873-43f1-8c36-85187065b224",
          "timestamp": "2026-06-19T02:03:20.352926+00:00"
        },
        "last_updated": "2026-06-19T02:03:20.352950"
      }
    },
    {
      "step": "update_employee_status",
      "result": {
        "status": "success",
        "employee": {
          "employee_id": "E0301",
          "name": "Oscar Marsh",
          "department": "HR",
          "role": "Recruiter",
          "hire_date": "2024-03-03",
          "email": "oscar.marsh@example.com",
          "status": "Active",
          "created_at": "2026-06-19 01:55:22",
          "updated_at": "2026-06-19 02:03:20"
        }
      }
    },
    {
      "step": "grant_access",
      "result": {
        "status": "success",
        "results": [
          {
            "status": "success",
            "access_id": "db6b9f3c-397d-4d11-9d49-4f3f3dac66ec"
          },
          {
            "status": "success",
            "access_id": "39828044-64ae-4a8b-b73d-3b6b52af3799"
          },
          {
            "status": "success",
            "access_id": "3a3dcd91-2d56-491a-a078-ab94cfe44c5e"
          }
        ]
      }
    },
    {
      "step": "assign_asset",
      "result": {
        "status": "success",
        "asset_id": "013d9486-6d5f-4661-b020-7d4b10c063de",
        "assigned_to": "E0301",
        "assigned_on": "2026-06-19T02:03:20.383384"
      }
    },
    {
      "step": "create_document",
      "result": {
        "status": "success",
        "document_id": "5f5784f1-4685-4642-894d-a9c3a53ad621"
      }
    },
    {
      "step": "save_context_onboarding_complete",
      "result": {
        "status": "success",
        "session_id": "workflow_orchestrator_agent::E0301",
        "last_updated": "2026-06-19T02:03:20.697993"
      }
    },
    {
      "step": "load_context_onboarding_complete",
      "result": {
        "status": "success",
        "session_id": "workflow_orchestrator_agent::E0301",
        "context": {
          "phase": "onboarding_complete",
          "employee_id": "E0301",
          "workflow_id": "f1e4d59f-99b9-4a8a-b7ce-f1600abb97b2",
          "systems": [
            "email",
            "slack",
            "hr-portal"
          ],
          "assigned_asset_id": "013d9486-6d5f-4661-b020-7d4b10c063de",
          "document_id": "5f5784f1-4685-4642-894d-a9c3a53ad621",
          "timestamp": "2026-06-19T02:03:20.697961+00:00"
        },
        "last_updated": "2026-06-19T02:03:20.697993"
      }
    },
    {
      "step": "check_access_permissions",
      "result": {
        "status": "success",
        "access": [
          {
            "access_id": "3a3dcd91-2d56-491a-a078-ab94cfe44c5e",
            "employee_id": "E0301",
            "system_name": "hr-portal",
            "access_type": "granted",
            "granted_by": "workflow_orchestrator_agent",
            "granted_on": "2026-06-19T02:03:20.375848",
            "revoked_on": null
          },
          {
            "access_id": "39828044-64ae-4a8b-b73d-3b6b52af3799",
            "employee_id": "E0301",
            "system_name": "slack",
            "access_type": "granted",
            "granted_by": "workflow_orchestrator_agent",
            "granted_on": "2026-06-19T02:03:20.370461",
            "revoked_on": null
          },
          {
            "access_id": "db6b9f3c-397d-4d11-9d49-4f3f3dac66ec",
            "employee_id": "E0301",
            "system_name": "email",
            "access_type": "granted",
            "granted_by": "workflow_orchestrator_agent",
            "granted_on": "2026-06-19T02:03:20.365173",
            "revoked_on": null
          },
          {
            "access_id": "0f3ee5df-08e6-4b33-a0c5-3929b22cdcba",
            "employee_id": "E0301",
            "system_name": "Slack",
            "access_type": "Write",
            "granted_by": "Scott Jackson",
            "granted_on": "2026-03-25T01:53:55.302373",
            "revoked_on": null
          }
        ]
      }
    },
    {
      "step": "revoke_access",
      "result": {
        "status": "success",
        "results": [
          {
            "status": "success",
            "access_id": "3a3dcd91-2d56-491a-a078-ab94cfe44c5e"
          },
          {
            "status": "success",
            "access_id": "39828044-64ae-4a8b-b73d-3b6b52af3799"
          },
          {
            "status": "success",
            "access_id": "db6b9f3c-397d-4d11-9d49-4f3f3dac66ec"
          },
          {
            "status": "success",
            "access_id": "0f3ee5df-08e6-4b33-a0c5-3929b22cdcba"
          }
        ]
      }
    },
    {
      "step": "reclaim_asset",
      "result": {
        "status": "success",
        "asset_id": "013d9486-6d5f-4661-b020-7d4b10c063de",
        "reclaimed_on": "2026-06-19T02:03:20.730303"
      }
    },
    {
      "step": "create_document",
      "result": {
        "status": "success",
        "document_id": "1848c184-7bb9-49b1-9e68-f5c21163608d"
      }
    },
    {
      "step": "load_context_before_clear",
      "result": {
        "status": "success",
        "session_id": "workflow_orchestrator_agent::E0301",
        "context": {
          "phase": "onboarding_complete",
          "employee_id": "E0301",
          "workflow_id": "f1e4d59f-99b9-4a8a-b7ce-f1600abb97b2",
          "systems": [
            "email",
            "slack",
            "hr-portal"
          ],
          "assigned_asset_id": "013d9486-6d5f-4661-b020-7d4b10c063de",
          "document_id": "5f5784f1-4685-4642-894d-a9c3a53ad621",
          "timestamp": "2026-06-19T02:03:20.697961+00:00"
        },
        "last_updated": "2026-06-19T02:03:20.697993"
      }
    },
    {
      "step": "deactivate_employee",
      "result": {
        "status": "success",
        "employee": {
          "employee_id": "E0301",
          "name": "Oscar Marsh",
          "department": "HR",
          "role": "Recruiter",
          "hire_date": "2024-03-03",
          "email": "oscar.marsh@example.com",
          "status": "Inactive",
          "created_at": "2026-06-19 01:55:22",
          "updated_at": "2026-06-19 02:03:21"
        }
      }
    },
    {
      "step": "clear_agent_context",
      "result": {
        "status": "success",
        "session_id": "workflow_orchestrator_agent::E0301"
      }
    },
    {
      "step": "load_context_after_clear",
      "result": {
        "status": "error",
        "error_message": "Context not found",
        "session_id": "workflow_orchestrator_agent::E0301"
      }
    },
    {
      "step": "update_workflow_status",
      "result": {
        "status": "success",
        "workflow": {
          "workflow_id": "f1e4d59f-99b9-4a8a-b7ce-f1600abb97b2",
          "workflow_type": "onboarding_then_offboarding",
          "employee_id": "E0301",
          "current_step": "start",
          "status": "Completed",
          "triggered_by": "run_full_hr_workflow",
          "created_at": "2026-06-19 02:03:20",
          "last_updated": "2026-06-19 02:03:21"
        }
      }
    }
  ],
  "trace_id": "6298b043-a873-43f1-8c36-85187065b224",
  "resume_review_used": true,
  "access_handled": true,
  "asset_handled": true,
  "resume_selection": {
    "document_id": "d2ee2b24-f260-4fe3-8ade-b72107b7c4e9",
    "employee_id": "E0301",
    "agent_name": "Resume Reviewer Agent",
    "score": 65,
    "reasons": [
      "Target role appears in the resume text.",
      "Target department appears in the resume text.",
      "Resume includes an experience section.",
      "Resume includes an education section.",
      "Matched keywords: machine learning"
    ]
  },
  "workflow_id": "f1e4d59f-99b9-4a8a-b7ce-f1600abb97b2",
  "session_context_workflow_started": {
    "status": "success",
    "session_id": "workflow_orchestrator_agent::E0301",
    "context": {
      "phase": "workflow_started",
      "employee_id": "E0301",
      "workflow_id": "f1e4d59f-99b9-4a8a-b7ce-f1600abb97b2",
      "scenario": "onboarding_then_offboarding",
      "trace_id": "6298b043-a873-43f1-8c36-85187065b224",
      "timestamp": "2026-06-19T02:03:20.352926+00:00"
    },
    "last_updated": "2026-06-19T02:03:20.352950"
  },
  "initial_context": {
    "status": "success",
    "session_id": "workflow_orchestrator_agent::E0301",
    "context": {
      "phase": "workflow_started",
      "employee_id": "E0301",
      "workflow_id": "f1e4d59f-99b9-4a8a-b7ce-f1600abb97b2",
      "scenario": "onboarding_then_offboarding",
      "trace_id": "6298b043-a873-43f1-8c36-85187065b224",
      "timestamp": "2026-06-19T02:03:20.352926+00:00"
    },
    "last_updated": "2026-06-19T02:03:20.352950"
  },
  "assigned_asset_id": "013d9486-6d5f-4661-b020-7d4b10c063de",
  "workflow": {
    "status": "success",
    "workflow": {
      "workflow_id": "f1e4d59f-99b9-4a8a-b7ce-f1600abb97b2",
      "workflow_type": "onboarding_then_offboarding",
      "employee_id": "E0301",
      "current_step": "start",
      "status": "Completed",
      "triggered_by": "run_full_hr_workflow",
      "created_at": "2026-06-19 02:03:20",
      "last_updated": "2026-06-19 02:03:21"
    }
  },
  "documents": {
    "status": "success",
    "documents": [
      {
        "document_id": "1848c184-7bb9-49b1-9e68-f5c21163608d",
        "employee_id": "E0301",
        "agent_name": "workflow_orchestrator_agent",
        "doc_type": "workflow_summary",
        "template_version": "v1",
        "content": "{\n  \"phase\": \"offboarding\",\n  \"employee_id\": \"E0301\",\n  \"workflow_id\": \"f1e4d59f-99b9-4a8a-b7ce-f1600abb97b2\",\n  \"generated_at\": \"2026-06-19T02:03:20.735399+00:00\"\n}",
        "generated_on": "2026-06-19T02:03:20.735491"
      },
      {
        "document_id": "5f5784f1-4685-4642-894d-a9c3a53ad621",
        "employee_id": "E0301",
        "agent_name": "workflow_orchestrator_agent",
        "doc_type": "workflow_summary",
        "template_version": "v1",
        "content": "{\n  \"phase\": \"onboarding\",\n  \"employee_id\": \"E0301\",\n  \"workflow_id\": \"f1e4d59f-99b9-4a8a-b7ce-f1600abb97b2\",\n  \"systems\": [\n    \"email\",\n    \"slack\",\n    \"hr-portal\"\n  ],\n  \"generated_at\": \"2026-06-19T02:03:20.388878+00:00\"\n}",
        "generated_on": "2026-06-19T02:03:20.388951"
      },
      {
        "document_id": "d2ee2b24-f260-4fe3-8ade-b72107b7c4e9",
        "employee_id": "E0301",
        "agent_name": "Resume Reviewer Agent",
        "doc_type": "Resume",
        "template_version": "v1",
        "content": "\nResume\n\nName: Rhonda Padilla\nTarget Role: Software Engineer\nDepartment: Engineering\nYears of Experience: 5\n\nSummary:\nExperienced professional with a background in engineering operations and strong execution skills.\nKnown for ownership, communication, and process improvement.\n\nCore Skills:\nMachine learning, pandas, scikit-learn, feature engineering\n\nEducation:\nMBA in HR from Symbiosis Institute of Business Management\n\nSelected Experience:\n- Worked on engineering process improvements and cross-functional coordination.\n- Delivered measurable improvements in software engineer execution and reporting.\n\nKeywords:\nresume, engineering, software engineer, operations, communication, stakeholder management\n",
        "generated_on": "2026-06-19 02:03:20.325189"
      },
      {
        "document_id": "92a6fa8f-95a6-4f33-bcdc-8b3dd3fad507",
        "employee_id": "E0301",
        "agent_name": "Access Management Agent",
        "doc_type": "Contract",
        "template_version": "v2",
        "content": "\nEmployment Contract\n\nThis Employment Agreement is made between ACME Corporation (\"Employer\")\nand **Rhonda Padilla** (\"Employee\") for the role of **Software Engineer** in the **Engineering Department**.\n\n1. Compensation: The employee will be paid an annual CTC of **\u20b91,323,318**.\n2. Work Hours: 40 hours per week, Monday to Friday.\n3. Notice Period: 60 days.\n4. Confidentiality: Employee agrees to maintain confidentiality of all company data.\n\nBy signing this contract, the employee agrees to abide by the policies of ACME Corporation.\n\nACME HR & Legal Team\n",
        "generated_on": "2026-06-19 01:54:15.357013"
      },
      {
        "document_id": "de9e0e36-d543-4905-8dae-4f2441ca63ad",
        "employee_id": "E0301",
        "agent_name": "Offboarding Agent",
        "doc_type": "Contract",
        "template_version": "v3",
        "content": "\nEmployment Contract\n\nThis Employment Agreement is made between ACME Corporation (\"Employer\")\nand **Rhonda Padilla** (\"Employee\") for the role of **Software Engineer** in the **Engineering Department**.\n\n1. Compensation: The employee will be paid an annual CTC of **\u20b91,172,958**.\n2. Work Hours: 40 hours per week, Monday to Friday.\n3. Notice Period: 60 days.\n4. Confidentiality: Employee agrees to maintain confidentiality of all company data.\n\nBy signing this contract, the employee agrees to abide by the policies of ACME Corporation.\n\nACME HR & Legal Team\n",
        "generated_on": "2026-06-19 01:54:15.356536"
      },
      {
        "document_id": "26378033-e79e-4d49-8e3b-a9d18dd82f46",
        "employee_id": "E0301",
        "agent_name": "Knowledge Retrieval Agent",
        "doc_type": "Contract",
        "template_version": "v3",
        "content": "\nEmployment Contract\n\nThis Employment Agreement is made between ACME Corporation (\"Employer\")\nand **Rhonda Padilla** (\"Employee\") for the role of **Software Engineer** in the **Engineering Department**.\n\n1. Compensation: The employee will be paid an annual CTC of **\u20b91,697,753**.\n2. Work Hours: 40 hours per week, Monday to Friday.\n3. Notice Period: 60 days.\n4. Confidentiality: Employee agrees to maintain confidentiality of all company data.\n\nBy signing this contract, the employee agrees to abide by the policies of ACME Corporation.\n\nACME HR & Legal Team\n",
        "generated_on": "2026-06-19 01:54:15.355458"
      },
      {
        "document_id": "96712be9-7de9-4ed0-92d0-fd37a287870a",
        "employee_id": "E0301",
        "agent_name": "Document Generation Agent",
        "doc_type": "Experience Letter",
        "template_version": "v3",
        "content": "EXPERIENCE LETTER\n\nThis is to certify that Oscar Marsh\nworked as a Recruiter in the\nHR department.\n\nThe employee demonstrated professionalism,\nownership, and commitment to business goals.\n\nRegards,\nDocument Generation Agent",
        "generated_on": "2026-06-04 01:55:22.649919"
      }
    ]
  },
  "access": {
    "status": "success",
    "access": [
      {
        "access_id": "3a3dcd91-2d56-491a-a078-ab94cfe44c5e",
        "employee_id": "E0301",
        "system_name": "hr-portal",
        "access_type": "granted",
        "granted_by": "workflow_orchestrator_agent",
        "granted_on": "2026-06-19T02:03:20.375848",
        "revoked_on": "2026-06-19T02:03:20.707220"
      },
      {
        "access_id": "39828044-64ae-4a8b-b73d-3b6b52af3799",
        "employee_id": "E0301",
        "system_name": "slack",
        "access_type": "granted",
        "granted_by": "workflow_orchestrator_agent",
        "granted_on": "2026-06-19T02:03:20.370461",
        "revoked_on": "2026-06-19T02:03:20.713634"
      },
      {
        "access_id": "db6b9f3c-397d-4d11-9d49-4f3f3dac66ec",
        "employee_id": "E0301",
        "system_name": "email",
        "access_type": "granted",
        "granted_by": "workflow_orchestrator_agent",
        "granted_on": "2026-06-19T02:03:20.365173",
        "revoked_on": "2026-06-19T02:03:20.719415"
      },
      {
        "access_id": "0f3ee5df-08e6-4b33-a0c5-3929b22cdcba",
        "employee_id": "E0301",
        "system_name": "Slack",
        "access_type": "Write",
        "granted_by": "Scott Jackson",
        "granted_on": "2026-03-25T01:53:55.302373",
        "revoked_on": "2026-06-19T02:03:20.725061"
      }
    ]
  },
  "memory_roundtrip_ok": false,
  "evaluation": {
    "status": "success",
    "eval_run_id": "83c4d525-a258-4640-9e12-e03bbb76a5ba",
    "score": 80,
    "summary": {
      "workflow_status": "Completed",
      "memory_roundtrip_ok": false,
      "resume_review_used": true,
      "access_handled": true,
      "asset_handled": true,
      "notes": [
        "generate_sample_resumes",
        "shortlist_resumes",
        "start_eval_run",
        "get_employee",
        "create_workflow",
        "save_context_workflow_started",
        "load_context_workflow_started",
        "update_employee_status",
        "grant_access",
        "assign_asset",
        "create_document",
        "save_context_onboarding_complete",
        "load_context_onboarding_complete",

/tmp/ipykernel_1272/2351905436.py:136: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  (datetime.utcnow().isoformat(), "finished", score, json.dumps(summary, default=str), eval_run_id),

<h1> Conclusion And a Discussion Of What Was Covered </h1>



Synthetic Data Generation
Purpose **bold text**

Generate realistic workflow records to simulate business processes.

The generated dataset serves as:

Agent testing data
Search index content
Workflow execution inputs
Demonstration scenarios
Future Production State

In production, this component would be replaced by:

Enterprise systems
Operational databases
Event streams
Workflow management platforms
Persistence Layer
Purpose

Provide a lightweight persistence mechanism using SQLite.

**Responsibilities:**

Workflow storage
Status tracking
Searchable records
Agent-accessible state
Future Production State

**Potential replacements:**

PostgreSQL
Cloud SQL
Snowflake
Enterprise workflow databases

The tool interface should remain unchanged.

Search and Retrieval Layer
Purpose

Provide retrieval capabilities for workflow records.

**Current implementation:**

SQLite queries
Vector search
Metadata retrieval
Future Production State

**Potential upgrades:**

ChromaDB clusters
Vertex AI Search
Elasticsearch
Enterprise knowledge systems

No changes should be required at the agent layer.

Tool Layer
Purpose

Expose workflow functionality as reusable tools.

**Responsibilities:**

Data retrieval
Workflow updates
Document generation
Search operations

Tools act as the abstraction boundary between:

Agents
Business logic
Infrastructure
MCP Integration
Purpose

Expose workflow capabilities through MCP-compatible interfaces.

**Benefits:**

Tool interoperability
Standardized invocation
Multi-agent compatibility
External integration support
Design Principle

Agents should interact with tools through MCP contracts rather than direct database access.

**Agent Layer**
Purpose

Coordinate workflow execution using specialized agents.

Planner Agent

Responsible for:

Understanding requests
Creating execution plans
Delegating tasks
Executor Agent

Responsible for:

Tool execution
Data retrieval
Workflow actions
Reviewer Agent

Responsible for:

Validation
Compliance checks
Final recommendations
Workflow Orchestration
Purpose

Coordinate interactions between agents and tools.

Workflow orchestration manages:

Task sequencing
State transitions
Agent delegation
Result aggregation

This notebook demonstrates the orchestration pattern prior to migration into a dedicated workflow framework.

<h3>API Layer Purpose </h4>

Provide external access to workflow functionality.

Current implementation:

Flask APIs

Potential future implementations:

FastAPI
Cloud Run services
Vertex AI endpoints
Enterprise API gateways
Future Production Architecture
Migration Path

The notebook validates workflow behavior and architectural decisions.

A future production implementation could be structured as:

workflow_automation/
│
├── agents/
│
├── tools/
│
├── workflows/
│
├── data/
│
├── mcp/
│
├── api/
│
├── config/
│
└── tests/

The primary objective of this notebook is to prove:

Workflow viability
Agent interaction patterns
Tool contracts
MCP integration
End-to-end execution

before investing in full production engineering.

**Key Assumptions and Limitations**
Assumptions

Notebook execution is sequential.

Synthetic data represents production workflows.

Local SQLite is sufficient for validation.

LLM-generated artifacts are acceptable for demonstration purposes.

<h3> Limitations </h3>
Not optimized for scale.
Minimal observability.
Limited testing coverage.
Simplified security model.
Intended as a proof-of-concept.